/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The properties specific to the "acceptCoupon" effect. This gets triggered whenever the coupon is valid and all other conditions in the rules of its campaign are met.
 * @export
 * @interface AcceptCouponEffectProps
 */
export interface AcceptCouponEffectProps {
    /**
     * The coupon code that was accepted.
     * @type {string}
     * @memberof AcceptCouponEffectProps
     */
    value: string;
}

/**
 * Check if a given object implements the AcceptCouponEffectProps interface.
 */
export function instanceOfAcceptCouponEffectProps(value: object): value is AcceptCouponEffectProps {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function AcceptCouponEffectPropsFromJSON(json: any): AcceptCouponEffectProps {
    return AcceptCouponEffectPropsFromJSONTyped(json, false);
}

export function AcceptCouponEffectPropsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceptCouponEffectProps {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
    };
}

export function AcceptCouponEffectPropsToJSON(json: any): AcceptCouponEffectProps {
    return AcceptCouponEffectPropsToJSONTyped(json, false);
}

export function AcceptCouponEffectPropsToJSONTyped(value?: AcceptCouponEffectProps | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
    };
}

