/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AchievementProgressWithDefinition
 */
export interface AchievementProgressWithDefinition {
    /**
     * The status of the achievement.
     * @type {string}
     * @memberof AchievementProgressWithDefinition
     */
    status: AchievementProgressWithDefinitionStatusEnum;
    /**
     * The current progress of the customer in the achievement.
     * @type {number}
     * @memberof AchievementProgressWithDefinition
     */
    progress: number;
    /**
     * Timestamp at which the customer started the achievement.
     * @type {Date}
     * @memberof AchievementProgressWithDefinition
     */
    startDate?: Date;
    /**
     * Timestamp at which point the customer completed the achievement.
     * @type {Date}
     * @memberof AchievementProgressWithDefinition
     */
    completionDate?: Date;
    /**
     * Timestamp at which point the achievement ends and resets for the customer.
     * @type {Date}
     * @memberof AchievementProgressWithDefinition
     */
    endDate?: Date;
    /**
     * The internal ID of the achievement.
     * @type {number}
     * @memberof AchievementProgressWithDefinition
     */
    achievementId: number;
    /**
     * The internal name of the achievement used in API requests.
     * 
     * @type {string}
     * @memberof AchievementProgressWithDefinition
     */
    name: string;
    /**
     * The display name of the achievement in the Campaign Manager.
     * @type {string}
     * @memberof AchievementProgressWithDefinition
     */
    title: string;
    /**
     * The description of the achievement in the Campaign Manager.
     * @type {string}
     * @memberof AchievementProgressWithDefinition
     */
    description: string;
    /**
     * The ID of the campaign the achievement belongs to.
     * @type {number}
     * @memberof AchievementProgressWithDefinition
     */
    campaignId: number;
    /**
     * The required number of actions or the transactional milestone to complete the achievement.
     * @type {number}
     * @memberof AchievementProgressWithDefinition
     */
    target?: number;
    /**
     * The policy that determines if and how the achievement recurs.
     * - `no_recurrence`: The achievement can be completed only once.
     * - `on_expiration`: The achievement resets after it expires and becomes available again.
     * - `on_completion`: When the customer progress status reaches `completed`, the achievement resets and becomes available again.
     * 
     * @type {string}
     * @memberof AchievementProgressWithDefinition
     */
    achievementRecurrencePolicy: AchievementProgressWithDefinitionAchievementRecurrencePolicyEnum;
    /**
     * The policy that determines how the achievement starts, ends, or resets.
     * - `user_action`: The achievement ends or resets relative to when the customer started the achievement.
     * - `fixed_schedule`: The achievement starts, ends, or resets for all customers following a fixed schedule.
     * 
     * @type {string}
     * @memberof AchievementProgressWithDefinition
     */
    achievementActivationPolicy: AchievementProgressWithDefinitionAchievementActivationPolicyEnum;
    /**
     * The achievement's start date when `achievementActivationPolicy` is equal to `fixed_schedule`.
     * 
     * **Note:** It is an RFC3339 timestamp string.
     * 
     * @type {Date}
     * @memberof AchievementProgressWithDefinition
     */
    achievementFixedStartDate?: Date;
    /**
     * The achievement's end date. If defined, customers cannot participate in the achievement after this date.
     * 
     * **Note:** It is an RFC3339 timestamp string.
     * 
     * @type {Date}
     * @memberof AchievementProgressWithDefinition
     */
    achievementEndDate?: Date;
    /**
     * When `true`, customer progress can be rolled back in completed achievements.
     * @type {boolean}
     * @memberof AchievementProgressWithDefinition
     */
    achievementAllowRollbackAfterCompletion?: boolean;
}


/**
 * @export
 */
export const AchievementProgressWithDefinitionStatusEnum = {
    Inprogress: 'inprogress',
    Completed: 'completed',
    Expired: 'expired',
    NotStarted: 'not_started'
} as const;
export type AchievementProgressWithDefinitionStatusEnum = typeof AchievementProgressWithDefinitionStatusEnum[keyof typeof AchievementProgressWithDefinitionStatusEnum];

/**
 * @export
 */
export const AchievementProgressWithDefinitionAchievementRecurrencePolicyEnum = {
    NoRecurrence: 'no_recurrence',
    OnExpiration: 'on_expiration',
    OnCompletion: 'on_completion'
} as const;
export type AchievementProgressWithDefinitionAchievementRecurrencePolicyEnum = typeof AchievementProgressWithDefinitionAchievementRecurrencePolicyEnum[keyof typeof AchievementProgressWithDefinitionAchievementRecurrencePolicyEnum];

/**
 * @export
 */
export const AchievementProgressWithDefinitionAchievementActivationPolicyEnum = {
    UserAction: 'user_action',
    FixedSchedule: 'fixed_schedule'
} as const;
export type AchievementProgressWithDefinitionAchievementActivationPolicyEnum = typeof AchievementProgressWithDefinitionAchievementActivationPolicyEnum[keyof typeof AchievementProgressWithDefinitionAchievementActivationPolicyEnum];


/**
 * Check if a given object implements the AchievementProgressWithDefinition interface.
 */
export function instanceOfAchievementProgressWithDefinition(value: object): value is AchievementProgressWithDefinition {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    if (!('achievementId' in value) || value['achievementId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('campaignId' in value) || value['campaignId'] === undefined) return false;
    if (!('achievementRecurrencePolicy' in value) || value['achievementRecurrencePolicy'] === undefined) return false;
    if (!('achievementActivationPolicy' in value) || value['achievementActivationPolicy'] === undefined) return false;
    return true;
}

export function AchievementProgressWithDefinitionFromJSON(json: any): AchievementProgressWithDefinition {
    return AchievementProgressWithDefinitionFromJSONTyped(json, false);
}

export function AchievementProgressWithDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AchievementProgressWithDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'progress': json['progress'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'completionDate': json['completionDate'] == null ? undefined : (new Date(json['completionDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'achievementId': json['achievementId'],
        'name': json['name'],
        'title': json['title'],
        'description': json['description'],
        'campaignId': json['campaignId'],
        'target': json['target'] == null ? undefined : json['target'],
        'achievementRecurrencePolicy': json['achievementRecurrencePolicy'],
        'achievementActivationPolicy': json['achievementActivationPolicy'],
        'achievementFixedStartDate': json['achievementFixedStartDate'] == null ? undefined : (new Date(json['achievementFixedStartDate'])),
        'achievementEndDate': json['achievementEndDate'] == null ? undefined : (new Date(json['achievementEndDate'])),
        'achievementAllowRollbackAfterCompletion': json['achievementAllowRollbackAfterCompletion'] == null ? undefined : json['achievementAllowRollbackAfterCompletion'],
    };
}

export function AchievementProgressWithDefinitionToJSON(json: any): AchievementProgressWithDefinition {
    return AchievementProgressWithDefinitionToJSONTyped(json, false);
}

export function AchievementProgressWithDefinitionToJSONTyped(value?: AchievementProgressWithDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'progress': value['progress'],
        'startDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
        'completionDate': value['completionDate'] == null ? value['completionDate'] : value['completionDate'].toISOString(),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString(),
        'achievementId': value['achievementId'],
        'name': value['name'],
        'title': value['title'],
        'description': value['description'],
        'campaignId': value['campaignId'],
        'target': value['target'],
        'achievementRecurrencePolicy': value['achievementRecurrencePolicy'],
        'achievementActivationPolicy': value['achievementActivationPolicy'],
        'achievementFixedStartDate': value['achievementFixedStartDate'] == null ? value['achievementFixedStartDate'] : value['achievementFixedStartDate'].toISOString(),
        'achievementEndDate': value['achievementEndDate'] == null ? value['achievementEndDate'] : value['achievementEndDate'].toISOString(),
        'achievementAllowRollbackAfterCompletion': value['achievementAllowRollbackAfterCompletion'],
    };
}

