/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddedDeductedPointsBalancesAction } from './AddedDeductedPointsBalancesAction';
import {
    AddedDeductedPointsBalancesActionFromJSON,
    AddedDeductedPointsBalancesActionFromJSONTyped,
    AddedDeductedPointsBalancesActionToJSON,
    AddedDeductedPointsBalancesActionToJSONTyped,
} from './AddedDeductedPointsBalancesAction';

/**
 * 
 * @export
 * @interface AddedDeductedPointsBalancesNotification
 */
export interface AddedDeductedPointsBalancesNotification {
    /**
     * The name of the employee who added or deducted points.
     * @type {string}
     * @memberof AddedDeductedPointsBalancesNotification
     */
    employeeName: string;
    /**
     * The ID of the loyalty program.
     * @type {number}
     * @memberof AddedDeductedPointsBalancesNotification
     */
    loyaltyProgramID: number;
    /**
     * The type of notification.
     * @type {AddedDeductedPointsBalancesNotificationNotificationTypeEnum}
     * @memberof AddedDeductedPointsBalancesNotification
     */
    notificationType: AddedDeductedPointsBalancesNotificationNotificationTypeEnum;
    /**
     * The integration ID of the customer profile to whom points were added or deducted.
     * @type {string}
     * @memberof AddedDeductedPointsBalancesNotification
     */
    profileIntegrationID: string;
    /**
     * The integration ID of the session through which the points were earned or lost.
     * @type {string}
     * @memberof AddedDeductedPointsBalancesNotification
     */
    sessionIntegrationID: string;
    /**
     * The ID of the subledger within the loyalty program where these points were added.
     * @type {string}
     * @memberof AddedDeductedPointsBalancesNotification
     */
    subledgerID: string;
    /**
     * The notification source, that is, it indicates whether the points were added or deducted via one of the following routes:
     * - [The Campaign Manager](/docs/product/getting-started)
     * - [Management API](/management-api#tag/Loyalty)
     * - [Rule Engine](/docs/product/applications/evaluation-order-for-rules-and-filters)
     * 
     * @type {AddedDeductedPointsBalancesNotificationTypeOfChangeEnum}
     * @memberof AddedDeductedPointsBalancesNotification
     */
    typeOfChange: AddedDeductedPointsBalancesNotificationTypeOfChangeEnum;
    /**
     * The ID of the employee who added or deducted points.
     * @type {number}
     * @memberof AddedDeductedPointsBalancesNotification
     */
    userID: number;
    /**
     * The list of actions that have been triggered in the loyalty program.
     * @type {Array<AddedDeductedPointsBalancesAction>}
     * @memberof AddedDeductedPointsBalancesNotification
     */
    actions: Array<AddedDeductedPointsBalancesAction>;
    /**
     * The current points balance.
     * @type {number}
     * @memberof AddedDeductedPointsBalancesNotification
     */
    currentPoints: number;
}


/**
 * @export
 */
export const AddedDeductedPointsBalancesNotificationNotificationTypeEnum = {
    LoyaltyAddedDeductedPointsBalances: 'LoyaltyAddedDeductedPointsBalances'
} as const;
export type AddedDeductedPointsBalancesNotificationNotificationTypeEnum = typeof AddedDeductedPointsBalancesNotificationNotificationTypeEnum[keyof typeof AddedDeductedPointsBalancesNotificationNotificationTypeEnum];

/**
 * @export
 */
export const AddedDeductedPointsBalancesNotificationTypeOfChangeEnum = {
    CampaignManager: 'campaign_manager',
    RuleEngine: 'rule_engine',
    ManagementApi: 'management_api'
} as const;
export type AddedDeductedPointsBalancesNotificationTypeOfChangeEnum = typeof AddedDeductedPointsBalancesNotificationTypeOfChangeEnum[keyof typeof AddedDeductedPointsBalancesNotificationTypeOfChangeEnum];


/**
 * Check if a given object implements the AddedDeductedPointsBalancesNotification interface.
 */
export function instanceOfAddedDeductedPointsBalancesNotification(value: object): value is AddedDeductedPointsBalancesNotification {
    const _v = value as Record<PropertyKey, unknown>;
    if ((!('employeeName' in _v) && !('EmployeeName' in _v)) || (_v['employeeName'] === undefined && _v['EmployeeName'] === undefined)) return false;
    if ((!('loyaltyProgramID' in _v) && !('LoyaltyProgramID' in _v)) || (_v['loyaltyProgramID'] === undefined && _v['LoyaltyProgramID'] === undefined)) return false;
    if ((!('notificationType' in _v) && !('NotificationType' in _v)) || (_v['notificationType'] === undefined && _v['NotificationType'] === undefined)) return false;
    if (_v['notificationType'] !== 'LoyaltyAddedDeductedPointsBalances' && _v['NotificationType'] !== 'LoyaltyAddedDeductedPointsBalances') return false;
    
    if ((!('profileIntegrationID' in _v) && !('ProfileIntegrationID' in _v)) || (_v['profileIntegrationID'] === undefined && _v['ProfileIntegrationID'] === undefined)) return false;
    if ((!('sessionIntegrationID' in _v) && !('SessionIntegrationID' in _v)) || (_v['sessionIntegrationID'] === undefined && _v['SessionIntegrationID'] === undefined)) return false;
    if ((!('subledgerID' in _v) && !('SubledgerID' in _v)) || (_v['subledgerID'] === undefined && _v['SubledgerID'] === undefined)) return false;
    if ((!('typeOfChange' in _v) && !('TypeOfChange' in _v)) || (_v['typeOfChange'] === undefined && _v['TypeOfChange'] === undefined)) return false;
    if ((!('userID' in _v) && !('UserID' in _v)) || (_v['userID'] === undefined && _v['UserID'] === undefined)) return false;
    if ((!('actions' in _v) && !('Actions' in _v)) || (_v['actions'] === undefined && _v['Actions'] === undefined)) return false;
    if ((!('currentPoints' in _v) && !('CurrentPoints' in _v)) || (_v['currentPoints'] === undefined && _v['CurrentPoints'] === undefined)) return false;
    return true;
}

export function AddedDeductedPointsBalancesNotificationFromJSON(json: any): AddedDeductedPointsBalancesNotification {
    return AddedDeductedPointsBalancesNotificationFromJSONTyped(json, false);
}

export function AddedDeductedPointsBalancesNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddedDeductedPointsBalancesNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'employeeName': json['EmployeeName'],
        'loyaltyProgramID': json['LoyaltyProgramID'],
        'notificationType': json['NotificationType'],
        'profileIntegrationID': json['ProfileIntegrationID'],
        'sessionIntegrationID': json['SessionIntegrationID'],
        'subledgerID': json['SubledgerID'],
        'typeOfChange': json['TypeOfChange'],
        'userID': json['UserID'],
        'actions': ((json['Actions'] as Array<any>).map(AddedDeductedPointsBalancesActionFromJSON)),
        'currentPoints': json['CurrentPoints'],
    };
}

export function AddedDeductedPointsBalancesNotificationToJSON(json: any): AddedDeductedPointsBalancesNotification {
    return AddedDeductedPointsBalancesNotificationToJSONTyped(json, false);
}

export function AddedDeductedPointsBalancesNotificationToJSONTyped(value?: AddedDeductedPointsBalancesNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'EmployeeName': value['employeeName'],
        'LoyaltyProgramID': value['loyaltyProgramID'],
        'NotificationType': value['notificationType'],
        'ProfileIntegrationID': value['profileIntegrationID'],
        'SessionIntegrationID': value['sessionIntegrationID'],
        'SubledgerID': value['subledgerID'],
        'TypeOfChange': value['typeOfChange'],
        'UserID': value['userID'],
        'Actions': ((value['actions'] as Array<any>).map(AddedDeductedPointsBalancesActionToJSON)),
        'CurrentPoints': value['currentPoints'],
    };
}

