/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * This effect is triggered when a rule containing an [Update audience](https://docs.talon.one/docs/product/rules/effects/use-effects#update-an-audience) effect with **Add customer to an audience** selected is validated. It indicates that a customer was added to an audience and is returned when a customer session is opened, updated, or closed.
 * @export
 * @interface AddToAudienceEffectProps
 */
export interface AddToAudienceEffectProps {
    /**
     * The internal ID of the audience.
     * @type {number}
     * @memberof AddToAudienceEffectProps
     */
    audienceId?: number;
    /**
     * The name of the audience.
     * @type {string}
     * @memberof AddToAudienceEffectProps
     */
    audienceName?: string;
    /**
     * The ID of the customer profile in the third-party integration platform.
     * @type {string}
     * @memberof AddToAudienceEffectProps
     */
    profileIntegrationId?: string;
    /**
     * The internal ID of the customer profile.
     * @type {number}
     * @memberof AddToAudienceEffectProps
     */
    profileId?: number;
}

/**
 * Check if a given object implements the AddToAudienceEffectProps interface.
 */
export function instanceOfAddToAudienceEffectProps(value: object): value is AddToAudienceEffectProps {
    const _v = value as Record<PropertyKey, unknown>;
    return true;
}

export function AddToAudienceEffectPropsFromJSON(json: any): AddToAudienceEffectProps {
    return AddToAudienceEffectPropsFromJSONTyped(json, false);
}

export function AddToAudienceEffectPropsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddToAudienceEffectProps {
    if (json == null) {
        return json;
    }
    return {
        
        'audienceId': json['audienceId'] == null ? undefined : json['audienceId'],
        'audienceName': json['audienceName'] == null ? undefined : json['audienceName'],
        'profileIntegrationId': json['profileIntegrationId'] == null ? undefined : json['profileIntegrationId'],
        'profileId': json['profileId'] == null ? undefined : json['profileId'],
    };
}

export function AddToAudienceEffectPropsToJSON(json: any): AddToAudienceEffectProps {
    return AddToAudienceEffectPropsToJSONTyped(json, false);
}

export function AddToAudienceEffectPropsToJSONTyped(value?: AddToAudienceEffectProps | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'audienceId': value['audienceId'],
        'audienceName': value['audienceName'],
        'profileIntegrationId': value['profileIntegrationId'],
        'profileId': value['profileId'],
    };
}

