/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationAPIKey
 */
export interface ApplicationAPIKey {
    /**
     * Title of the API key.
     * @type {string}
     * @memberof ApplicationAPIKey
     */
    title: string;
    /**
     * The date the API key expires.
     * @type {Date}
     * @memberof ApplicationAPIKey
     */
    expires: Date;
    /**
     * The third-party platform the API key is valid for. Use `none` for a generic API key to be used
     * from your own integration layer.
     * 
     * @type {string}
     * @memberof ApplicationAPIKey
     */
    platform?: ApplicationAPIKeyPlatformEnum;
    /**
     * The API key type. Can be empty or `staging`.
     * 
     * Staging API keys can only be used for dry requests with the [Update customer session](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint, [Update customer profile](https://docs.talon.one/integration-api#tag/Customer-profiles/operation/updateCustomerProfileV2) endpoint, and [Track event](https://docs.talon.one/integration-api#tag/Events/operation/trackEventV2) endpoint.
     * 
     * When using the _Update customer profile_ endpoint with a staging API key, the query parameter `runRuleEngine` must be `true`.
     * 
     * @type {string}
     * @memberof ApplicationAPIKey
     */
    type?: ApplicationAPIKeyTypeEnum;
    /**
     * A time offset in nanoseconds associated with the API key. When making a request using the API key, rule evaluation is based on a date that is calculated by adding the offset to the current date.
     * 
     * @type {number}
     * @memberof ApplicationAPIKey
     */
    timeOffset?: number;
    /**
     * ID of the API Key.
     * @type {number}
     * @memberof ApplicationAPIKey
     */
    id: number;
    /**
     * ID of user who created.
     * @type {number}
     * @memberof ApplicationAPIKey
     */
    createdBy: number;
    /**
     * ID of account the key is used for.
     * @type {number}
     * @memberof ApplicationAPIKey
     */
    accountID: number;
    /**
     * ID of application the key is used for.
     * @type {number}
     * @memberof ApplicationAPIKey
     */
    applicationID: number;
    /**
     * The date the API key was created.
     * @type {Date}
     * @memberof ApplicationAPIKey
     */
    created: Date;
}


/**
 * @export
 */
export const ApplicationAPIKeyPlatformEnum = {
    None: 'none',
    Segment: 'segment',
    Braze: 'braze',
    Mparticle: 'mparticle',
    Shopify: 'shopify',
    Iterable: 'iterable',
    CustomerEngagement: 'customer_engagement',
    CustomerData: 'customer_data',
    Salesforce: 'salesforce',
    Emarsys: 'emarsys'
} as const;
export type ApplicationAPIKeyPlatformEnum = typeof ApplicationAPIKeyPlatformEnum[keyof typeof ApplicationAPIKeyPlatformEnum];

/**
 * @export
 */
export const ApplicationAPIKeyTypeEnum = {
    Staging: 'staging'
} as const;
export type ApplicationAPIKeyTypeEnum = typeof ApplicationAPIKeyTypeEnum[keyof typeof ApplicationAPIKeyTypeEnum];


/**
 * Check if a given object implements the ApplicationAPIKey interface.
 */
export function instanceOfApplicationAPIKey(value: object): value is ApplicationAPIKey {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('expires' in value) || value['expires'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('accountID' in value) || value['accountID'] === undefined) return false;
    if (!('applicationID' in value) || value['applicationID'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    return true;
}

export function ApplicationAPIKeyFromJSON(json: any): ApplicationAPIKey {
    return ApplicationAPIKeyFromJSONTyped(json, false);
}

export function ApplicationAPIKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationAPIKey {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'expires': (new Date(json['expires'])),
        'platform': json['platform'] == null ? undefined : json['platform'],
        'type': json['type'] == null ? undefined : json['type'],
        'timeOffset': json['timeOffset'] == null ? undefined : json['timeOffset'],
        'id': json['id'],
        'createdBy': json['createdBy'],
        'accountID': json['accountID'],
        'applicationID': json['applicationID'],
        'created': (new Date(json['created'])),
    };
}

export function ApplicationAPIKeyToJSON(json: any): ApplicationAPIKey {
    return ApplicationAPIKeyToJSONTyped(json, false);
}

export function ApplicationAPIKeyToJSONTyped(value?: ApplicationAPIKey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'expires': value['expires'].toISOString(),
        'platform': value['platform'],
        'type': value['type'],
        'timeOffset': value['timeOffset'],
        'id': value['id'],
        'createdBy': value['createdBy'],
        'accountID': value['accountID'],
        'applicationID': value['applicationID'],
        'created': value['created'].toISOString(),
    };
}

