/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Provides statistics regarding an application's campaigns.
 * @export
 * @interface ApplicationCampaignStats
 */
export interface ApplicationCampaignStats {
    /**
     * Number of disabled campaigns.
     * @type {number}
     * @memberof ApplicationCampaignStats
     */
    disabled: number;
    /**
     * Number of staged campaigns.
     * @type {number}
     * @memberof ApplicationCampaignStats
     */
    staged: number;
    /**
     * Number of scheduled campaigns.
     * @type {number}
     * @memberof ApplicationCampaignStats
     */
    scheduled: number;
    /**
     * Number of running campaigns.
     * @type {number}
     * @memberof ApplicationCampaignStats
     */
    running: number;
    /**
     * Number of expired campaigns.
     * @type {number}
     * @memberof ApplicationCampaignStats
     */
    expired: number;
    /**
     * Number of archived campaigns.
     * @type {number}
     * @memberof ApplicationCampaignStats
     */
    archived: number;
}

/**
 * Check if a given object implements the ApplicationCampaignStats interface.
 */
export function instanceOfApplicationCampaignStats(value: object): value is ApplicationCampaignStats {
    if (!('disabled' in value) || value['disabled'] === undefined) return false;
    if (!('staged' in value) || value['staged'] === undefined) return false;
    if (!('scheduled' in value) || value['scheduled'] === undefined) return false;
    if (!('running' in value) || value['running'] === undefined) return false;
    if (!('expired' in value) || value['expired'] === undefined) return false;
    if (!('archived' in value) || value['archived'] === undefined) return false;
    return true;
}

export function ApplicationCampaignStatsFromJSON(json: any): ApplicationCampaignStats {
    return ApplicationCampaignStatsFromJSONTyped(json, false);
}

export function ApplicationCampaignStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationCampaignStats {
    if (json == null) {
        return json;
    }
    return {
        
        'disabled': json['disabled'],
        'staged': json['staged'],
        'scheduled': json['scheduled'],
        'running': json['running'],
        'expired': json['expired'],
        'archived': json['archived'],
    };
}

export function ApplicationCampaignStatsToJSON(json: any): ApplicationCampaignStats {
    return ApplicationCampaignStatsToJSONTyped(json, false);
}

export function ApplicationCampaignStatsToJSONTyped(value?: ApplicationCampaignStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'disabled': value['disabled'],
        'staged': value['staged'],
        'scheduled': value['scheduled'],
        'running': value['running'],
        'expired': value['expired'],
        'archived': value['archived'],
    };
}

