/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AsyncCouponCreationResponse
 */
export interface AsyncCouponCreationResponse {
    /**
     * The batch ID that all coupons created by the request will have.
     * @type {string}
     * @memberof AsyncCouponCreationResponse
     */
    batchId: string;
}

/**
 * Check if a given object implements the AsyncCouponCreationResponse interface.
 */
export function instanceOfAsyncCouponCreationResponse(value: object): value is AsyncCouponCreationResponse {
    if (!('batchId' in value) || value['batchId'] === undefined) return false;
    return true;
}

export function AsyncCouponCreationResponseFromJSON(json: any): AsyncCouponCreationResponse {
    return AsyncCouponCreationResponseFromJSONTyped(json, false);
}

export function AsyncCouponCreationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AsyncCouponCreationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'batchId': json['batchId'],
    };
}

export function AsyncCouponCreationResponseToJSON(json: any): AsyncCouponCreationResponse {
    return AsyncCouponCreationResponseToJSONTyped(json, false);
}

export function AsyncCouponCreationResponseToJSONTyped(value?: AsyncCouponCreationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'batchId': value['batchId'],
    };
}

