/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Arbitrary settings associated with attributes.
 * @export
 * @interface AttributesMandatory
 */
export interface AttributesMandatory {
    /**
     * List of mandatory attributes for campaigns.
     * @type {Array<string>}
     * @memberof AttributesMandatory
     */
    campaigns?: Array<string>;
    /**
     * List of mandatory attributes for campaigns.
     * @type {Array<string>}
     * @memberof AttributesMandatory
     */
    coupons?: Array<string>;
}

/**
 * Check if a given object implements the AttributesMandatory interface.
 */
export function instanceOfAttributesMandatory(value: object): value is AttributesMandatory {
    return true;
}

export function AttributesMandatoryFromJSON(json: any): AttributesMandatory {
    return AttributesMandatoryFromJSONTyped(json, false);
}

export function AttributesMandatoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttributesMandatory {
    if (json == null) {
        return json;
    }
    return {
        
        'campaigns': json['campaigns'] == null ? undefined : json['campaigns'],
        'coupons': json['coupons'] == null ? undefined : json['coupons'],
    };
}

export function AttributesMandatoryToJSON(json: any): AttributesMandatory {
    return AttributesMandatoryToJSONTyped(json, false);
}

export function AttributesMandatoryToJSONTyped(value?: AttributesMandatory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'campaigns': value['campaigns'],
        'coupons': value['coupons'],
    };
}

