/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Awards points per item in the cart.
 * @export
 * @interface AwardLoyaltyPointsAllItemsTarget
 */
export interface AwardLoyaltyPointsAllItemsTarget {
    /**
     * A target discriminator of type `allItems`.
     */
    type: AwardLoyaltyPointsAllItemsTargetTypeEnum;
}


/**
 * @export
 */
export const AwardLoyaltyPointsAllItemsTargetTypeEnum = {
    AllItems: 'allItems',
} as const;
export type AwardLoyaltyPointsAllItemsTargetTypeEnum = typeof AwardLoyaltyPointsAllItemsTargetTypeEnum[keyof typeof AwardLoyaltyPointsAllItemsTargetTypeEnum];


/**
 * Check if a given object implements the AwardLoyaltyPointsAllItemsTarget interface.
 */
export function instanceOfAwardLoyaltyPointsAllItemsTarget(value: object): value is AwardLoyaltyPointsAllItemsTarget {
    const _v = value as Record<PropertyKey, unknown>;
    if (!('type' in _v) || _v['type'] === undefined) return false;
    if (_v['type'] !== 'allItems') return false;
    
    return true;
}

export function AwardLoyaltyPointsAllItemsTargetFromJSON(json: any): AwardLoyaltyPointsAllItemsTarget {
    return AwardLoyaltyPointsAllItemsTargetFromJSONTyped(json, false);
}

export function AwardLoyaltyPointsAllItemsTargetFromJSONTyped(json: any, ignoreDiscriminator: boolean): AwardLoyaltyPointsAllItemsTarget {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function AwardLoyaltyPointsAllItemsTargetToJSON(json: any): AwardLoyaltyPointsAllItemsTarget {
    return AwardLoyaltyPointsAllItemsTargetToJSONTyped(json, false);
}

export function AwardLoyaltyPointsAllItemsTargetToJSONTyped(value?: AwardLoyaltyPointsAllItemsTarget | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

