/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BestPriorPriceMetadata } from './BestPriorPriceMetadata';
import {
    BestPriorPriceMetadataFromJSON,
    BestPriorPriceMetadataFromJSONTyped,
    BestPriorPriceMetadataToJSON,
    BestPriorPriceMetadataToJSONTyped,
} from './BestPriorPriceMetadata';

/**
 * 
 * @export
 * @interface BestPriorPrice
 */
export interface BestPriorPrice {
    /**
     * sku
     * @type {string}
     * @memberof BestPriorPrice
     */
    sku: string;
    /**
     * The date and time when the best price was observed.
     * @type {Date}
     * @memberof BestPriorPrice
     */
    observedAt: Date;
    /**
     * The context ID of the context active at the time of observation.
     * 
     * @type {string}
     * @memberof BestPriorPrice
     */
    contextId: string;
    /**
     * Price of the item.
     * @type {number}
     * @memberof BestPriorPrice
     */
    price: number;
    /**
     * 
     * @type {BestPriorPriceMetadata}
     * @memberof BestPriorPrice
     */
    metadata: BestPriorPriceMetadata;
    /**
     * 
     * @type {object}
     * @memberof BestPriorPrice
     */
    target: object;
}

/**
 * Check if a given object implements the BestPriorPrice interface.
 */
export function instanceOfBestPriorPrice(value: object): value is BestPriorPrice {
    if (!('sku' in value) || value['sku'] === undefined) return false;
    if (!('observedAt' in value) || value['observedAt'] === undefined) return false;
    if (!('contextId' in value) || value['contextId'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('target' in value) || value['target'] === undefined) return false;
    return true;
}

export function BestPriorPriceFromJSON(json: any): BestPriorPrice {
    return BestPriorPriceFromJSONTyped(json, false);
}

export function BestPriorPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): BestPriorPrice {
    if (json == null) {
        return json;
    }
    return {
        
        'sku': json['sku'],
        'observedAt': (new Date(json['observedAt'])),
        'contextId': json['contextId'],
        'price': json['price'],
        'metadata': BestPriorPriceMetadataFromJSON(json['metadata']),
        'target': json['target'],
    };
}

export function BestPriorPriceToJSON(json: any): BestPriorPrice {
    return BestPriorPriceToJSONTyped(json, false);
}

export function BestPriorPriceToJSONTyped(value?: BestPriorPrice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sku': value['sku'],
        'observedAt': value['observedAt'].toISOString(),
        'contextId': value['contextId'],
        'price': value['price'],
        'metadata': BestPriorPriceMetadataToJSON(value['metadata']),
        'target': value['target'],
    };
}

