/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Auxiliary data for found price observation.
 * @export
 * @interface BestPriorPriceMetadata
 */
export interface BestPriorPriceMetadata {
    /**
     * 
     * @type {Array<number>}
     * @memberof BestPriorPriceMetadata
     */
    influencingCampaignIDs?: Array<number>;
    /**
     * Identifier related to the `referenceId` used during a `ADD_PRICE_ADJUSTMENT` action  using the [Sync cart item catalog endpoint](https://docs.talon.one/integration-api#tag/Catalogs/operation/syncCatalog).
     * @type {string}
     * @memberof BestPriorPriceMetadata
     */
    adjustmentReferenceID?: string;
}

/**
 * Check if a given object implements the BestPriorPriceMetadata interface.
 */
export function instanceOfBestPriorPriceMetadata(value: object): value is BestPriorPriceMetadata {
    return true;
}

export function BestPriorPriceMetadataFromJSON(json: any): BestPriorPriceMetadata {
    return BestPriorPriceMetadataFromJSONTyped(json, false);
}

export function BestPriorPriceMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BestPriorPriceMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'influencingCampaignIDs': json['influencingCampaignIDs'] == null ? undefined : json['influencingCampaignIDs'],
        'adjustmentReferenceID': json['adjustmentReferenceID'] == null ? undefined : json['adjustmentReferenceID'],
    };
}

export function BestPriorPriceMetadataToJSON(json: any): BestPriorPriceMetadata {
    return BestPriorPriceMetadataToJSONTyped(json, false);
}

export function BestPriorPriceMetadataToJSONTyped(value?: BestPriorPriceMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'influencingCampaignIDs': value['influencingCampaignIDs'],
        'adjustmentReferenceID': value['adjustmentReferenceID'],
    };
}

