/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CampaignEditedNotificationItem } from './CampaignEditedNotificationItem';
import {
    CampaignEditedNotificationItemFromJSON,
    CampaignEditedNotificationItemFromJSONTyped,
    CampaignEditedNotificationItemToJSON,
    CampaignEditedNotificationItemToJSONTyped,
} from './CampaignEditedNotificationItem';

/**
 * 
 * @export
 * @interface CampaignEditedNotification
 */
export interface CampaignEditedNotification {
    /**
     * The type of the notification
     * @type {CampaignEditedNotificationNotificationTypeEnum}
     * @memberof CampaignEditedNotification
     */
    notificationType: CampaignEditedNotificationNotificationTypeEnum;
    /**
     * The total size of the result set.
     * @type {number}
     * @memberof CampaignEditedNotification
     */
    totalResultSize: number;
    /**
     * A list of campaign notification data.
     * @type {Array<CampaignEditedNotificationItem>}
     * @memberof CampaignEditedNotification
     */
    data?: Array<CampaignEditedNotificationItem>;
}


/**
 * @export
 */
export const CampaignEditedNotificationNotificationTypeEnum = {
    CampaignNotification: 'CampaignNotification'
} as const;
export type CampaignEditedNotificationNotificationTypeEnum = typeof CampaignEditedNotificationNotificationTypeEnum[keyof typeof CampaignEditedNotificationNotificationTypeEnum];


/**
 * Check if a given object implements the CampaignEditedNotification interface.
 */
export function instanceOfCampaignEditedNotification(value: object): value is CampaignEditedNotification {
    const _v = value as Record<PropertyKey, unknown>;
    if ((!('notificationType' in _v) && !('NotificationType' in _v)) || (_v['notificationType'] === undefined && _v['NotificationType'] === undefined)) return false;
    if (_v['notificationType'] !== 'CampaignNotification' && _v['NotificationType'] !== 'CampaignNotification') return false;
    
    if ((!('totalResultSize' in _v) && !('TotalResultSize' in _v)) || (_v['totalResultSize'] === undefined && _v['TotalResultSize'] === undefined)) return false;
    return true;
}

export function CampaignEditedNotificationFromJSON(json: any): CampaignEditedNotification {
    return CampaignEditedNotificationFromJSONTyped(json, false);
}

export function CampaignEditedNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignEditedNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'notificationType': json['NotificationType'],
        'totalResultSize': json['TotalResultSize'],
        'data': json['Data'] == null ? undefined : ((json['Data'] as Array<any>).map(CampaignEditedNotificationItemFromJSON)),
    };
}

export function CampaignEditedNotificationToJSON(json: any): CampaignEditedNotification {
    return CampaignEditedNotificationToJSONTyped(json, false);
}

export function CampaignEditedNotificationToJSONTyped(value?: CampaignEditedNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'NotificationType': value['notificationType'],
        'TotalResultSize': value['totalResultSize'],
        'Data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CampaignEditedNotificationItemToJSON)),
    };
}

