/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CampaignDeactivationRequest
 */
export interface CampaignDeactivationRequest {
    /**
     * The list of IDs of the users receiving the deactivation request emails.
     * @type {Array<number>}
     * @memberof CampaignDeactivationRequest
     */
    userIds: Array<number>;
}

/**
 * Check if a given object implements the CampaignDeactivationRequest interface.
 */
export function instanceOfCampaignDeactivationRequest(value: object): value is CampaignDeactivationRequest {
    if (!('userIds' in value) || value['userIds'] === undefined) return false;
    return true;
}

export function CampaignDeactivationRequestFromJSON(json: any): CampaignDeactivationRequest {
    return CampaignDeactivationRequestFromJSONTyped(json, false);
}

export function CampaignDeactivationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignDeactivationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userIds': json['userIds'],
    };
}

export function CampaignDeactivationRequestToJSON(json: any): CampaignDeactivationRequest {
    return CampaignDeactivationRequestToJSONTyped(json, false);
}

export function CampaignDeactivationRequestToJSONTyped(value?: CampaignDeactivationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userIds': value['userIds'],
    };
}

