/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { Campaign } from './Campaign';
import {
    CampaignFromJSON,
    CampaignFromJSONTyped,
    CampaignToJSON,
    CampaignToJSONTyped,
} from './Campaign';

/**
 * 
 * @export
 * @interface CampaignDeletedNotificationItem
 */
export interface CampaignDeletedNotificationItem {
    /**
     * The type of the event. Can be one of the following: ['campaign_state_changed', 'campaign_ruleset_changed', 'campaign_edited', 'campaign_created', 'campaign_deleted']
     * 
     */
    event: string;
    /**
     * The campaign whose state changed.
     */
    campaign: Campaign;
    /**
     * Time when the campaign was deleted.
     */
    deletedAt: Date;
}

/**
 * Check if a given object implements the CampaignDeletedNotificationItem interface.
 */
export function instanceOfCampaignDeletedNotificationItem(value: object): value is CampaignDeletedNotificationItem {
    const _v = value as Record<PropertyKey, unknown>;
    if ((!('event' in _v) && !('Event' in _v)) || (_v['event'] === undefined && _v['Event'] === undefined)) return false;
    if (!('campaign' in _v) || _v['campaign'] === undefined) return false;
    if (!('deletedAt' in _v) || _v['deletedAt'] === undefined) return false;
    return true;
}

export function CampaignDeletedNotificationItemFromJSON(json: any): CampaignDeletedNotificationItem {
    return CampaignDeletedNotificationItemFromJSONTyped(json, false);
}

export function CampaignDeletedNotificationItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignDeletedNotificationItem {
    if (json == null) {
        return json;
    }
    return {
        
        'event': json['Event'],
        'campaign': CampaignFromJSON(json['campaign']),
        'deletedAt': (json['deletedAt'] == null ? json['deletedAt'] : parseDateTime(json['deletedAt'])),
    };
}

export function CampaignDeletedNotificationItemToJSON(json: any): CampaignDeletedNotificationItem {
    return CampaignDeletedNotificationItemToJSONTyped(json, false);
}

export function CampaignDeletedNotificationItemToJSONTyped(value?: CampaignDeletedNotificationItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Event': value['event'],
        'campaign': CampaignToJSON(value['campaign']),
        'deletedAt': value['deletedAt'] == null ? undefined : serializeDateTime(value['deletedAt']),
    };
}

