/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CampaignEvaluationGroup
 */
export interface CampaignEvaluationGroup {
    /**
     * The ID of the Application that owns this entity.
     * @type {number}
     * @memberof CampaignEvaluationGroup
     */
    applicationId: number;
    /**
     * The name of the campaign evaluation group.
     * @type {string}
     * @memberof CampaignEvaluationGroup
     */
    name: string;
    /**
     * The ID of the parent group that contains the campaign evaluation group.
     * @type {number}
     * @memberof CampaignEvaluationGroup
     */
    parentId: number;
    /**
     * A description of the campaign evaluation group.
     * @type {string}
     * @memberof CampaignEvaluationGroup
     */
    description?: string;
    /**
     * The mode by which campaigns in the campaign evaluation group are evaluated.
     * @type {string}
     * @memberof CampaignEvaluationGroup
     */
    evaluationMode: CampaignEvaluationGroupEvaluationModeEnum;
    /**
     * The evaluation scope of the campaign evaluation group.
     * @type {string}
     * @memberof CampaignEvaluationGroup
     */
    evaluationScope: CampaignEvaluationGroupEvaluationScopeEnum;
    /**
     * An indicator of whether the campaign evaluation group is locked for modification.
     * @type {boolean}
     * @memberof CampaignEvaluationGroup
     */
    locked: boolean;
    /**
     * Unique ID for this entity. Not to be confused with the Integration ID, which is set by your integration layer and used in most endpoints.
     * @type {number}
     * @memberof CampaignEvaluationGroup
     */
    id: number;
}


/**
 * @export
 */
export const CampaignEvaluationGroupEvaluationModeEnum = {
    Stackable: 'stackable',
    ListOrder: 'listOrder',
    LowestDiscount: 'lowestDiscount',
    HighestDiscount: 'highestDiscount'
} as const;
export type CampaignEvaluationGroupEvaluationModeEnum = typeof CampaignEvaluationGroupEvaluationModeEnum[keyof typeof CampaignEvaluationGroupEvaluationModeEnum];

/**
 * @export
 */
export const CampaignEvaluationGroupEvaluationScopeEnum = {
    CartItem: 'cartItem',
    Session: 'session'
} as const;
export type CampaignEvaluationGroupEvaluationScopeEnum = typeof CampaignEvaluationGroupEvaluationScopeEnum[keyof typeof CampaignEvaluationGroupEvaluationScopeEnum];


/**
 * Check if a given object implements the CampaignEvaluationGroup interface.
 */
export function instanceOfCampaignEvaluationGroup(value: object): value is CampaignEvaluationGroup {
    if (!('applicationId' in value) || value['applicationId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('parentId' in value) || value['parentId'] === undefined) return false;
    if (!('evaluationMode' in value) || value['evaluationMode'] === undefined) return false;
    if (!('evaluationScope' in value) || value['evaluationScope'] === undefined) return false;
    if (!('locked' in value) || value['locked'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CampaignEvaluationGroupFromJSON(json: any): CampaignEvaluationGroup {
    return CampaignEvaluationGroupFromJSONTyped(json, false);
}

export function CampaignEvaluationGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignEvaluationGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'applicationId': json['applicationId'],
        'name': json['name'],
        'parentId': json['parentId'],
        'description': json['description'] == null ? undefined : json['description'],
        'evaluationMode': json['evaluationMode'],
        'evaluationScope': json['evaluationScope'],
        'locked': json['locked'],
        'id': json['id'],
    };
}

export function CampaignEvaluationGroupToJSON(json: any): CampaignEvaluationGroup {
    return CampaignEvaluationGroupToJSONTyped(json, false);
}

export function CampaignEvaluationGroupToJSONTyped(value?: CampaignEvaluationGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'applicationId': value['applicationId'],
        'name': value['name'],
        'parentId': value['parentId'],
        'description': value['description'],
        'evaluationMode': value['evaluationMode'],
        'evaluationScope': value['evaluationScope'],
        'locked': value['locked'],
        'id': value['id'],
    };
}

