/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { CampaignEligibilityDetails } from './CampaignEligibilityDetails';
import {
    CampaignEligibilityDetailsFromJSON,
    CampaignEligibilityDetailsFromJSONTyped,
    CampaignEligibilityDetailsToJSON,
    CampaignEligibilityDetailsToJSONTyped,
} from './CampaignEligibilityDetails';
import type { CampaignEligibilityExperiment } from './CampaignEligibilityExperiment';
import {
    CampaignEligibilityExperimentFromJSON,
    CampaignEligibilityExperimentFromJSONTyped,
    CampaignEligibilityExperimentToJSON,
    CampaignEligibilityExperimentToJSONTyped,
} from './CampaignEligibilityExperiment';
import type { RuleMetadataEligibility } from './RuleMetadataEligibility';
import {
    RuleMetadataEligibilityFromJSON,
    RuleMetadataEligibilityFromJSONTyped,
    RuleMetadataEligibilityToJSON,
    RuleMetadataEligibilityToJSONTyped,
} from './RuleMetadataEligibility';

/**
 * 
 * @export
 * @interface CampaignEligibility
 */
export interface CampaignEligibility {
    /**
     * The ID of the Application that owns this entity.
     */
    applicationId: number;
    /**
     * Unique ID of Campaign.
     */
    id: number;
    /**
     * The name of the campaign.
     */
    name: string;
    /**
     * A detailed description of the campaign.
     */
    description?: string;
    /**
     * Timestamp when the campaign will become active.
     */
    startTime?: Date;
    /**
     * Timestamp when the campaign will become inactive.
     */
    endTime?: Date;
    /**
     * Arbitrary properties associated with this campaign.
     */
    attributes?: object;
    /**
     * The state of the campaign.
     * 
     */
    state: CampaignEligibilityStateEnum;
    /**
     * A list of tags for the campaign.
     */
    tags: Array<string>;
    /**
     * The features enabled in this campaign.
     */
    features: Array<CampaignEligibilityFeaturesEnum>;
    /**
     * The customer's eligibility for each campaign in the current customer session.
     */
    eligibility: Array<CampaignEligibilityDetails>;
    /**
     * A list of rules containing customer-facing details of the rewards defined in the campaign.
     */
    rules: Array<RuleMetadataEligibility>;
    /**
     * 
     */
    experiment?: CampaignEligibilityExperiment;
}


/**
 * @export
 */
export const CampaignEligibilityStateEnum = {
    Enabled: 'enabled',
} as const;
export type CampaignEligibilityStateEnum = typeof CampaignEligibilityStateEnum[keyof typeof CampaignEligibilityStateEnum];

/**
 * @export
 */
export const CampaignEligibilityFeaturesEnum = {
    Coupons: 'coupons',
    Referrals: 'referrals',
    Loyalty: 'loyalty',
    Giveaways: 'giveaways',
    Strikethrough: 'strikethrough',
    Achievements: 'achievements',
    AdvancedEvents: 'advancedEvents',
} as const;
export type CampaignEligibilityFeaturesEnum = typeof CampaignEligibilityFeaturesEnum[keyof typeof CampaignEligibilityFeaturesEnum];


/**
 * Check if a given object implements the CampaignEligibility interface.
 */
export function instanceOfCampaignEligibility(value: object): value is CampaignEligibility {
    const _v = value as Record<PropertyKey, unknown>;
    if (!('applicationId' in _v) || _v['applicationId'] === undefined) return false;
    if (!('id' in _v) || _v['id'] === undefined) return false;
    if (!('name' in _v) || _v['name'] === undefined) return false;
    if (!('state' in _v) || _v['state'] === undefined) return false;
    if (_v['state'] !== 'enabled') return false;
    
    if (!('tags' in _v) || _v['tags'] === undefined) return false;
    if (!('features' in _v) || _v['features'] === undefined) return false;
    if (!('eligibility' in _v) || _v['eligibility'] === undefined) return false;
    if (!('rules' in _v) || _v['rules'] === undefined) return false;
    return true;
}

export function CampaignEligibilityFromJSON(json: any): CampaignEligibility {
    return CampaignEligibilityFromJSONTyped(json, false);
}

export function CampaignEligibilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignEligibility {
    if (json == null) {
        return json;
    }
    return {
        
        'applicationId': json['applicationId'],
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'startTime': json['startTime'] == null ? undefined : (parseDateTime(json['startTime'])),
        'endTime': json['endTime'] == null ? undefined : (parseDateTime(json['endTime'])),
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'state': json['state'],
        'tags': json['tags'],
        'features': json['features'],
        'eligibility': (json['eligibility'] == null ? undefined as any : (json['eligibility'] as Array<any>).map(CampaignEligibilityDetailsFromJSON)),
        'rules': (json['rules'] == null ? undefined as any : (json['rules'] as Array<any>).map(RuleMetadataEligibilityFromJSON)),
        'experiment': json['experiment'] == null ? undefined : CampaignEligibilityExperimentFromJSON(json['experiment']),
    };
}

export function CampaignEligibilityToJSON(json: any): CampaignEligibility {
    return CampaignEligibilityToJSONTyped(json, false);
}

export function CampaignEligibilityToJSONTyped(value?: CampaignEligibility | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'applicationId': value['applicationId'],
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'startTime': value['startTime'] == null ? value['startTime'] : serializeDateTime(value['startTime']),
        'endTime': value['endTime'] == null ? value['endTime'] : serializeDateTime(value['endTime']),
        'attributes': value['attributes'],
        'state': value['state'],
        'tags': value['tags'],
        'features': value['features'],
        'eligibility': (value['eligibility'] == null ? undefined : (value['eligibility'] as Array<any>).map(CampaignEligibilityDetailsToJSON)),
        'rules': (value['rules'] == null ? undefined : (value['rules'] as Array<any>).map(RuleMetadataEligibilityToJSON)),
        'experiment': CampaignEligibilityExperimentToJSON(value['experiment']),
    };
}

