/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CampaignCollectionEditedNotificationItem } from './CampaignCollectionEditedNotificationItem';
import {
    CampaignCollectionEditedNotificationItemFromJSON,
    CampaignCollectionEditedNotificationItemFromJSONTyped,
    CampaignCollectionEditedNotificationItemToJSON,
    CampaignCollectionEditedNotificationItemToJSONTyped,
} from './CampaignCollectionEditedNotificationItem';

/**
 * 
 * @export
 * @interface CampaignCollectionEditedNotification
 */
export interface CampaignCollectionEditedNotification {
    /**
     * The type of the notification
     * @type {string}
     * @memberof CampaignCollectionEditedNotification
     */
    notificationType: CampaignCollectionEditedNotificationNotificationTypeEnum;
    /**
     * The total size of the result set.
     * @type {number}
     * @memberof CampaignCollectionEditedNotification
     */
    totalResultSize: number;
    /**
     * A list of campaign notification data.
     * @type {Array<CampaignCollectionEditedNotificationItem>}
     * @memberof CampaignCollectionEditedNotification
     */
    data?: Array<CampaignCollectionEditedNotificationItem>;
}


/**
 * @export
 */
export const CampaignCollectionEditedNotificationNotificationTypeEnum = {
    CampaignNotification: 'CampaignNotification'
} as const;
export type CampaignCollectionEditedNotificationNotificationTypeEnum = typeof CampaignCollectionEditedNotificationNotificationTypeEnum[keyof typeof CampaignCollectionEditedNotificationNotificationTypeEnum];


/**
 * Check if a given object implements the CampaignCollectionEditedNotification interface.
 */
export function instanceOfCampaignCollectionEditedNotification(value: object): value is CampaignCollectionEditedNotification {
    if (!('notificationType' in value) || value['notificationType'] === undefined) return false;
    if (!('totalResultSize' in value) || value['totalResultSize'] === undefined) return false;
    return true;
}

export function CampaignCollectionEditedNotificationFromJSON(json: any): CampaignCollectionEditedNotification {
    return CampaignCollectionEditedNotificationFromJSONTyped(json, false);
}

export function CampaignCollectionEditedNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignCollectionEditedNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'notificationType': json['NotificationType'],
        'totalResultSize': json['TotalResultSize'],
        'data': json['Data'] == null ? undefined : ((json['Data'] as Array<any>).map(CampaignCollectionEditedNotificationItemFromJSON)),
    };
}

export function CampaignCollectionEditedNotificationToJSON(json: any): CampaignCollectionEditedNotification {
    return CampaignCollectionEditedNotificationToJSONTyped(json, false);
}

export function CampaignCollectionEditedNotificationToJSONTyped(value?: CampaignCollectionEditedNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'NotificationType': value['notificationType'],
        'TotalResultSize': value['totalResultSize'],
        'Data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CampaignCollectionEditedNotificationItemToJSON)),
    };
}

