/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CampaignSetNode } from './CampaignSetNode';
import {
    CampaignSetNodeFromJSON,
    CampaignSetNodeFromJSONTyped,
    CampaignSetNodeToJSON,
    CampaignSetNodeToJSONTyped,
} from './CampaignSetNode';

/**
 * 
 * @export
 * @interface CampaignSetBranchNode
 */
export interface CampaignSetBranchNode {
    /**
     * Indicates the node type.
     * @type {string}
     * @memberof CampaignSetBranchNode
     */
    type: CampaignSetBranchNodeTypeEnum;
    /**
     * Name of the set.
     * @type {string}
     * @memberof CampaignSetBranchNode
     */
    name: string;
    /**
     * An indicator of how the set operates on its elements.
     * @type {string}
     * @memberof CampaignSetBranchNode
     */
    operator: CampaignSetBranchNodeOperatorEnum;
    /**
     * Child elements of this set.
     * @type {Array<CampaignSetNode>}
     * @memberof CampaignSetBranchNode
     */
    elements: Array<CampaignSetNode>;
    /**
     * The ID of the campaign set.
     * @type {number}
     * @memberof CampaignSetBranchNode
     */
    groupId: number;
    /**
     * An indicator of whether the campaign set is locked for modification.
     * @type {boolean}
     * @memberof CampaignSetBranchNode
     */
    locked: boolean;
    /**
     * A description of the campaign set.
     * @type {string}
     * @memberof CampaignSetBranchNode
     */
    description?: string;
    /**
     * The mode by which campaigns in the campaign evaluation group are evaluated.
     * @type {string}
     * @memberof CampaignSetBranchNode
     */
    evaluationMode: CampaignSetBranchNodeEvaluationModeEnum;
    /**
     * The evaluation scope of the campaign evaluation group.
     * @type {string}
     * @memberof CampaignSetBranchNode
     */
    evaluationScope: CampaignSetBranchNodeEvaluationScopeEnum;
}


/**
 * @export
 */
export const CampaignSetBranchNodeTypeEnum = {
    Set: 'SET'
} as const;
export type CampaignSetBranchNodeTypeEnum = typeof CampaignSetBranchNodeTypeEnum[keyof typeof CampaignSetBranchNodeTypeEnum];

/**
 * @export
 */
export const CampaignSetBranchNodeOperatorEnum = {
    All: 'ALL',
    First: 'FIRST'
} as const;
export type CampaignSetBranchNodeOperatorEnum = typeof CampaignSetBranchNodeOperatorEnum[keyof typeof CampaignSetBranchNodeOperatorEnum];

/**
 * @export
 */
export const CampaignSetBranchNodeEvaluationModeEnum = {
    Stackable: 'stackable',
    ListOrder: 'listOrder',
    LowestDiscount: 'lowestDiscount',
    HighestDiscount: 'highestDiscount'
} as const;
export type CampaignSetBranchNodeEvaluationModeEnum = typeof CampaignSetBranchNodeEvaluationModeEnum[keyof typeof CampaignSetBranchNodeEvaluationModeEnum];

/**
 * @export
 */
export const CampaignSetBranchNodeEvaluationScopeEnum = {
    CartItem: 'cartItem',
    Session: 'session'
} as const;
export type CampaignSetBranchNodeEvaluationScopeEnum = typeof CampaignSetBranchNodeEvaluationScopeEnum[keyof typeof CampaignSetBranchNodeEvaluationScopeEnum];


/**
 * Check if a given object implements the CampaignSetBranchNode interface.
 */
export function instanceOfCampaignSetBranchNode(value: object): value is CampaignSetBranchNode {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('operator' in value) || value['operator'] === undefined) return false;
    if (!('elements' in value) || value['elements'] === undefined) return false;
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    if (!('locked' in value) || value['locked'] === undefined) return false;
    if (!('evaluationMode' in value) || value['evaluationMode'] === undefined) return false;
    if (!('evaluationScope' in value) || value['evaluationScope'] === undefined) return false;
    return true;
}

export function CampaignSetBranchNodeFromJSON(json: any): CampaignSetBranchNode {
    return CampaignSetBranchNodeFromJSONTyped(json, false);
}

export function CampaignSetBranchNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignSetBranchNode {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'name': json['name'],
        'operator': json['operator'],
        'elements': ((json['elements'] as Array<any>).map(CampaignSetNodeFromJSON)),
        'groupId': json['groupId'],
        'locked': json['locked'],
        'description': json['description'] == null ? undefined : json['description'],
        'evaluationMode': json['evaluationMode'],
        'evaluationScope': json['evaluationScope'],
    };
}

export function CampaignSetBranchNodeToJSON(json: any): CampaignSetBranchNode {
    return CampaignSetBranchNodeToJSONTyped(json, false);
}

export function CampaignSetBranchNodeToJSONTyped(value?: CampaignSetBranchNode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'name': value['name'],
        'operator': value['operator'],
        'elements': ((value['elements'] as Array<any>).map(CampaignSetNodeToJSON)),
        'groupId': value['groupId'],
        'locked': value['locked'],
        'description': value['description'],
        'evaluationMode': value['evaluationMode'],
        'evaluationScope': value['evaluationScope'],
    };
}

