/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Loyalty card points with start and expiry dates.
 * @export
 * @interface CardLedgerPointsEntryIntegrationAPI
 */
export interface CardLedgerPointsEntryIntegrationAPI {
    /**
     * ID of the transaction that adds loyalty points.
     * @type {number}
     * @memberof CardLedgerPointsEntryIntegrationAPI
     */
    id: number;
    /**
     * Unique identifier of the transaction in the UUID format.
     * @type {string}
     * @memberof CardLedgerPointsEntryIntegrationAPI
     */
    transactionUUID: string;
    /**
     * Date and time the loyalty card points were added.
     * @type {Date}
     * @memberof CardLedgerPointsEntryIntegrationAPI
     */
    created: Date;
    /**
     * ID of the loyalty program.
     * @type {number}
     * @memberof CardLedgerPointsEntryIntegrationAPI
     */
    programId: number;
    /**
     * Integration ID of the customer profile linked to the card.
     * @type {string}
     * @memberof CardLedgerPointsEntryIntegrationAPI
     */
    customerProfileID?: string;
    /**
     * ID of the customer session where points were added.
     * @type {string}
     * @memberof CardLedgerPointsEntryIntegrationAPI
     */
    customerSessionId?: string;
    /**
     * Name or reason of the transaction that adds loyalty points.
     * @type {string}
     * @memberof CardLedgerPointsEntryIntegrationAPI
     */
    name: string;
    /**
     * When points become active. Possible values:
     *   - `immediate`: Points are active immediately.
     *   - `timestamp value`: Points become active at a given date and time.
     * 
     * @type {string}
     * @memberof CardLedgerPointsEntryIntegrationAPI
     */
    startDate: string;
    /**
     * Date when points expire. Possible values are:
     *   - `unlimited`: Points have no expiration date.
     *   - `timestamp value`: Points expire on the given date and time.
     * 
     * @type {string}
     * @memberof CardLedgerPointsEntryIntegrationAPI
     */
    expiryDate: string;
    /**
     * ID of the subledger.
     * @type {string}
     * @memberof CardLedgerPointsEntryIntegrationAPI
     */
    subledgerId: string;
    /**
     * Amount of loyalty points added in the transaction.
     * @type {number}
     * @memberof CardLedgerPointsEntryIntegrationAPI
     */
    amount: number;
    /**
     * The duration for which the points remain active, relative to the  activation date.
     * 
     * **Note**: This only applies to points for which `awaitsActivation` is `true` and `expiryDate` is not set.
     * 
     * @type {string}
     * @memberof CardLedgerPointsEntryIntegrationAPI
     */
    validityDuration?: string;
}

/**
 * Check if a given object implements the CardLedgerPointsEntryIntegrationAPI interface.
 */
export function instanceOfCardLedgerPointsEntryIntegrationAPI(value: object): value is CardLedgerPointsEntryIntegrationAPI {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('transactionUUID' in value) || value['transactionUUID'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('programId' in value) || value['programId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('expiryDate' in value) || value['expiryDate'] === undefined) return false;
    if (!('subledgerId' in value) || value['subledgerId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function CardLedgerPointsEntryIntegrationAPIFromJSON(json: any): CardLedgerPointsEntryIntegrationAPI {
    return CardLedgerPointsEntryIntegrationAPIFromJSONTyped(json, false);
}

export function CardLedgerPointsEntryIntegrationAPIFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardLedgerPointsEntryIntegrationAPI {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'transactionUUID': json['transactionUUID'],
        'created': (new Date(json['created'])),
        'programId': json['programId'],
        'customerProfileID': json['customerProfileID'] == null ? undefined : json['customerProfileID'],
        'customerSessionId': json['customerSessionId'] == null ? undefined : json['customerSessionId'],
        'name': json['name'],
        'startDate': json['startDate'],
        'expiryDate': json['expiryDate'],
        'subledgerId': json['subledgerId'],
        'amount': json['amount'],
        'validityDuration': json['validityDuration'] == null ? undefined : json['validityDuration'],
    };
}

export function CardLedgerPointsEntryIntegrationAPIToJSON(json: any): CardLedgerPointsEntryIntegrationAPI {
    return CardLedgerPointsEntryIntegrationAPIToJSONTyped(json, false);
}

export function CardLedgerPointsEntryIntegrationAPIToJSONTyped(value?: CardLedgerPointsEntryIntegrationAPI | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'transactionUUID': value['transactionUUID'],
        'created': value['created'].toISOString(),
        'programId': value['programId'],
        'customerProfileID': value['customerProfileID'],
        'customerSessionId': value['customerSessionId'],
        'name': value['name'],
        'startDate': value['startDate'],
        'expiryDate': value['expiryDate'],
        'subledgerId': value['subledgerId'],
        'amount': value['amount'],
        'validityDuration': value['validityDuration'],
    };
}

