/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddedDeductedPointsBalancesAction } from './AddedDeductedPointsBalancesAction';
import {
    AddedDeductedPointsBalancesActionFromJSON,
    AddedDeductedPointsBalancesActionFromJSONTyped,
    AddedDeductedPointsBalancesActionToJSON,
    AddedDeductedPointsBalancesActionToJSONTyped,
} from './AddedDeductedPointsBalancesAction';

/**
 * 
 * @export
 * @interface CardAddedDeductedPointsBalancesNotification
 */
export interface CardAddedDeductedPointsBalancesNotification {
    /**
     * Loyalty card identification number.
     */
    cardIdentifier: string;
    /**
     * The name of the employee who added or deducted points.
     */
    employeeName: string;
    /**
     * The ID of the loyalty program.
     */
    loyaltyProgramID: number;
    /**
     * The type of notification.
     */
    notificationType: CardAddedDeductedPointsBalancesNotificationNotificationTypeEnum;
    /**
     * The integration ID of the customer profile to whom points were added or deducted.
     */
    profileIntegrationIDs: Array<string>;
    /**
     * The integration ID of the session through which the points were earned or lost.
     */
    sessionIntegrationID: string;
    /**
     * The ID of the subledger within the loyalty program where these points were added or deducted.
     */
    subledgerID: string;
    /**
     * The notification source, that is, it indicates whether the points were added or deducted via one of the following routes:
     * - [The Campaign Manager](/docs/product/getting-started)
     * - [Management API](/management-api#tag/Loyalty)
     * - [Rule Engine](/docs/product/applications/evaluation-order-for-rules-and-filters)
     * 
     */
    typeOfChange: CardAddedDeductedPointsBalancesNotificationTypeOfChangeEnum;
    /**
     * The ID of the employee who added or deducted points.
     */
    userID: number;
    /**
     * The max amount of user profiles with whom a card can be shared. This can be set to `0` for no limit.
     */
    usersPerCardLimit: number;
    /**
     * The list of actions that have been triggered in the loyalty program.
     */
    actions: Array<AddedDeductedPointsBalancesAction>;
    /**
     * The current points balance.
     */
    currentPoints: number;
}


/**
 * @export
 */
export const CardAddedDeductedPointsBalancesNotificationNotificationTypeEnum = {
    LoyaltyCardAddedDeductedPointsBalances: 'LoyaltyCardAddedDeductedPointsBalances',
} as const;
export type CardAddedDeductedPointsBalancesNotificationNotificationTypeEnum = typeof CardAddedDeductedPointsBalancesNotificationNotificationTypeEnum[keyof typeof CardAddedDeductedPointsBalancesNotificationNotificationTypeEnum];

/**
 * @export
 */
export const CardAddedDeductedPointsBalancesNotificationTypeOfChangeEnum = {
    CampaignManager: 'campaign_manager',
    RuleEngine: 'rule_engine',
    ManagementApi: 'management_api',
} as const;
export type CardAddedDeductedPointsBalancesNotificationTypeOfChangeEnum = typeof CardAddedDeductedPointsBalancesNotificationTypeOfChangeEnum[keyof typeof CardAddedDeductedPointsBalancesNotificationTypeOfChangeEnum];


/**
 * Check if a given object implements the CardAddedDeductedPointsBalancesNotification interface.
 */
export function instanceOfCardAddedDeductedPointsBalancesNotification(value: object): value is CardAddedDeductedPointsBalancesNotification {
    const _v = value as Record<PropertyKey, unknown>;
    if ((!('cardIdentifier' in _v) && !('CardIdentifier' in _v)) || (_v['cardIdentifier'] === undefined && _v['CardIdentifier'] === undefined)) return false;
    if ((!('employeeName' in _v) && !('EmployeeName' in _v)) || (_v['employeeName'] === undefined && _v['EmployeeName'] === undefined)) return false;
    if ((!('loyaltyProgramID' in _v) && !('LoyaltyProgramID' in _v)) || (_v['loyaltyProgramID'] === undefined && _v['LoyaltyProgramID'] === undefined)) return false;
    if ((!('notificationType' in _v) && !('NotificationType' in _v)) || (_v['notificationType'] === undefined && _v['NotificationType'] === undefined)) return false;
    if (_v['notificationType'] !== 'LoyaltyCardAddedDeductedPointsBalances' && _v['NotificationType'] !== 'LoyaltyCardAddedDeductedPointsBalances') return false;
    
    if ((!('profileIntegrationIDs' in _v) && !('ProfileIntegrationIDs' in _v)) || (_v['profileIntegrationIDs'] === undefined && _v['ProfileIntegrationIDs'] === undefined)) return false;
    if ((!('sessionIntegrationID' in _v) && !('SessionIntegrationID' in _v)) || (_v['sessionIntegrationID'] === undefined && _v['SessionIntegrationID'] === undefined)) return false;
    if ((!('subledgerID' in _v) && !('SubledgerID' in _v)) || (_v['subledgerID'] === undefined && _v['SubledgerID'] === undefined)) return false;
    if ((!('typeOfChange' in _v) && !('TypeOfChange' in _v)) || (_v['typeOfChange'] === undefined && _v['TypeOfChange'] === undefined)) return false;
    if ((!('userID' in _v) && !('UserID' in _v)) || (_v['userID'] === undefined && _v['UserID'] === undefined)) return false;
    if ((!('usersPerCardLimit' in _v) && !('UsersPerCardLimit' in _v)) || (_v['usersPerCardLimit'] === undefined && _v['UsersPerCardLimit'] === undefined)) return false;
    if ((!('actions' in _v) && !('Actions' in _v)) || (_v['actions'] === undefined && _v['Actions'] === undefined)) return false;
    if ((!('currentPoints' in _v) && !('CurrentPoints' in _v)) || (_v['currentPoints'] === undefined && _v['CurrentPoints'] === undefined)) return false;
    return true;
}

export function CardAddedDeductedPointsBalancesNotificationFromJSON(json: any): CardAddedDeductedPointsBalancesNotification {
    return CardAddedDeductedPointsBalancesNotificationFromJSONTyped(json, false);
}

export function CardAddedDeductedPointsBalancesNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardAddedDeductedPointsBalancesNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'cardIdentifier': json['CardIdentifier'],
        'employeeName': json['EmployeeName'],
        'loyaltyProgramID': json['LoyaltyProgramID'],
        'notificationType': json['NotificationType'],
        'profileIntegrationIDs': json['ProfileIntegrationIDs'],
        'sessionIntegrationID': json['SessionIntegrationID'],
        'subledgerID': json['SubledgerID'],
        'typeOfChange': json['TypeOfChange'],
        'userID': json['UserID'],
        'usersPerCardLimit': json['UsersPerCardLimit'],
        'actions': (json['Actions'] == null ? undefined as any : (json['Actions'] as Array<any>).map(AddedDeductedPointsBalancesActionFromJSON)),
        'currentPoints': json['CurrentPoints'],
    };
}

export function CardAddedDeductedPointsBalancesNotificationToJSON(json: any): CardAddedDeductedPointsBalancesNotification {
    return CardAddedDeductedPointsBalancesNotificationToJSONTyped(json, false);
}

export function CardAddedDeductedPointsBalancesNotificationToJSONTyped(value?: CardAddedDeductedPointsBalancesNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'CardIdentifier': value['cardIdentifier'],
        'EmployeeName': value['employeeName'],
        'LoyaltyProgramID': value['loyaltyProgramID'],
        'NotificationType': value['notificationType'],
        'ProfileIntegrationIDs': value['profileIntegrationIDs'],
        'SessionIntegrationID': value['sessionIntegrationID'],
        'SubledgerID': value['subledgerID'],
        'TypeOfChange': value['typeOfChange'],
        'UserID': value['userID'],
        'UsersPerCardLimit': value['usersPerCardLimit'],
        'Actions': (value['actions'] == null ? undefined : (value['actions'] as Array<any>).map(AddedDeductedPointsBalancesActionToJSON)),
        'CurrentPoints': value['currentPoints'],
    };
}

