/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardExpiringPointsNotificationTrigger
 */
export interface CardExpiringPointsNotificationTrigger {
    /**
     * The amount of period.
     * @type {number}
     * @memberof CardExpiringPointsNotificationTrigger
     */
    amount: number;
    /**
     * Notification period indicated by a letter; "w" means week, "d" means day.
     * @type {string}
     * @memberof CardExpiringPointsNotificationTrigger
     */
    period: CardExpiringPointsNotificationTriggerPeriodEnum;
}


/**
 * @export
 */
export const CardExpiringPointsNotificationTriggerPeriodEnum = {
    W: 'w',
    D: 'd'
} as const;
export type CardExpiringPointsNotificationTriggerPeriodEnum = typeof CardExpiringPointsNotificationTriggerPeriodEnum[keyof typeof CardExpiringPointsNotificationTriggerPeriodEnum];


/**
 * Check if a given object implements the CardExpiringPointsNotificationTrigger interface.
 */
export function instanceOfCardExpiringPointsNotificationTrigger(value: object): value is CardExpiringPointsNotificationTrigger {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('period' in value) || value['period'] === undefined) return false;
    return true;
}

export function CardExpiringPointsNotificationTriggerFromJSON(json: any): CardExpiringPointsNotificationTrigger {
    return CardExpiringPointsNotificationTriggerFromJSONTyped(json, false);
}

export function CardExpiringPointsNotificationTriggerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardExpiringPointsNotificationTrigger {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'period': json['period'],
    };
}

export function CardExpiringPointsNotificationTriggerToJSON(json: any): CardExpiringPointsNotificationTrigger {
    return CardExpiringPointsNotificationTriggerToJSONTyped(json, false);
}

export function CardExpiringPointsNotificationTriggerToJSONTyped(value?: CardExpiringPointsNotificationTrigger | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'period': value['period'],
    };
}

