/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardAddedDeductedPointsNotificationPolicy
 */
export interface CardAddedDeductedPointsNotificationPolicy {
    /**
     * Notification name.
     * @type {string}
     * @memberof CardAddedDeductedPointsNotificationPolicy
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CardAddedDeductedPointsNotificationPolicy
     */
    scopes: Array<CardAddedDeductedPointsNotificationPolicyScopesEnum>;
}


/**
 * @export
 */
export const CardAddedDeductedPointsNotificationPolicyScopesEnum = {
    All: 'all',
    CampaignManager: 'campaign_manager',
    ManagementApi: 'management_api',
    RuleEngine: 'rule_engine'
} as const;
export type CardAddedDeductedPointsNotificationPolicyScopesEnum = typeof CardAddedDeductedPointsNotificationPolicyScopesEnum[keyof typeof CardAddedDeductedPointsNotificationPolicyScopesEnum];


/**
 * Check if a given object implements the CardAddedDeductedPointsNotificationPolicy interface.
 */
export function instanceOfCardAddedDeductedPointsNotificationPolicy(value: object): value is CardAddedDeductedPointsNotificationPolicy {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('scopes' in value) || value['scopes'] === undefined) return false;
    return true;
}

export function CardAddedDeductedPointsNotificationPolicyFromJSON(json: any): CardAddedDeductedPointsNotificationPolicy {
    return CardAddedDeductedPointsNotificationPolicyFromJSONTyped(json, false);
}

export function CardAddedDeductedPointsNotificationPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardAddedDeductedPointsNotificationPolicy {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'scopes': json['scopes'],
    };
}

export function CardAddedDeductedPointsNotificationPolicyToJSON(json: any): CardAddedDeductedPointsNotificationPolicy {
    return CardAddedDeductedPointsNotificationPolicyToJSONTyped(json, false);
}

export function CardAddedDeductedPointsNotificationPolicyToJSONTyped(value?: CardAddedDeductedPointsNotificationPolicy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'scopes': value['scopes'],
    };
}

