/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A cart item filter template stored in a library entry. Cart item filters in library entries only contain name (no description, as description is at the library entry level).
 * @export
 * @interface CartItemFilterTemplate
 */
export interface CartItemFilterTemplate {
    /**
     * The name of the Application cart item filter.
     * @type {string}
     * @memberof CartItemFilterTemplate
     */
    name: string;
    /**
     * The Talang expression for the cart item filter.
     * @type {Array<any>}
     * @memberof CartItemFilterTemplate
     */
    expression: Array<any>;
}

/**
 * Check if a given object implements the CartItemFilterTemplate interface.
 */
export function instanceOfCartItemFilterTemplate(value: object): value is CartItemFilterTemplate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('expression' in value) || value['expression'] === undefined) return false;
    return true;
}

export function CartItemFilterTemplateFromJSON(json: any): CartItemFilterTemplate {
    return CartItemFilterTemplateFromJSONTyped(json, false);
}

export function CartItemFilterTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartItemFilterTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'expression': json['expression'],
    };
}

export function CartItemFilterTemplateToJSON(json: any): CartItemFilterTemplate {
    return CartItemFilterTemplateToJSONTyped(json, false);
}

export function CartItemFilterTemplateToJSONTyped(value?: CartItemFilterTemplate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'expression': value['expression'],
    };
}

