/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdditionalCost } from './AdditionalCost';
import {
    AdditionalCostFromJSON,
    AdditionalCostFromJSONTyped,
    AdditionalCostToJSON,
    AdditionalCostToJSONTyped,
} from './AdditionalCost';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';
import type { PriceDetail } from './PriceDetail';
import {
    PriceDetailFromJSON,
    PriceDetailFromJSONTyped,
    PriceDetailToJSON,
    PriceDetailToJSONTyped,
} from './PriceDetail';

/**
 * 
 * @export
 * @interface CartItem
 */
export interface CartItem {
    /**
     * Name of item.
     * @type {string}
     * @memberof CartItem
     */
    name?: string;
    /**
     * Stock keeping unit of item.
     * @type {string}
     * @memberof CartItem
     */
    sku: string;
    /**
     * Number of units of this item. Due to [cart item flattening](https://docs.talon.one/docs/product/rules/understanding-cart-item-flattening),
     * if you provide a quantity greater than 1, the item will be split in as many items as the provided quantity.
     * This will impact the number of **per-item** effects triggered from your campaigns.
     * 
     * @type {number}
     * @memberof CartItem
     */
    quantity: number;
    /**
     * Number of returned items, calculated internally based on returns of this item.
     * @type {number}
     * @memberof CartItem
     */
    returnedQuantity?: number;
    /**
     * Remaining quantity of the item, calculated internally based on returns of this item.
     * @type {number}
     * @memberof CartItem
     */
    remainingQuantity?: number;
    /**
     * Price of the item in the currency defined by your Application. This field is required if this item is not part of a [catalog](https://docs.talon.one/docs/product/account/dev-tools/managing-cart-item-catalogs). If it is part of a catalog, setting a price here overrides the price from the catalog.
     * 
     * @type {number}
     * @memberof CartItem
     */
    price?: number;
    /**
     * Type, group or model of the item.
     * @type {string}
     * @memberof CartItem
     */
    category?: string;
    /**
     * 
     * @type {Product}
     * @memberof CartItem
     */
    product?: Product;
    /**
     * Weight of item in grams.
     * @type {number}
     * @memberof CartItem
     */
    weight?: number;
    /**
     * Height of item in mm.
     * @type {number}
     * @memberof CartItem
     */
    height?: number;
    /**
     * Width of item in mm.
     * @type {number}
     * @memberof CartItem
     */
    width?: number;
    /**
     * Length of item in mm.
     * @type {number}
     * @memberof CartItem
     */
    length?: number;
    /**
     * Position of the Cart Item in the Cart (calculated internally).
     * @type {number}
     * @memberof CartItem
     */
    position?: number;
    /**
     * Use this property to set a value for the attributes of your choice. [Attributes](https://docs.talon.one/docs/dev/concepts/attributes) represent any information to attach to this cart item.
     * 
     * Custom _cart item_ attributes must be created in the Campaign Manager before you set them with this property.
     * 
     * **Note:** Any previously defined attributes that you do not include in the array will be removed.
     * 
     * @type {object}
     * @memberof CartItem
     */
    attributes?: object;
    /**
     * Use this property to set a value for the additional costs of this item, such as a shipping cost. They must be created in the Campaign Manager
     * before you set them with this property. See [Managing additional costs](https://docs.talon.one/docs/product/account/dev-tools/managing-additional-costs).
     * 
     * @type {{ [key: string]: AdditionalCost; }}
     * @memberof CartItem
     */
    additionalCosts?: { [key: string]: AdditionalCost; };
    /**
     * The catalog item ID.
     * @type {number}
     * @memberof CartItem
     */
    catalogItemID?: number;
    /**
     * The selected price type for this cart item (e.g. the price for members only).
     * @type {string}
     * @memberof CartItem
     */
    selectedPriceType?: string;
    /**
     * The reference ID of the selected price adjustment for this cart item. Only returned if the selected price resulted from a price adjustment.
     * @type {string}
     * @memberof CartItem
     */
    adjustmentReferenceId?: string;
    /**
     * The date and time from which the price adjustment is effective. Only returned if the selected price resulted from a price adjustment that contains this field.
     * @type {Date}
     * @memberof CartItem
     */
    adjustmentEffectiveFrom?: Date;
    /**
     * The date and time until which the price adjustment is effective. Only returned if the selected price resulted from a price adjustment that contains this field.
     * @type {Date}
     * @memberof CartItem
     */
    adjustmentEffectiveUntil?: Date;
    /**
     * A map of keys and values representing the price types and related price adjustment details for this cart item.
     * The keys correspond to the `priceType` names.
     * 
     * @type {{ [key: string]: PriceDetail; }}
     * @memberof CartItem
     */
    prices?: { [key: string]: PriceDetail; };
}

/**
 * Check if a given object implements the CartItem interface.
 */
export function instanceOfCartItem(value: object): value is CartItem {
    if (!('sku' in value) || value['sku'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function CartItemFromJSON(json: any): CartItem {
    return CartItemFromJSONTyped(json, false);
}

export function CartItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartItem {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'sku': json['sku'],
        'quantity': json['quantity'],
        'returnedQuantity': json['returnedQuantity'] == null ? undefined : json['returnedQuantity'],
        'remainingQuantity': json['remainingQuantity'] == null ? undefined : json['remainingQuantity'],
        'price': json['price'] == null ? undefined : json['price'],
        'category': json['category'] == null ? undefined : json['category'],
        'product': json['product'] == null ? undefined : ProductFromJSON(json['product']),
        'weight': json['weight'] == null ? undefined : json['weight'],
        'height': json['height'] == null ? undefined : json['height'],
        'width': json['width'] == null ? undefined : json['width'],
        'length': json['length'] == null ? undefined : json['length'],
        'position': json['position'] == null ? undefined : json['position'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'additionalCosts': json['additionalCosts'] == null ? undefined : (mapValues(json['additionalCosts'], AdditionalCostFromJSON)),
        'catalogItemID': json['catalogItemID'] == null ? undefined : json['catalogItemID'],
        'selectedPriceType': json['selectedPriceType'] == null ? undefined : json['selectedPriceType'],
        'adjustmentReferenceId': json['adjustmentReferenceId'] == null ? undefined : json['adjustmentReferenceId'],
        'adjustmentEffectiveFrom': json['adjustmentEffectiveFrom'] == null ? undefined : (new Date(json['adjustmentEffectiveFrom'])),
        'adjustmentEffectiveUntil': json['adjustmentEffectiveUntil'] == null ? undefined : (new Date(json['adjustmentEffectiveUntil'])),
        'prices': json['prices'] == null ? undefined : (mapValues(json['prices'], PriceDetailFromJSON)),
    };
}

export function CartItemToJSON(json: any): CartItem {
    return CartItemToJSONTyped(json, false);
}

export function CartItemToJSONTyped(value?: CartItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'sku': value['sku'],
        'quantity': value['quantity'],
        'returnedQuantity': value['returnedQuantity'],
        'remainingQuantity': value['remainingQuantity'],
        'price': value['price'],
        'category': value['category'],
        'product': ProductToJSON(value['product']),
        'weight': value['weight'],
        'height': value['height'],
        'width': value['width'],
        'length': value['length'],
        'position': value['position'],
        'attributes': value['attributes'],
        'additionalCosts': value['additionalCosts'] == null ? undefined : (mapValues(value['additionalCosts'], AdditionalCostToJSON)),
        'catalogItemID': value['catalogItemID'],
        'selectedPriceType': value['selectedPriceType'],
        'adjustmentReferenceId': value['adjustmentReferenceId'],
        'adjustmentEffectiveFrom': value['adjustmentEffectiveFrom'] == null ? value['adjustmentEffectiveFrom'] : value['adjustmentEffectiveFrom'].toISOString(),
        'adjustmentEffectiveUntil': value['adjustmentEffectiveUntil'] == null ? value['adjustmentEffectiveUntil'] : value['adjustmentEffectiveUntil'].toISOString(),
        'prices': value['prices'] == null ? undefined : (mapValues(value['prices'], PriceDetailToJSON)),
    };
}

