/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Catalog
 */
export interface Catalog {
    /**
     * The internal ID of this entity.
     * @type {number}
     * @memberof Catalog
     */
    id: number;
    /**
     * The time this entity was created.
     * @type {Date}
     * @memberof Catalog
     */
    created: Date;
    /**
     * The ID of the account that owns this entity.
     * @type {number}
     * @memberof Catalog
     */
    accountId: number;
    /**
     * The time this entity was last modified.
     * @type {Date}
     * @memberof Catalog
     */
    modified: Date;
    /**
     * The cart item catalog name.
     * @type {string}
     * @memberof Catalog
     */
    name: string;
    /**
     * A description of this cart item catalog.
     * @type {string}
     * @memberof Catalog
     */
    description: string;
    /**
     * A list of the IDs of the applications that are subscribed to this catalog.
     * @type {Array<number>}
     * @memberof Catalog
     */
    subscribedApplicationsIds?: Array<number>;
    /**
     * The current version of this catalog.
     * @type {number}
     * @memberof Catalog
     */
    version: number;
    /**
     * The ID of user who created this catalog.
     * @type {number}
     * @memberof Catalog
     */
    createdBy: number;
}

/**
 * Check if a given object implements the Catalog interface.
 */
export function instanceOfCatalog(value: object): value is Catalog {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('modified' in value) || value['modified'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    return true;
}

export function CatalogFromJSON(json: any): Catalog {
    return CatalogFromJSONTyped(json, false);
}

export function CatalogFromJSONTyped(json: any, ignoreDiscriminator: boolean): Catalog {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'created': (new Date(json['created'])),
        'accountId': json['accountId'],
        'modified': (new Date(json['modified'])),
        'name': json['name'],
        'description': json['description'],
        'subscribedApplicationsIds': json['subscribedApplicationsIds'] == null ? undefined : json['subscribedApplicationsIds'],
        'version': json['version'],
        'createdBy': json['createdBy'],
    };
}

export function CatalogToJSON(json: any): Catalog {
    return CatalogToJSONTyped(json, false);
}

export function CatalogToJSONTyped(value?: Catalog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created': value['created'].toISOString(),
        'accountId': value['accountId'],
        'modified': value['modified'].toISOString(),
        'name': value['name'],
        'description': value['description'],
        'subscribedApplicationsIds': value['subscribedApplicationsIds'],
        'version': value['version'],
        'createdBy': value['createdBy'],
    };
}

