/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PatchItemCatalogAction } from './PatchItemCatalogAction';
import {
    PatchItemCatalogActionFromJSON,
    PatchItemCatalogActionFromJSONTyped,
    PatchItemCatalogActionToJSON,
    PatchItemCatalogActionToJSONTyped,
} from './PatchItemCatalogAction';

/**
 * 
 * @export
 * @interface CatalogActionOneOf1
 */
export interface CatalogActionOneOf1 {
    /**
     * 
     * @type {any}
     * @memberof CatalogActionOneOf1
     */
    type: any | null;
    /**
     * 
     * @type {PatchItemCatalogAction}
     * @memberof CatalogActionOneOf1
     */
    payload: PatchItemCatalogAction;
}

/**
 * Check if a given object implements the CatalogActionOneOf1 interface.
 */
export function instanceOfCatalogActionOneOf1(value: object): value is CatalogActionOneOf1 {
    const _v = value as Record<PropertyKey, unknown>;
    if (!('type' in _v) || _v['type'] === undefined) return false;
    if (!('payload' in _v) || _v['payload'] === undefined) return false;
    return true;
}

export function CatalogActionOneOf1FromJSON(json: any): CatalogActionOneOf1 {
    return CatalogActionOneOf1FromJSONTyped(json, false);
}

export function CatalogActionOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogActionOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'payload': PatchItemCatalogActionFromJSON(json['payload']),
    };
}

export function CatalogActionOneOf1ToJSON(json: any): CatalogActionOneOf1 {
    return CatalogActionOneOf1ToJSONTyped(json, false);
}

export function CatalogActionOneOf1ToJSONTyped(value?: CatalogActionOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'payload': PatchItemCatalogActionToJSON(value['payload']),
    };
}

