/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import { type BetweenCheckAttributeBlock, BetweenCheckAttributeBlockFromJSONTyped, BetweenCheckAttributeBlockToJSON, BetweenCheckAttributeBlockToJSONTyped } from './BetweenCheckAttributeBlock';
import { type ScalarCheckAttributeBlock, ScalarCheckAttributeBlockFromJSONTyped, ScalarCheckAttributeBlockToJSON, ScalarCheckAttributeBlockToJSONTyped } from './ScalarCheckAttributeBlock';
import { type ListCheckAttributeBlock, ListCheckAttributeBlockFromJSONTyped, ListCheckAttributeBlockToJSON, ListCheckAttributeBlockToJSONTyped } from './ListCheckAttributeBlock';
import { type ListWithCountCheckAttributeBlock, ListWithCountCheckAttributeBlockFromJSONTyped, ListWithCountCheckAttributeBlockToJSON, ListWithCountCheckAttributeBlockToJSONTyped } from './ListWithCountCheckAttributeBlock';
import { type UnaryCheckAttributeBlock, UnaryCheckAttributeBlockFromJSONTyped, UnaryCheckAttributeBlockToJSON, UnaryCheckAttributeBlockToJSONTyped } from './UnaryCheckAttributeBlock';
/**
 * 
 * @export
 * @interface CheckAttributeBlock
 */
export interface CheckAttributeBlock {
    /**
     * Unique identifier for this block.
     * @type {string}
     * @memberof CheckAttributeBlock
     */
    id: string;
    /**
     * Identifies the block variant and determines which additional properties are present in it.
     * @type {string}
     * @memberof CheckAttributeBlock
     */
    type: string;
    /**
     * Semantic labels attached to this block.
     * @type {Array<string>}
     * @memberof CheckAttributeBlock
     */
    tags?: Array<string>;
    /**
     * The comparison operator applied to the attribute.
     * @type {CheckAttributeBlockOperatorEnum}
     * @memberof CheckAttributeBlock
     */
    operator: CheckAttributeBlockOperatorEnum;
    /**
     * The attribute path identifier (e.g. "$Session.Total").
     * @type {string}
     * @memberof CheckAttributeBlock
     */
    attribute: string;
    /**
     * 
     * @type {any}
     * @memberof CheckAttributeBlock
     */
    value?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CheckAttributeBlock
     */
    min?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CheckAttributeBlock
     */
    max?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CheckAttributeBlock
     */
    values?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CheckAttributeBlock
     */
    count?: any | null;
}


/**
 * @export
 */
export const CheckAttributeBlockOperatorEnum = {
    Equals: 'equals',
    NotEquals: 'not(equals)',
    LessThan: 'lessThan',
    LessThanOrEqual: 'lessThanOrEqual',
    GreaterThan: 'greaterThan',
    GreaterThanOrEqual: 'greaterThanOrEqual',
    Between: 'between',
    Contains: 'contains',
    NotContains: 'not(contains)',
    MatchesRegexp: 'matchesRegexp',
    StartsWith: 'startsWith',
    EndsWith: 'endsWith',
    OneOf: 'oneOf',
    NotOneOf: 'not(oneOf)',
    InCollection: 'inCollection',
    NotInCollection: 'not(inCollection)',
    Empty: 'empty',
    NotEmpty: 'not(empty)',
    Exists: 'exists',
    NotExists: 'not(exists)',
    IsTrue: 'isTrue',
    IsFalse: 'isFalse',
    ContainsAtLeast: 'containsAtLeast',
    ContainsExactly: 'containsExactly',
    ContainsOneOf: 'containsOneOf',
    ContainsNoneOf: 'containsNoneOf',
    ContainsAllOf: 'containsAllOf'
} as const;
export type CheckAttributeBlockOperatorEnum = typeof CheckAttributeBlockOperatorEnum[keyof typeof CheckAttributeBlockOperatorEnum];


/**
 * Check if a given object implements the CheckAttributeBlock interface.
 */
export function instanceOfCheckAttributeBlock(value: object): value is CheckAttributeBlock {
    const _v = value as Record<PropertyKey, unknown>;
    if (!('id' in _v) || _v['id'] === undefined) return false;
    if (!('type' in _v) || _v['type'] === undefined) return false;
    if (!('operator' in _v) || _v['operator'] === undefined) return false;
    if (!('attribute' in _v) || _v['attribute'] === undefined) return false;
    return true;
}

export function CheckAttributeBlockFromJSON(json: any): CheckAttributeBlock {
    return CheckAttributeBlockFromJSONTyped(json, false);
}

export function CheckAttributeBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckAttributeBlock {
    if (json == null) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['operator'] === 'between') {
            return BetweenCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'contains') {
            return ScalarCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'containsAllOf') {
            return ListCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'containsAtLeast') {
            return ListWithCountCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'containsExactly') {
            return ListWithCountCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'containsNoneOf') {
            return ListCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'containsOneOf') {
            return ListCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'empty') {
            return UnaryCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'endsWith') {
            return ScalarCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'equals') {
            return ScalarCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'exists') {
            return UnaryCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'greaterThan') {
            return ScalarCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'greaterThanOrEqual') {
            return ScalarCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'inCollection') {
            return ScalarCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'isFalse') {
            return UnaryCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'isTrue') {
            return UnaryCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'lessThan') {
            return ScalarCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'lessThanOrEqual') {
            return ScalarCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'matchesRegexp') {
            return ScalarCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'not(contains)') {
            return ScalarCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'not(empty)') {
            return UnaryCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'not(equals)') {
            return ScalarCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'not(exists)') {
            return UnaryCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'not(inCollection)') {
            return ScalarCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'not(oneOf)') {
            return ScalarCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'oneOf') {
            return ScalarCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['operator'] === 'startsWith') {
            return ScalarCheckAttributeBlockFromJSONTyped(json, ignoreDiscriminator);
        }

    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'operator': json['operator'],
        'attribute': json['attribute'],
        'value': json['value'] == null ? undefined : json['value'],
        'min': json['min'] == null ? undefined : json['min'],
        'max': json['max'] == null ? undefined : json['max'],
        'values': json['values'] == null ? undefined : json['values'],
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function CheckAttributeBlockToJSON(json: any): CheckAttributeBlock {
    return CheckAttributeBlockToJSONTyped(json, false);
}

export function CheckAttributeBlockToJSONTyped(value?: CheckAttributeBlock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (!ignoreDiscriminator) {
        switch (value['operator']) {
            case 'between':
                return BetweenCheckAttributeBlockToJSONTyped(value as BetweenCheckAttributeBlock, ignoreDiscriminator);
            case 'contains':
                return ScalarCheckAttributeBlockToJSONTyped(value as ScalarCheckAttributeBlock, ignoreDiscriminator);
            case 'containsAllOf':
                return ListCheckAttributeBlockToJSONTyped(value as ListCheckAttributeBlock, ignoreDiscriminator);
            case 'containsAtLeast':
                return ListWithCountCheckAttributeBlockToJSONTyped(value as ListWithCountCheckAttributeBlock, ignoreDiscriminator);
            case 'containsExactly':
                return ListWithCountCheckAttributeBlockToJSONTyped(value as ListWithCountCheckAttributeBlock, ignoreDiscriminator);
            case 'containsNoneOf':
                return ListCheckAttributeBlockToJSONTyped(value as ListCheckAttributeBlock, ignoreDiscriminator);
            case 'containsOneOf':
                return ListCheckAttributeBlockToJSONTyped(value as ListCheckAttributeBlock, ignoreDiscriminator);
            case 'empty':
                return UnaryCheckAttributeBlockToJSONTyped(value as UnaryCheckAttributeBlock, ignoreDiscriminator);
            case 'endsWith':
                return ScalarCheckAttributeBlockToJSONTyped(value as ScalarCheckAttributeBlock, ignoreDiscriminator);
            case 'equals':
                return ScalarCheckAttributeBlockToJSONTyped(value as ScalarCheckAttributeBlock, ignoreDiscriminator);
            case 'exists':
                return UnaryCheckAttributeBlockToJSONTyped(value as UnaryCheckAttributeBlock, ignoreDiscriminator);
            case 'greaterThan':
                return ScalarCheckAttributeBlockToJSONTyped(value as ScalarCheckAttributeBlock, ignoreDiscriminator);
            case 'greaterThanOrEqual':
                return ScalarCheckAttributeBlockToJSONTyped(value as ScalarCheckAttributeBlock, ignoreDiscriminator);
            case 'inCollection':
                return ScalarCheckAttributeBlockToJSONTyped(value as ScalarCheckAttributeBlock, ignoreDiscriminator);
            case 'isFalse':
                return UnaryCheckAttributeBlockToJSONTyped(value as UnaryCheckAttributeBlock, ignoreDiscriminator);
            case 'isTrue':
                return UnaryCheckAttributeBlockToJSONTyped(value as UnaryCheckAttributeBlock, ignoreDiscriminator);
            case 'lessThan':
                return ScalarCheckAttributeBlockToJSONTyped(value as ScalarCheckAttributeBlock, ignoreDiscriminator);
            case 'lessThanOrEqual':
                return ScalarCheckAttributeBlockToJSONTyped(value as ScalarCheckAttributeBlock, ignoreDiscriminator);
            case 'matchesRegexp':
                return ScalarCheckAttributeBlockToJSONTyped(value as ScalarCheckAttributeBlock, ignoreDiscriminator);
            case 'not(contains)':
                return ScalarCheckAttributeBlockToJSONTyped(value as ScalarCheckAttributeBlock, ignoreDiscriminator);
            case 'not(empty)':
                return UnaryCheckAttributeBlockToJSONTyped(value as UnaryCheckAttributeBlock, ignoreDiscriminator);
            case 'not(equals)':
                return ScalarCheckAttributeBlockToJSONTyped(value as ScalarCheckAttributeBlock, ignoreDiscriminator);
            case 'not(exists)':
                return UnaryCheckAttributeBlockToJSONTyped(value as UnaryCheckAttributeBlock, ignoreDiscriminator);
            case 'not(inCollection)':
                return ScalarCheckAttributeBlockToJSONTyped(value as ScalarCheckAttributeBlock, ignoreDiscriminator);
            case 'not(oneOf)':
                return ScalarCheckAttributeBlockToJSONTyped(value as ScalarCheckAttributeBlock, ignoreDiscriminator);
            case 'oneOf':
                return ScalarCheckAttributeBlockToJSONTyped(value as ScalarCheckAttributeBlock, ignoreDiscriminator);
            case 'startsWith':
                return ScalarCheckAttributeBlockToJSONTyped(value as ScalarCheckAttributeBlock, ignoreDiscriminator);
            default:
                return value;
        }
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'tags': value['tags'],
        'operator': value['operator'],
        'attribute': value['attribute'],
        'value': value['value'],
        'min': value['min'],
        'max': value['max'],
        'values': value['values'],
        'count': value['count'],
    };
}

