/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Collection
 */
export interface Collection {
    /**
     * The internal ID of this entity.
     * @type {number}
     * @memberof Collection
     */
    id: number;
    /**
     * The time this entity was created.
     * @type {Date}
     * @memberof Collection
     */
    created: Date;
    /**
     * The ID of the account that owns this entity.
     * @type {number}
     * @memberof Collection
     */
    accountId: number;
    /**
     * The time this entity was last modified.
     * @type {Date}
     * @memberof Collection
     */
    modified: Date;
    /**
     * A short description of the purpose of this collection.
     * @type {string}
     * @memberof Collection
     */
    description?: string;
    /**
     * A list of the IDs of the Applications where this collection is enabled.
     * @type {Array<number>}
     * @memberof Collection
     */
    subscribedApplicationsIds?: Array<number>;
    /**
     * The name of this collection.
     * @type {string}
     * @memberof Collection
     */
    name: string;
    /**
     * ID of the user who last updated this effect if available.
     * @type {number}
     * @memberof Collection
     */
    modifiedBy?: number;
    /**
     * ID of the user who created this effect.
     * @type {number}
     * @memberof Collection
     */
    createdBy: number;
    /**
     * The ID of the Application that owns this entity.
     * @type {number}
     * @memberof Collection
     */
    applicationId?: number;
    /**
     * The ID of the campaign that owns this entity.
     * @type {number}
     * @memberof Collection
     */
    campaignId?: number;
    /**
     * The content of the collection.
     * @type {Array<string>}
     * @memberof Collection
     */
    payload?: Array<string>;
}

/**
 * Check if a given object implements the Collection interface.
 */
export function instanceOfCollection(value: object): value is Collection {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('modified' in value) || value['modified'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    return true;
}

export function CollectionFromJSON(json: any): Collection {
    return CollectionFromJSONTyped(json, false);
}

export function CollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Collection {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'created': (new Date(json['created'])),
        'accountId': json['accountId'],
        'modified': (new Date(json['modified'])),
        'description': json['description'] == null ? undefined : json['description'],
        'subscribedApplicationsIds': json['subscribedApplicationsIds'] == null ? undefined : json['subscribedApplicationsIds'],
        'name': json['name'],
        'modifiedBy': json['modifiedBy'] == null ? undefined : json['modifiedBy'],
        'createdBy': json['createdBy'],
        'applicationId': json['applicationId'] == null ? undefined : json['applicationId'],
        'campaignId': json['campaignId'] == null ? undefined : json['campaignId'],
        'payload': json['payload'] == null ? undefined : json['payload'],
    };
}

export function CollectionToJSON(json: any): Collection {
    return CollectionToJSONTyped(json, false);
}

export function CollectionToJSONTyped(value?: Collection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created': value['created'].toISOString(),
        'accountId': value['accountId'],
        'modified': value['modified'].toISOString(),
        'description': value['description'],
        'subscribedApplicationsIds': value['subscribedApplicationsIds'],
        'name': value['name'],
        'modifiedBy': value['modifiedBy'],
        'createdBy': value['createdBy'],
        'applicationId': value['applicationId'],
        'campaignId': value['campaignId'],
        'payload': value['payload'],
    };
}

