/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The properties specific to the "couponCreated" effect. This gets triggered whenever a validated rule contained a "create coupon" effect, and a coupon was created for a customer. See "createdCoupons" on the response for all details of this coupon.
 * @export
 * @interface CouponCreatedEffectProps
 */
export interface CouponCreatedEffectProps {
    /**
     * The coupon code that was created.
     * @type {string}
     * @memberof CouponCreatedEffectProps
     */
    value: string;
    /**
     * The integration identifier of the customer for whom this coupon was created.
     * @type {string}
     * @memberof CouponCreatedEffectProps
     */
    profileId: string;
}

/**
 * Check if a given object implements the CouponCreatedEffectProps interface.
 */
export function instanceOfCouponCreatedEffectProps(value: object): value is CouponCreatedEffectProps {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('profileId' in value) || value['profileId'] === undefined) return false;
    return true;
}

export function CouponCreatedEffectPropsFromJSON(json: any): CouponCreatedEffectProps {
    return CouponCreatedEffectPropsFromJSONTyped(json, false);
}

export function CouponCreatedEffectPropsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CouponCreatedEffectProps {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'profileId': json['profileId'],
    };
}

export function CouponCreatedEffectPropsToJSON(json: any): CouponCreatedEffectProps {
    return CouponCreatedEffectPropsToJSONTyped(json, false);
}

export function CouponCreatedEffectPropsToJSONTyped(value?: CouponCreatedEffectProps | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'profileId': value['profileId'],
    };
}

