/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A summary report of customer activity for a given time range.
 * @export
 * @interface CustomerActivityReport
 */
export interface CustomerActivityReport {
    /**
     * The integration ID set by your integration layer.
     * @type {string}
     * @memberof CustomerActivityReport
     */
    integrationId: string;
    /**
     * The time this entity was created.
     * @type {Date}
     * @memberof CustomerActivityReport
     */
    created: Date;
    /**
     * The name for this customer profile.
     * @type {string}
     * @memberof CustomerActivityReport
     */
    name: string;
    /**
     * The internal Talon.One ID of the customer.
     * @type {number}
     * @memberof CustomerActivityReport
     */
    customerId: number;
    /**
     * The last activity of the customer.
     * @type {Date}
     * @memberof CustomerActivityReport
     */
    lastActivity?: Date;
    /**
     * Number of coupon redemptions in all customer campaigns.
     * @type {number}
     * @memberof CustomerActivityReport
     */
    couponRedemptions: number;
    /**
     * Number of coupon use attempts in all customer campaigns.
     * @type {number}
     * @memberof CustomerActivityReport
     */
    couponUseAttempts: number;
    /**
     * Number of failed coupon use attempts in all customer campaigns.
     * @type {number}
     * @memberof CustomerActivityReport
     */
    couponFailedAttempts: number;
    /**
     * Number of accrued discounts in all customer campaigns.
     * @type {number}
     * @memberof CustomerActivityReport
     */
    accruedDiscounts: number;
    /**
     * Amount of accrued revenue in all customer campaigns.
     * @type {number}
     * @memberof CustomerActivityReport
     */
    accruedRevenue: number;
    /**
     * Number of orders in all customer campaigns.
     * @type {number}
     * @memberof CustomerActivityReport
     */
    totalOrders: number;
    /**
     * Number of orders without coupon used in all customer campaigns.
     * @type {number}
     * @memberof CustomerActivityReport
     */
    totalOrdersNoCoupon: number;
    /**
     * The name of the campaign this customer belongs to.
     * @type {string}
     * @memberof CustomerActivityReport
     */
    campaignName: string;
}

/**
 * Check if a given object implements the CustomerActivityReport interface.
 */
export function instanceOfCustomerActivityReport(value: object): value is CustomerActivityReport {
    if (!('integrationId' in value) || value['integrationId'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('couponRedemptions' in value) || value['couponRedemptions'] === undefined) return false;
    if (!('couponUseAttempts' in value) || value['couponUseAttempts'] === undefined) return false;
    if (!('couponFailedAttempts' in value) || value['couponFailedAttempts'] === undefined) return false;
    if (!('accruedDiscounts' in value) || value['accruedDiscounts'] === undefined) return false;
    if (!('accruedRevenue' in value) || value['accruedRevenue'] === undefined) return false;
    if (!('totalOrders' in value) || value['totalOrders'] === undefined) return false;
    if (!('totalOrdersNoCoupon' in value) || value['totalOrdersNoCoupon'] === undefined) return false;
    if (!('campaignName' in value) || value['campaignName'] === undefined) return false;
    return true;
}

export function CustomerActivityReportFromJSON(json: any): CustomerActivityReport {
    return CustomerActivityReportFromJSONTyped(json, false);
}

export function CustomerActivityReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerActivityReport {
    if (json == null) {
        return json;
    }
    return {
        
        'integrationId': json['integrationId'],
        'created': (new Date(json['created'])),
        'name': json['name'],
        'customerId': json['customerId'],
        'lastActivity': json['lastActivity'] == null ? undefined : (new Date(json['lastActivity'])),
        'couponRedemptions': json['couponRedemptions'],
        'couponUseAttempts': json['couponUseAttempts'],
        'couponFailedAttempts': json['couponFailedAttempts'],
        'accruedDiscounts': json['accruedDiscounts'],
        'accruedRevenue': json['accruedRevenue'],
        'totalOrders': json['totalOrders'],
        'totalOrdersNoCoupon': json['totalOrdersNoCoupon'],
        'campaignName': json['campaignName'],
    };
}

export function CustomerActivityReportToJSON(json: any): CustomerActivityReport {
    return CustomerActivityReportToJSONTyped(json, false);
}

export function CustomerActivityReportToJSONTyped(value?: CustomerActivityReport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'integrationId': value['integrationId'],
        'created': value['created'].toISOString(),
        'name': value['name'],
        'customerId': value['customerId'],
        'lastActivity': value['lastActivity'] == null ? value['lastActivity'] : value['lastActivity'].toISOString(),
        'couponRedemptions': value['couponRedemptions'],
        'couponUseAttempts': value['couponUseAttempts'],
        'couponFailedAttempts': value['couponFailedAttempts'],
        'accruedDiscounts': value['accruedDiscounts'],
        'accruedRevenue': value['accruedRevenue'],
        'totalOrders': value['totalOrders'],
        'totalOrdersNoCoupon': value['totalOrdersNoCoupon'],
        'campaignName': value['campaignName'],
    };
}

