/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TemplateArgDef } from './TemplateArgDef';
import {
    TemplateArgDefFromJSON,
    TemplateArgDefFromJSONTyped,
    TemplateArgDefToJSON,
    TemplateArgDefToJSONTyped,
} from './TemplateArgDef';

/**
 * 
 * @export
 * @interface CustomEffect
 */
export interface CustomEffect {
    /**
     * The internal ID of this entity.
     * @type {number}
     * @memberof CustomEffect
     */
    id: number;
    /**
     * The time this entity was created.
     * @type {Date}
     * @memberof CustomEffect
     */
    created: Date;
    /**
     * The ID of the account that owns this entity.
     * @type {number}
     * @memberof CustomEffect
     */
    accountId: number;
    /**
     * The time this entity was last modified.
     * @type {Date}
     * @memberof CustomEffect
     */
    modified: Date;
    /**
     * The IDs of the Applications that are related to this entity.
     * @type {Array<number>}
     * @memberof CustomEffect
     */
    applicationIds: Array<number>;
    /**
     * Indicates if this effect is per item or not.
     * @type {boolean}
     * @memberof CustomEffect
     */
    isPerItem?: boolean;
    /**
     * The name of this effect.
     * @type {string}
     * @memberof CustomEffect
     */
    name: string;
    /**
     * The title of this effect.
     * @type {string}
     * @memberof CustomEffect
     */
    title: string;
    /**
     * The JSON payload of this effect.
     * @type {string}
     * @memberof CustomEffect
     */
    payload: string;
    /**
     * The description of this effect.
     * @type {string}
     * @memberof CustomEffect
     */
    description?: string;
    /**
     * Determines if this effect is active.
     * @type {boolean}
     * @memberof CustomEffect
     */
    enabled: boolean;
    /**
     * Array of template argument definitions.
     * @type {Array<TemplateArgDef>}
     * @memberof CustomEffect
     */
    params?: Array<TemplateArgDef>;
    /**
     * ID of the user who last updated this effect if available.
     * @type {number}
     * @memberof CustomEffect
     */
    modifiedBy?: number;
    /**
     * ID of the user who created this effect.
     * @type {number}
     * @memberof CustomEffect
     */
    createdBy: number;
}

/**
 * Check if a given object implements the CustomEffect interface.
 */
export function instanceOfCustomEffect(value: object): value is CustomEffect {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('modified' in value) || value['modified'] === undefined) return false;
    if (!('applicationIds' in value) || value['applicationIds'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    return true;
}

export function CustomEffectFromJSON(json: any): CustomEffect {
    return CustomEffectFromJSONTyped(json, false);
}

export function CustomEffectFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomEffect {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'created': (new Date(json['created'])),
        'accountId': json['accountId'],
        'modified': (new Date(json['modified'])),
        'applicationIds': json['applicationIds'],
        'isPerItem': json['isPerItem'] == null ? undefined : json['isPerItem'],
        'name': json['name'],
        'title': json['title'],
        'payload': json['payload'],
        'description': json['description'] == null ? undefined : json['description'],
        'enabled': json['enabled'],
        'params': json['params'] == null ? undefined : ((json['params'] as Array<any>).map(TemplateArgDefFromJSON)),
        'modifiedBy': json['modifiedBy'] == null ? undefined : json['modifiedBy'],
        'createdBy': json['createdBy'],
    };
}

export function CustomEffectToJSON(json: any): CustomEffect {
    return CustomEffectToJSONTyped(json, false);
}

export function CustomEffectToJSONTyped(value?: CustomEffect | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created': value['created'].toISOString(),
        'accountId': value['accountId'],
        'modified': value['modified'].toISOString(),
        'applicationIds': value['applicationIds'],
        'isPerItem': value['isPerItem'],
        'name': value['name'],
        'title': value['title'],
        'payload': value['payload'],
        'description': value['description'],
        'enabled': value['enabled'],
        'params': value['params'] == null ? undefined : ((value['params'] as Array<any>).map(TemplateArgDefToJSON)),
        'modifiedBy': value['modifiedBy'],
        'createdBy': value['createdBy'],
    };
}

