/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SetLoyaltyPointsExpiryDateEffectProps } from './SetLoyaltyPointsExpiryDateEffectProps';
import {
    SetLoyaltyPointsExpiryDateEffectPropsFromJSON,
    SetLoyaltyPointsExpiryDateEffectPropsFromJSONTyped,
    SetLoyaltyPointsExpiryDateEffectPropsToJSON,
    SetLoyaltyPointsExpiryDateEffectPropsToJSONTyped,
} from './SetLoyaltyPointsExpiryDateEffectProps';

/**
 * 
 * @export
 * @interface EffectSetLoyaltyPointsExpiryDate
 */
export interface EffectSetLoyaltyPointsExpiryDate {
    /**
     * The ID of the experiment that campaign belongs to.
     */
    experimentId?: number;
    /**
     * The ID of the campaign that triggered this effect.
     */
    campaignId: number;
    /**
     * The ID of the ruleset that was active in the campaign when this effect was triggered.
     */
    rulesetId: number;
    /**
     * The position of the rule that triggered this effect within the ruleset.
     */
    ruleIndex: number;
    /**
     * The name of the rule that triggered this effect.
     */
    ruleName: string;
    /**
     * An effect discriminator of type `setLoyaltyPointsExpiryDate`.
     */
    effectType: EffectSetLoyaltyPointsExpiryDateEffectTypeEnum;
    /**
     * The ID of the coupon that was being evaluated when this effect was triggered.
     */
    triggeredByCoupon?: number;
    /**
     * The ID of the catalog item that was being evaluated when this effect was triggered.
     */
    triggeredForCatalogItem?: number;
    /**
     * The index of the condition that was triggered.
     */
    conditionIndex?: number;
    /**
     * The ID of the evaluation group. For more information, see [Managing campaign evaluation](https://docs.talon.one/docs/product/applications/managing-campaign-evaluation).
     */
    evaluationGroupID?: number;
    /**
     * The evaluation mode of the evaluation group. For more information, see [Managing campaign evaluation](https://docs.talon.one/docs/product/applications/managing-campaign-evaluation).
     */
    evaluationGroupMode?: string;
    /**
     * The revision ID of the campaign that was used when triggering the effect.
     */
    campaignRevisionId?: number;
    /**
     * The revision version ID of the campaign that was used when triggering the effect.
     */
    campaignRevisionVersionId?: number;
    /**
     * The selected price type for the SKU targeted by this effect.
     */
    selectedPriceType?: string;
    /**
     * The value of the selected price type to apply to the SKU targeted by this effect, before any discounts are applied.
     */
    selectedPrice?: number;
    /**
     * The reference identifier of the selected price adjustment for this SKU. This is only returned if the `selectedPrice` resulted from a price adjustment.
     */
    adjustmentReferenceId?: string;
    /**
     * The ID of the reward that was being evaluated when this effect was triggered.
     */
    rewardId?: number;
    /**
     * The properties of the `setLoyaltyPointsExpiryDate` effect.
     */
    props: SetLoyaltyPointsExpiryDateEffectProps;
}


/**
 * @export
 */
export const EffectSetLoyaltyPointsExpiryDateEffectTypeEnum = {
    SetLoyaltyPointsExpiryDate: 'setLoyaltyPointsExpiryDate',
} as const;
export type EffectSetLoyaltyPointsExpiryDateEffectTypeEnum = typeof EffectSetLoyaltyPointsExpiryDateEffectTypeEnum[keyof typeof EffectSetLoyaltyPointsExpiryDateEffectTypeEnum];


/**
 * Check if a given object implements the EffectSetLoyaltyPointsExpiryDate interface.
 */
export function instanceOfEffectSetLoyaltyPointsExpiryDate(value: object): value is EffectSetLoyaltyPointsExpiryDate {
    const _v = value as Record<PropertyKey, unknown>;
    if (!('campaignId' in _v) || _v['campaignId'] === undefined) return false;
    if (!('rulesetId' in _v) || _v['rulesetId'] === undefined) return false;
    if (!('ruleIndex' in _v) || _v['ruleIndex'] === undefined) return false;
    if (!('ruleName' in _v) || _v['ruleName'] === undefined) return false;
    if (!('effectType' in _v) || _v['effectType'] === undefined) return false;
    if (_v['effectType'] !== 'setLoyaltyPointsExpiryDate') return false;
    
    if (!('props' in _v) || _v['props'] === undefined) return false;
    return true;
}

export function EffectSetLoyaltyPointsExpiryDateFromJSON(json: any): EffectSetLoyaltyPointsExpiryDate {
    return EffectSetLoyaltyPointsExpiryDateFromJSONTyped(json, false);
}

export function EffectSetLoyaltyPointsExpiryDateFromJSONTyped(json: any, ignoreDiscriminator: boolean): EffectSetLoyaltyPointsExpiryDate {
    if (json == null) {
        return json;
    }
    return {
        
        'experimentId': json['experimentId'] == null ? undefined : json['experimentId'],
        'campaignId': json['campaignId'],
        'rulesetId': json['rulesetId'],
        'ruleIndex': json['ruleIndex'],
        'ruleName': json['ruleName'],
        'effectType': json['effectType'],
        'triggeredByCoupon': json['triggeredByCoupon'] == null ? undefined : json['triggeredByCoupon'],
        'triggeredForCatalogItem': json['triggeredForCatalogItem'] == null ? undefined : json['triggeredForCatalogItem'],
        'conditionIndex': json['conditionIndex'] == null ? undefined : json['conditionIndex'],
        'evaluationGroupID': json['evaluationGroupID'] == null ? undefined : json['evaluationGroupID'],
        'evaluationGroupMode': json['evaluationGroupMode'] == null ? undefined : json['evaluationGroupMode'],
        'campaignRevisionId': json['campaignRevisionId'] == null ? undefined : json['campaignRevisionId'],
        'campaignRevisionVersionId': json['campaignRevisionVersionId'] == null ? undefined : json['campaignRevisionVersionId'],
        'selectedPriceType': json['selectedPriceType'] == null ? undefined : json['selectedPriceType'],
        'selectedPrice': json['selectedPrice'] == null ? undefined : json['selectedPrice'],
        'adjustmentReferenceId': json['adjustmentReferenceId'] == null ? undefined : json['adjustmentReferenceId'],
        'rewardId': json['rewardId'] == null ? undefined : json['rewardId'],
        'props': SetLoyaltyPointsExpiryDateEffectPropsFromJSON(json['props']),
    };
}

export function EffectSetLoyaltyPointsExpiryDateToJSON(json: any): EffectSetLoyaltyPointsExpiryDate {
    return EffectSetLoyaltyPointsExpiryDateToJSONTyped(json, false);
}

export function EffectSetLoyaltyPointsExpiryDateToJSONTyped(value?: EffectSetLoyaltyPointsExpiryDate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'experimentId': value['experimentId'],
        'campaignId': value['campaignId'],
        'rulesetId': value['rulesetId'],
        'ruleIndex': value['ruleIndex'],
        'ruleName': value['ruleName'],
        'effectType': value['effectType'],
        'triggeredByCoupon': value['triggeredByCoupon'],
        'triggeredForCatalogItem': value['triggeredForCatalogItem'],
        'conditionIndex': value['conditionIndex'],
        'evaluationGroupID': value['evaluationGroupID'],
        'evaluationGroupMode': value['evaluationGroupMode'],
        'campaignRevisionId': value['campaignRevisionId'],
        'campaignRevisionVersionId': value['campaignRevisionVersionId'],
        'selectedPriceType': value['selectedPriceType'],
        'selectedPrice': value['selectedPrice'],
        'adjustmentReferenceId': value['adjustmentReferenceId'],
        'rewardId': value['rewardId'],
        'props': SetLoyaltyPointsExpiryDateEffectPropsToJSON(value['props']),
    };
}

