/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface ExperimentCampaignCopy
 */
export interface ExperimentCampaignCopy {
    /**
     * Name of the copied campaign (Defaults to "Copy of original campaign name").
     */
    name?: string;
    /**
     * A detailed description of the campaign.
     */
    description?: string;
    /**
     * Timestamp when the campaign will become active.
     */
    startTime?: Date;
    /**
     * Timestamp when the campaign will become inactive.
     */
    endTime?: Date;
    /**
     * A list of tags for the campaign.
     */
    tags?: Array<string>;
    /**
     * The ID of the campaign evaluation group the campaign belongs to.
     */
    evaluationGroupId?: number;
}

/**
 * Check if a given object implements the ExperimentCampaignCopy interface.
 */
export function instanceOfExperimentCampaignCopy(value: object): value is ExperimentCampaignCopy {
    const _v = value as Record<PropertyKey, unknown>;
    return true;
}

export function ExperimentCampaignCopyFromJSON(json: any): ExperimentCampaignCopy {
    return ExperimentCampaignCopyFromJSONTyped(json, false);
}

export function ExperimentCampaignCopyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExperimentCampaignCopy {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'startTime': json['startTime'] == null ? undefined : (parseDateTime(json['startTime'])),
        'endTime': json['endTime'] == null ? undefined : (parseDateTime(json['endTime'])),
        'tags': json['tags'] == null ? undefined : json['tags'],
        'evaluationGroupId': json['evaluationGroupId'] == null ? undefined : json['evaluationGroupId'],
    };
}

export function ExperimentCampaignCopyToJSON(json: any): ExperimentCampaignCopy {
    return ExperimentCampaignCopyToJSONTyped(json, false);
}

export function ExperimentCampaignCopyToJSONTyped(value?: ExperimentCampaignCopy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'startTime': value['startTime'] == null ? value['startTime'] : serializeDateTime(value['startTime']),
        'endTime': value['endTime'] == null ? value['endTime'] : serializeDateTime(value['endTime']),
        'tags': value['tags'],
        'evaluationGroupId': value['evaluationGroupId'],
    };
}

