/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExperimentVariantResultConfidence } from './ExperimentVariantResultConfidence';
import {
    ExperimentVariantResultConfidenceFromJSON,
    ExperimentVariantResultConfidenceFromJSONTyped,
    ExperimentVariantResultConfidenceToJSON,
    ExperimentVariantResultConfidenceToJSONTyped,
} from './ExperimentVariantResultConfidence';
import type { ExperimentVariantResult } from './ExperimentVariantResult';
import {
    ExperimentVariantResultFromJSON,
    ExperimentVariantResultFromJSONTyped,
    ExperimentVariantResultToJSON,
    ExperimentVariantResultToJSONTyped,
} from './ExperimentVariantResult';

/**
 * 
 * @export
 * @interface ExperimentResults
 */
export interface ExperimentResults {
    /**
     * 
     * @type {Array<ExperimentVariantResult>}
     * @memberof ExperimentResults
     */
    variants?: Array<ExperimentVariantResult>;
    /**
     * 
     * @type {ExperimentVariantResultConfidence}
     * @memberof ExperimentResults
     */
    confidence: ExperimentVariantResultConfidence;
}

/**
 * Check if a given object implements the ExperimentResults interface.
 */
export function instanceOfExperimentResults(value: object): value is ExperimentResults {
    if (!('confidence' in value) || value['confidence'] === undefined) return false;
    return true;
}

export function ExperimentResultsFromJSON(json: any): ExperimentResults {
    return ExperimentResultsFromJSONTyped(json, false);
}

export function ExperimentResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExperimentResults {
    if (json == null) {
        return json;
    }
    return {
        
        'variants': json['variants'] == null ? undefined : ((json['variants'] as Array<any>).map(ExperimentVariantResultFromJSON)),
        'confidence': ExperimentVariantResultConfidenceFromJSON(json['confidence']),
    };
}

export function ExperimentResultsToJSON(json: any): ExperimentResults {
    return ExperimentResultsToJSONTyped(json, false);
}

export function ExperimentResultsToJSONTyped(value?: ExperimentResults | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'variants': value['variants'] == null ? undefined : ((value['variants'] as Array<any>).map(ExperimentVariantResultToJSON)),
        'confidence': ExperimentVariantResultConfidenceToJSON(value['confidence']),
    };
}

