/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExpiringCouponsNotificationTrigger } from './ExpiringCouponsNotificationTrigger';
import {
    ExpiringCouponsNotificationTriggerFromJSON,
    ExpiringCouponsNotificationTriggerFromJSONTyped,
    ExpiringCouponsNotificationTriggerToJSON,
    ExpiringCouponsNotificationTriggerToJSONTyped,
} from './ExpiringCouponsNotificationTrigger';

/**
 * 
 * @export
 * @interface ExpiringCouponsNotificationPolicy
 */
export interface ExpiringCouponsNotificationPolicy {
    /**
     * Notification name.
     * @type {string}
     * @memberof ExpiringCouponsNotificationPolicy
     */
    name: string;
    /**
     * 
     * @type {Array<ExpiringCouponsNotificationTrigger>}
     * @memberof ExpiringCouponsNotificationPolicy
     */
    triggers: Array<ExpiringCouponsNotificationTrigger>;
    /**
     * Indicates whether batching is activated.
     * @type {boolean}
     * @memberof ExpiringCouponsNotificationPolicy
     */
    batchingEnabled?: boolean;
    /**
     * The required size of each batch of data. This value applies only when `batchingEnabled` is `true`.
     * @type {number}
     * @memberof ExpiringCouponsNotificationPolicy
     */
    batchSize?: number;
}

/**
 * Check if a given object implements the ExpiringCouponsNotificationPolicy interface.
 */
export function instanceOfExpiringCouponsNotificationPolicy(value: object): value is ExpiringCouponsNotificationPolicy {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('triggers' in value) || value['triggers'] === undefined) return false;
    return true;
}

export function ExpiringCouponsNotificationPolicyFromJSON(json: any): ExpiringCouponsNotificationPolicy {
    return ExpiringCouponsNotificationPolicyFromJSONTyped(json, false);
}

export function ExpiringCouponsNotificationPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpiringCouponsNotificationPolicy {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'triggers': ((json['triggers'] as Array<any>).map(ExpiringCouponsNotificationTriggerFromJSON)),
        'batchingEnabled': json['batchingEnabled'] == null ? undefined : json['batchingEnabled'],
        'batchSize': json['batchSize'] == null ? undefined : json['batchSize'],
    };
}

export function ExpiringCouponsNotificationPolicyToJSON(json: any): ExpiringCouponsNotificationPolicy {
    return ExpiringCouponsNotificationPolicyToJSONTyped(json, false);
}

export function ExpiringCouponsNotificationPolicyToJSONTyped(value?: ExpiringCouponsNotificationPolicy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'triggers': ((value['triggers'] as Array<any>).map(ExpiringCouponsNotificationTriggerToJSON)),
        'batchingEnabled': value['batchingEnabled'],
        'batchSize': value['batchSize'],
    };
}

