/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExpiringPointsData
 */
export interface ExpiringPointsData {
    /**
     * The expiration date of loyalty points.
     * @type {Date}
     * @memberof ExpiringPointsData
     */
    expiryDate: Date;
    /**
     * The ID of the loyalty program.
     * @type {number}
     * @memberof ExpiringPointsData
     */
    loyaltyProgramID: number;
    /**
     * The integration ID of the customer profile that has expiring points.
     * @type {string}
     * @memberof ExpiringPointsData
     */
    customerProfileID: string;
    /**
     * The amount of loyalty points that will be expired soon.
     * @type {number}
     * @memberof ExpiringPointsData
     */
    amountOfExpiringPoints: number;
    /**
     * The ID of the subledger within the loyalty program where these points were added.
     * @type {string}
     * @memberof ExpiringPointsData
     */
    subledgerID: string;
}

/**
 * Check if a given object implements the ExpiringPointsData interface.
 */
export function instanceOfExpiringPointsData(value: object): value is ExpiringPointsData {
    if (!('expiryDate' in value) || value['expiryDate'] === undefined) return false;
    if (!('loyaltyProgramID' in value) || value['loyaltyProgramID'] === undefined) return false;
    if (!('customerProfileID' in value) || value['customerProfileID'] === undefined) return false;
    if (!('amountOfExpiringPoints' in value) || value['amountOfExpiringPoints'] === undefined) return false;
    if (!('subledgerID' in value) || value['subledgerID'] === undefined) return false;
    return true;
}

export function ExpiringPointsDataFromJSON(json: any): ExpiringPointsData {
    return ExpiringPointsDataFromJSONTyped(json, false);
}

export function ExpiringPointsDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpiringPointsData {
    if (json == null) {
        return json;
    }
    return {
        
        'expiryDate': (new Date(json['ExpiryDate'])),
        'loyaltyProgramID': json['LoyaltyProgramID'],
        'customerProfileID': json['CustomerProfileID'],
        'amountOfExpiringPoints': json['AmountOfExpiringPoints'],
        'subledgerID': json['SubledgerID'],
    };
}

export function ExpiringPointsDataToJSON(json: any): ExpiringPointsData {
    return ExpiringPointsDataToJSONTyped(json, false);
}

export function ExpiringPointsDataToJSONTyped(value?: ExpiringPointsData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ExpiryDate': value['expiryDate'].toISOString().substring(0,10),
        'LoyaltyProgramID': value['loyaltyProgramID'],
        'CustomerProfileID': value['customerProfileID'],
        'AmountOfExpiringPoints': value['amountOfExpiringPoints'],
        'SubledgerID': value['subledgerID'],
    };
}

