/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExpiringPointsData } from './ExpiringPointsData';
import {
    ExpiringPointsDataFromJSON,
    ExpiringPointsDataFromJSONTyped,
    ExpiringPointsDataToJSON,
    ExpiringPointsDataToJSONTyped,
} from './ExpiringPointsData';

/**
 * 
 * @export
 * @interface ExpiringPointsNotification
 */
export interface ExpiringPointsNotification {
    /**
     * 
     * @type {number}
     * @memberof ExpiringPointsNotification
     */
    totalResultSize: number;
    /**
     * The array of expiring points.
     * @type {Array<ExpiringPointsData>}
     * @memberof ExpiringPointsNotification
     */
    data: Array<ExpiringPointsData>;
    /**
     * The type of notification.
     * @type {string}
     * @memberof ExpiringPointsNotification
     */
    notificationType: ExpiringPointsNotificationNotificationTypeEnum;
}


/**
 * @export
 */
export const ExpiringPointsNotificationNotificationTypeEnum = {
    LoyaltyPointsExpiring: 'LoyaltyPointsExpiring'
} as const;
export type ExpiringPointsNotificationNotificationTypeEnum = typeof ExpiringPointsNotificationNotificationTypeEnum[keyof typeof ExpiringPointsNotificationNotificationTypeEnum];


/**
 * Check if a given object implements the ExpiringPointsNotification interface.
 */
export function instanceOfExpiringPointsNotification(value: object): value is ExpiringPointsNotification {
    if (!('totalResultSize' in value) || value['totalResultSize'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('notificationType' in value) || value['notificationType'] === undefined) return false;
    return true;
}

export function ExpiringPointsNotificationFromJSON(json: any): ExpiringPointsNotification {
    return ExpiringPointsNotificationFromJSONTyped(json, false);
}

export function ExpiringPointsNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpiringPointsNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'totalResultSize': json['TotalResultSize'],
        'data': ((json['Data'] as Array<any>).map(ExpiringPointsDataFromJSON)),
        'notificationType': json['NotificationType'],
    };
}

export function ExpiringPointsNotificationToJSON(json: any): ExpiringPointsNotification {
    return ExpiringPointsNotificationToJSONTyped(json, false);
}

export function ExpiringPointsNotificationToJSONTyped(value?: ExpiringPointsNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'TotalResultSize': value['totalResultSize'],
        'Data': ((value['data'] as Array<any>).map(ExpiringPointsDataToJSON)),
        'NotificationType': value['notificationType'],
    };
}

