/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CouponFailureSummary } from './CouponFailureSummary';
import {
    CouponFailureSummaryFromJSON,
    CouponFailureSummaryFromJSONTyped,
    CouponFailureSummaryToJSON,
    CouponFailureSummaryToJSONTyped,
} from './CouponFailureSummary';

/**
 * 
 * @export
 * @interface GenerateCouponRejections200Response
 */
export interface GenerateCouponRejections200Response {
    /**
     * 
     * @type {Array<CouponFailureSummary>}
     * @memberof GenerateCouponRejections200Response
     */
    data: Array<CouponFailureSummary>;
}

/**
 * Check if a given object implements the GenerateCouponRejections200Response interface.
 */
export function instanceOfGenerateCouponRejections200Response(value: object): value is GenerateCouponRejections200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GenerateCouponRejections200ResponseFromJSON(json: any): GenerateCouponRejections200Response {
    return GenerateCouponRejections200ResponseFromJSONTyped(json, false);
}

export function GenerateCouponRejections200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateCouponRejections200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(CouponFailureSummaryFromJSON)),
    };
}

export function GenerateCouponRejections200ResponseToJSON(json: any): GenerateCouponRejections200Response {
    return GenerateCouponRejections200ResponseToJSONTyped(json, false);
}

export function GenerateCouponRejections200ResponseToJSONTyped(value?: GenerateCouponRejections200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(CouponFailureSummaryToJSON)),
    };
}

