/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeoJSONGeometry } from './GeoJSONGeometry';
import {
    GeoJSONGeometryFromJSON,
    GeoJSONGeometryFromJSONTyped,
    GeoJSONGeometryToJSON,
    GeoJSONGeometryToJSONTyped,
} from './GeoJSONGeometry';

/**
 * A group of different shapes combined into a single location, following the GeoJSON format.
 * @export
 * @interface GeoJSONGeometryCollection
 */
export interface GeoJSONGeometryCollection {
    /**
     * The geometry type discriminator.
     */
    type: GeoJSONGeometryCollectionTypeEnum;
    /**
     * The shapes contained in this group.
     */
    geometries: Array<GeoJSONGeometry>;
}


/**
 * @export
 */
export const GeoJSONGeometryCollectionTypeEnum = {
    GeometryCollection: 'GeometryCollection',
} as const;
export type GeoJSONGeometryCollectionTypeEnum = typeof GeoJSONGeometryCollectionTypeEnum[keyof typeof GeoJSONGeometryCollectionTypeEnum];


/**
 * Check if a given object implements the GeoJSONGeometryCollection interface.
 */
export function instanceOfGeoJSONGeometryCollection(value: object): value is GeoJSONGeometryCollection {
    const _v = value as Record<PropertyKey, unknown>;
    if (!('type' in _v) || _v['type'] === undefined) return false;
    if (_v['type'] !== 'GeometryCollection') return false;
    
    if (!('geometries' in _v) || _v['geometries'] === undefined) return false;
    return true;
}

export function GeoJSONGeometryCollectionFromJSON(json: any): GeoJSONGeometryCollection {
    return GeoJSONGeometryCollectionFromJSONTyped(json, false);
}

export function GeoJSONGeometryCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoJSONGeometryCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'geometries': (json['geometries'] == null ? undefined as any : (json['geometries'] as Array<any>).map(GeoJSONGeometryFromJSON)),
    };
}

export function GeoJSONGeometryCollectionToJSON(json: any): GeoJSONGeometryCollection {
    return GeoJSONGeometryCollectionToJSONTyped(json, false);
}

export function GeoJSONGeometryCollectionToJSONTyped(value?: GeoJSONGeometryCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'geometries': (value['geometries'] == null ? undefined : (value['geometries'] as Array<any>).map(GeoJSONGeometryToJSON)),
    };
}

