/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementProgress } from './AchievementProgress';
import {
    AchievementProgressFromJSON,
    AchievementProgressFromJSONTyped,
    AchievementProgressToJSON,
    AchievementProgressToJSONTyped,
} from './AchievementProgress';

/**
 * 
 * @export
 * @interface GetCustomerAchievementHistory200Response
 */
export interface GetCustomerAchievementHistory200Response {
    /**
     * 
     * @type {number}
     * @memberof GetCustomerAchievementHistory200Response
     */
    totalResultSize: number;
    /**
     * 
     * @type {Array<AchievementProgress>}
     * @memberof GetCustomerAchievementHistory200Response
     */
    data: Array<AchievementProgress>;
}

/**
 * Check if a given object implements the GetCustomerAchievementHistory200Response interface.
 */
export function instanceOfGetCustomerAchievementHistory200Response(value: object): value is GetCustomerAchievementHistory200Response {
    if (!('totalResultSize' in value) || value['totalResultSize'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetCustomerAchievementHistory200ResponseFromJSON(json: any): GetCustomerAchievementHistory200Response {
    return GetCustomerAchievementHistory200ResponseFromJSONTyped(json, false);
}

export function GetCustomerAchievementHistory200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCustomerAchievementHistory200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'totalResultSize': json['totalResultSize'],
        'data': ((json['data'] as Array<any>).map(AchievementProgressFromJSON)),
    };
}

export function GetCustomerAchievementHistory200ResponseToJSON(json: any): GetCustomerAchievementHistory200Response {
    return GetCustomerAchievementHistory200ResponseToJSONTyped(json, false);
}

export function GetCustomerAchievementHistory200ResponseToJSONTyped(value?: GetCustomerAchievementHistory200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalResultSize': value['totalResultSize'],
        'data': ((value['data'] as Array<any>).map(AchievementProgressToJSON)),
    };
}

