/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CampaignTemplate } from './CampaignTemplate';
import {
    CampaignTemplateFromJSON,
    CampaignTemplateFromJSONTyped,
    CampaignTemplateToJSON,
    CampaignTemplateToJSONTyped,
} from './CampaignTemplate';

/**
 * 
 * @export
 * @interface GetCampaignTemplates200Response
 */
export interface GetCampaignTemplates200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetCampaignTemplates200Response
     */
    hasMore: boolean;
    /**
     * 
     * @type {Array<CampaignTemplate>}
     * @memberof GetCampaignTemplates200Response
     */
    data: Array<CampaignTemplate>;
}

/**
 * Check if a given object implements the GetCampaignTemplates200Response interface.
 */
export function instanceOfGetCampaignTemplates200Response(value: object): value is GetCampaignTemplates200Response {
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetCampaignTemplates200ResponseFromJSON(json: any): GetCampaignTemplates200Response {
    return GetCampaignTemplates200ResponseFromJSONTyped(json, false);
}

export function GetCampaignTemplates200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCampaignTemplates200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'hasMore': json['hasMore'],
        'data': ((json['data'] as Array<any>).map(CampaignTemplateFromJSON)),
    };
}

export function GetCampaignTemplates200ResponseToJSON(json: any): GetCampaignTemplates200Response {
    return GetCampaignTemplates200ResponseToJSONTyped(json, false);
}

export function GetCampaignTemplates200ResponseToJSONTyped(value?: GetCampaignTemplates200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hasMore': value['hasMore'],
        'data': ((value['data'] as Array<any>).map(CampaignTemplateToJSON)),
    };
}

