/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoyaltyProgram } from './LoyaltyProgram';
import {
    LoyaltyProgramFromJSON,
    LoyaltyProgramFromJSONTyped,
    LoyaltyProgramToJSON,
    LoyaltyProgramToJSONTyped,
} from './LoyaltyProgram';

/**
 * 
 * @export
 * @interface GetLoyaltyPrograms200Response
 */
export interface GetLoyaltyPrograms200Response {
    /**
     * 
     * @type {number}
     * @memberof GetLoyaltyPrograms200Response
     */
    totalResultSize: number;
    /**
     * 
     * @type {Array<LoyaltyProgram>}
     * @memberof GetLoyaltyPrograms200Response
     */
    data: Array<LoyaltyProgram>;
}

/**
 * Check if a given object implements the GetLoyaltyPrograms200Response interface.
 */
export function instanceOfGetLoyaltyPrograms200Response(value: object): value is GetLoyaltyPrograms200Response {
    if (!('totalResultSize' in value) || value['totalResultSize'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetLoyaltyPrograms200ResponseFromJSON(json: any): GetLoyaltyPrograms200Response {
    return GetLoyaltyPrograms200ResponseFromJSONTyped(json, false);
}

export function GetLoyaltyPrograms200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLoyaltyPrograms200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'totalResultSize': json['totalResultSize'],
        'data': ((json['data'] as Array<any>).map(LoyaltyProgramFromJSON)),
    };
}

export function GetLoyaltyPrograms200ResponseToJSON(json: any): GetLoyaltyPrograms200Response {
    return GetLoyaltyPrograms200ResponseToJSONTyped(json, false);
}

export function GetLoyaltyPrograms200ResponseToJSONTyped(value?: GetLoyaltyPrograms200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalResultSize': value['totalResultSize'],
        'data': ((value['data'] as Array<any>).map(LoyaltyProgramToJSON)),
    };
}

