/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookWithOutgoingIntegrationDetails } from './WebhookWithOutgoingIntegrationDetails';
import {
    WebhookWithOutgoingIntegrationDetailsFromJSON,
    WebhookWithOutgoingIntegrationDetailsFromJSONTyped,
    WebhookWithOutgoingIntegrationDetailsToJSON,
    WebhookWithOutgoingIntegrationDetailsToJSONTyped,
} from './WebhookWithOutgoingIntegrationDetails';

/**
 * 
 * @export
 * @interface GetWebhooks200Response
 */
export interface GetWebhooks200Response {
    /**
     * 
     * @type {number}
     * @memberof GetWebhooks200Response
     */
    totalResultSize: number;
    /**
     * 
     * @type {Array<WebhookWithOutgoingIntegrationDetails>}
     * @memberof GetWebhooks200Response
     */
    data: Array<WebhookWithOutgoingIntegrationDetails>;
}

/**
 * Check if a given object implements the GetWebhooks200Response interface.
 */
export function instanceOfGetWebhooks200Response(value: object): value is GetWebhooks200Response {
    if (!('totalResultSize' in value) || value['totalResultSize'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetWebhooks200ResponseFromJSON(json: any): GetWebhooks200Response {
    return GetWebhooks200ResponseFromJSONTyped(json, false);
}

export function GetWebhooks200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWebhooks200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'totalResultSize': json['totalResultSize'],
        'data': ((json['data'] as Array<any>).map(WebhookWithOutgoingIntegrationDetailsFromJSON)),
    };
}

export function GetWebhooks200ResponseToJSON(json: any): GetWebhooks200Response {
    return GetWebhooks200ResponseToJSONTyped(json, false);
}

export function GetWebhooks200ResponseToJSONTyped(value?: GetWebhooks200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalResultSize': value['totalResultSize'],
        'data': ((value['data'] as Array<any>).map(WebhookWithOutgoingIntegrationDetailsToJSON)),
    };
}

