/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GiveawayPoolNotificationData
 */
export interface GiveawayPoolNotificationData {
    /**
     * The event type of the notification.
     * @type {string}
     * @memberof GiveawayPoolNotificationData
     */
    event: string;
    /**
     * The ID of the giveaway pool.
     * @type {number}
     * @memberof GiveawayPoolNotificationData
     */
    poolId: number;
    /**
     * The name of the giveaway pool.
     * @type {string}
     * @memberof GiveawayPoolNotificationData
     */
    poolName: string;
    /**
     * The description of the giveaway pool.
     * @type {string}
     * @memberof GiveawayPoolNotificationData
     */
    poolDescription: string;
    /**
     * The ID of the account that owns the giveaway pool.
     * @type {number}
     * @memberof GiveawayPoolNotificationData
     */
    accountId: number;
    /**
     * The ID of the Application connected to the giveaway pool.
     * @type {number}
     * @memberof GiveawayPoolNotificationData
     */
    applicationId: number;
    /**
     * The total number of codes in the giveaway pool.
     * @type {number}
     * @memberof GiveawayPoolNotificationData
     */
    totalCodes: number;
    /**
     * The number of codes that have been used.
     * @type {number}
     * @memberof GiveawayPoolNotificationData
     */
    usedCodes: number;
    /**
     * The number of codes remaining in the giveaway pool.
     * @type {number}
     * @memberof GiveawayPoolNotificationData
     */
    remainingCodes: number;
    /**
     * The percentage threshold for the notification. The notification is triggered when the number of codes drops below this threshold.
     * @type {number}
     * @memberof GiveawayPoolNotificationData
     */
    thresholdPercent: number;
}

/**
 * Check if a given object implements the GiveawayPoolNotificationData interface.
 */
export function instanceOfGiveawayPoolNotificationData(value: object): value is GiveawayPoolNotificationData {
    if ((!('event' in value) && !('Event' in value)) || (value['event'] === undefined && value['Event'] === undefined)) return false;
    if ((!('poolId' in value) && !('PoolId' in value)) || (value['poolId'] === undefined && value['PoolId'] === undefined)) return false;
    if ((!('poolName' in value) && !('PoolName' in value)) || (value['poolName'] === undefined && value['PoolName'] === undefined)) return false;
    if ((!('poolDescription' in value) && !('PoolDescription' in value)) || (value['poolDescription'] === undefined && value['PoolDescription'] === undefined)) return false;
    if ((!('accountId' in value) && !('AccountId' in value)) || (value['accountId'] === undefined && value['AccountId'] === undefined)) return false;
    if ((!('applicationId' in value) && !('ApplicationId' in value)) || (value['applicationId'] === undefined && value['ApplicationId'] === undefined)) return false;
    if ((!('totalCodes' in value) && !('TotalCodes' in value)) || (value['totalCodes'] === undefined && value['TotalCodes'] === undefined)) return false;
    if ((!('usedCodes' in value) && !('UsedCodes' in value)) || (value['usedCodes'] === undefined && value['UsedCodes'] === undefined)) return false;
    if ((!('remainingCodes' in value) && !('RemainingCodes' in value)) || (value['remainingCodes'] === undefined && value['RemainingCodes'] === undefined)) return false;
    if ((!('thresholdPercent' in value) && !('ThresholdPercent' in value)) || (value['thresholdPercent'] === undefined && value['ThresholdPercent'] === undefined)) return false;
    return true;
}

export function GiveawayPoolNotificationDataFromJSON(json: any): GiveawayPoolNotificationData {
    return GiveawayPoolNotificationDataFromJSONTyped(json, false);
}

export function GiveawayPoolNotificationDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GiveawayPoolNotificationData {
    if (json == null) {
        return json;
    }
    return {
        
        'event': json['Event'],
        'poolId': json['PoolId'],
        'poolName': json['PoolName'],
        'poolDescription': json['PoolDescription'],
        'accountId': json['AccountId'],
        'applicationId': json['ApplicationId'],
        'totalCodes': json['TotalCodes'],
        'usedCodes': json['UsedCodes'],
        'remainingCodes': json['RemainingCodes'],
        'thresholdPercent': json['ThresholdPercent'],
    };
}

export function GiveawayPoolNotificationDataToJSON(json: any): GiveawayPoolNotificationData {
    return GiveawayPoolNotificationDataToJSONTyped(json, false);
}

export function GiveawayPoolNotificationDataToJSONTyped(value?: GiveawayPoolNotificationData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Event': value['event'],
        'PoolId': value['poolId'],
        'PoolName': value['poolName'],
        'PoolDescription': value['poolDescription'],
        'AccountId': value['accountId'],
        'ApplicationId': value['applicationId'],
        'TotalCodes': value['totalCodes'],
        'UsedCodes': value['usedCodes'],
        'RemainingCodes': value['remainingCodes'],
        'ThresholdPercent': value['thresholdPercent'],
    };
}

