/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Import
 */
export interface Import {
    /**
     * The internal ID of this entity.
     * @type {number}
     * @memberof Import
     */
    id: number;
    /**
     * The time this entity was created.
     * @type {Date}
     * @memberof Import
     */
    created: Date;
    /**
     * The ID of the account that owns this entity.
     * @type {number}
     * @memberof Import
     */
    accountId: number;
    /**
     * The ID of the user associated with this entity.
     * @type {number}
     * @memberof Import
     */
    userId: number;
    /**
     * The name of the entity that was imported.
     * 
     * @type {string}
     * @memberof Import
     */
    entity: string;
    /**
     * The number of values that were imported.
     * @type {number}
     * @memberof Import
     */
    amount: number;
}

/**
 * Check if a given object implements the Import interface.
 */
export function instanceOfImport(value: object): value is Import {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('entity' in value) || value['entity'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function ImportFromJSON(json: any): Import {
    return ImportFromJSONTyped(json, false);
}

export function ImportFromJSONTyped(json: any, ignoreDiscriminator: boolean): Import {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'created': (new Date(json['created'])),
        'accountId': json['accountId'],
        'userId': json['userId'],
        'entity': json['entity'],
        'amount': json['amount'],
    };
}

export function ImportToJSON(json: any): Import {
    return ImportToJSONTyped(json, false);
}

export function ImportToJSONTyped(value?: Import | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created': value['created'].toISOString(),
        'accountId': value['accountId'],
        'userId': value['userId'],
        'entity': value['entity'],
        'amount': value['amount'],
    };
}

