/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IntegrationHubFlowConfigResponse } from './IntegrationHubFlowConfigResponse';
import {
    IntegrationHubFlowConfigResponseFromJSON,
    IntegrationHubFlowConfigResponseFromJSONTyped,
    IntegrationHubFlowConfigResponseToJSON,
    IntegrationHubFlowConfigResponseToJSONTyped,
} from './IntegrationHubFlowConfigResponse';

/**
 * 
 * @export
 * @interface IntegrationHubFlowResponse
 */
export interface IntegrationHubFlowResponse {
    /**
     * ID of the integration hub flow.
     * @type {number}
     * @memberof IntegrationHubFlowResponse
     */
    id: number;
    /**
     * Name of the integration.
     * @type {string}
     * @memberof IntegrationHubFlowResponse
     */
    integrationName?: string;
    /**
     * Name of the integration instance.
     * @type {string}
     * @memberof IntegrationHubFlowResponse
     */
    instanceName?: string;
    /**
     * Timestamp when the flow was created.
     * @type {Date}
     * @memberof IntegrationHubFlowResponse
     */
    createdAt: Date;
    /**
     * Timestamp until which the flow is disabled. Null when the flow is active.
     * @type {Date}
     * @memberof IntegrationHubFlowResponse
     */
    disabledUntil?: Date | null;
    /**
     * ID of the application the flow is registered for.
     * @type {number}
     * @memberof IntegrationHubFlowResponse
     */
    applicationId?: number;
    /**
     * ID of the loyalty program the flow is registered for.
     * @type {number}
     * @memberof IntegrationHubFlowResponse
     */
    loyaltyProgramId?: number;
    /**
     * The event type we want to register a flow for.
     * @type {string}
     * @memberof IntegrationHubFlowResponse
     */
    eventType: string;
    /**
     * 
     * @type {IntegrationHubFlowConfigResponse}
     * @memberof IntegrationHubFlowResponse
     */
    config: IntegrationHubFlowConfigResponse;
}

/**
 * Check if a given object implements the IntegrationHubFlowResponse interface.
 */
export function instanceOfIntegrationHubFlowResponse(value: object): value is IntegrationHubFlowResponse {
    const _v = value as Record<PropertyKey, unknown>;
    if (!('id' in _v) || _v['id'] === undefined) return false;
    if (!('createdAt' in _v) || _v['createdAt'] === undefined) return false;
    if (!('eventType' in _v) || _v['eventType'] === undefined) return false;
    if (!('config' in _v) || _v['config'] === undefined) return false;
    return true;
}

export function IntegrationHubFlowResponseFromJSON(json: any): IntegrationHubFlowResponse {
    return IntegrationHubFlowResponseFromJSONTyped(json, false);
}

export function IntegrationHubFlowResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationHubFlowResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'integrationName': json['integrationName'] == null ? undefined : json['integrationName'],
        'instanceName': json['instanceName'] == null ? undefined : json['instanceName'],
        'createdAt': (json['createdAt'] == null ? undefined as any : new Date(json['createdAt'])),
        'disabledUntil': json['disabledUntil'] === undefined ? undefined : json['disabledUntil'] === null ? null : (new Date(json['disabledUntil'])),
        'applicationId': json['applicationId'] == null ? undefined : json['applicationId'],
        'loyaltyProgramId': json['loyaltyProgramId'] == null ? undefined : json['loyaltyProgramId'],
        'eventType': json['eventType'],
        'config': IntegrationHubFlowConfigResponseFromJSON(json['config']),
    };
}

export function IntegrationHubFlowResponseToJSON(json: any): IntegrationHubFlowResponse {
    return IntegrationHubFlowResponseToJSONTyped(json, false);
}

export function IntegrationHubFlowResponseToJSONTyped(value?: IntegrationHubFlowResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'integrationName': value['integrationName'],
        'instanceName': value['instanceName'],
        'createdAt': value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
        'disabledUntil': value['disabledUntil'] == null ? value['disabledUntil'] : value['disabledUntil'].toISOString(),
        'applicationId': value['applicationId'],
        'loyaltyProgramId': value['loyaltyProgramId'],
        'eventType': value['eventType'],
        'config': IntegrationHubFlowConfigResponseToJSON(value['config']),
    };
}

