/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IntegrationStoreEntity
 */
export interface IntegrationStoreEntity {
    /**
     * The integration ID of the store. You choose this ID when you create a store.
     * @type {string}
     * @memberof IntegrationStoreEntity
     */
    storeIntegrationId?: string;
}

/**
 * Check if a given object implements the IntegrationStoreEntity interface.
 */
export function instanceOfIntegrationStoreEntity(value: object): value is IntegrationStoreEntity {
    return true;
}

export function IntegrationStoreEntityFromJSON(json: any): IntegrationStoreEntity {
    return IntegrationStoreEntityFromJSONTyped(json, false);
}

export function IntegrationStoreEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationStoreEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'storeIntegrationId': json['storeIntegrationId'] == null ? undefined : json['storeIntegrationId'],
    };
}

export function IntegrationStoreEntityToJSON(json: any): IntegrationStoreEntity {
    return IntegrationStoreEntityToJSONTyped(json, false);
}

export function IntegrationStoreEntityToJSONTyped(value?: IntegrationStoreEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'storeIntegrationId': value['storeIntegrationId'],
    };
}

