/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationAction
 */
export interface IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationAction {
    /**
     * 
     * @type {number}
     * @memberof IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationAction
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationAction
     */
    reason?: string;
    /**
     * 
     * @type {IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationActionOperationEnum}
     * @memberof IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationAction
     */
    operation: IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationActionOperationEnum;
    /**
     * 
     * @type {Date}
     * @memberof IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationAction
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationAction
     */
    expiryDate?: Date;
    /**
     * The identifier of the transaction in the loyalty ledger.
     * @type {string}
     * @memberof IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationAction
     */
    transactionUUID: string;
}


/**
 * @export
 */
export const IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationActionOperationEnum = {
    Addition: 'addition',
    Subtraction: 'subtraction'
} as const;
export type IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationActionOperationEnum = typeof IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationActionOperationEnum[keyof typeof IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationActionOperationEnum];


/**
 * Check if a given object implements the IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationAction interface.
 */
export function instanceOfIntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationAction(value: object): value is IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationAction {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('operation' in value) || value['operation'] === undefined) return false;
    if (!('transactionUUID' in value) || value['transactionUUID'] === undefined) return false;
    return true;
}

export function IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationActionFromJSON(json: any): IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationAction {
    return IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationActionFromJSONTyped(json, false);
}

export function IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationAction {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['Amount'],
        'reason': json['Reason'] == null ? undefined : json['Reason'],
        'operation': json['Operation'],
        'startDate': json['StartDate'] == null ? undefined : (new Date(json['StartDate'])),
        'expiryDate': json['ExpiryDate'] == null ? undefined : (new Date(json['ExpiryDate'])),
        'transactionUUID': json['TransactionUUID'],
    };
}

export function IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationActionToJSON(json: any): IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationAction {
    return IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationActionToJSONTyped(json, false);
}

export function IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationActionToJSONTyped(value?: IntegrationHubEventPayloadLoyaltyProfileBasedPointsChangedNotificationAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Amount': value['amount'],
        'Reason': value['reason'],
        'Operation': value['operation'],
        'StartDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
        'ExpiryDate': value['expiryDate'] == null ? value['expiryDate'] : value['expiryDate'].toISOString(),
        'TransactionUUID': value['transactionUUID'],
    };
}

