/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Effect } from './Effect';
import {
    EffectFromJSON,
    EffectFromJSONTyped,
    EffectToJSON,
    EffectToJSONTyped,
} from './Effect';
import type { CustomerProfile } from './CustomerProfile';
import {
    CustomerProfileFromJSON,
    CustomerProfileFromJSONTyped,
    CustomerProfileToJSON,
    CustomerProfileToJSONTyped,
} from './CustomerProfile';
import type { Loyalty } from './Loyalty';
import {
    LoyaltyFromJSON,
    LoyaltyFromJSONTyped,
    LoyaltyToJSON,
    LoyaltyToJSONTyped,
} from './Loyalty';

/**
 * Contains the result of unlocking a reward for a customer profile or loyalty card.
 * 
 * @export
 * @interface IntegrationUnlockRewardResponse
 */
export interface IntegrationUnlockRewardResponse {
    /**
     * The customer profile that unlocked the reward.
     */
    customerProfile?: CustomerProfile;
    /**
     * The loyalty information of the customer profile or loyalty card that unlocked the reward.
     */
    loyalty?: Loyalty;
    /**
     * The effects generated when evaluating this reward unlock, after the reward's eligibility conditions are met. See [API effects](https://docs.talon.one/docs/dev/integration-api/api-effects).
     */
    effects: Array<Effect>;
}

/**
 * Check if a given object implements the IntegrationUnlockRewardResponse interface.
 */
export function instanceOfIntegrationUnlockRewardResponse(value: object): value is IntegrationUnlockRewardResponse {
    const _v = value as Record<PropertyKey, unknown>;
    if (!('effects' in _v) || _v['effects'] === undefined) return false;
    return true;
}

export function IntegrationUnlockRewardResponseFromJSON(json: any): IntegrationUnlockRewardResponse {
    return IntegrationUnlockRewardResponseFromJSONTyped(json, false);
}

export function IntegrationUnlockRewardResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationUnlockRewardResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'customerProfile': json['customerProfile'] == null ? undefined : CustomerProfileFromJSON(json['customerProfile']),
        'loyalty': json['loyalty'] == null ? undefined : LoyaltyFromJSON(json['loyalty']),
        'effects': (json['effects'] == null ? undefined as any : (json['effects'] as Array<any>).map(EffectFromJSON)),
    };
}

export function IntegrationUnlockRewardResponseToJSON(json: any): IntegrationUnlockRewardResponse {
    return IntegrationUnlockRewardResponseToJSONTyped(json, false);
}

export function IntegrationUnlockRewardResponseToJSONTyped(value?: IntegrationUnlockRewardResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customerProfile': CustomerProfileToJSON(value['customerProfile']),
        'loyalty': LoyaltyToJSON(value['loyalty']),
        'effects': (value['effects'] == null ? undefined : (value['effects'] as Array<any>).map(EffectToJSON)),
    };
}

