/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification
 */
export interface IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification {
    /**
     * 
     * @type {string}
     * @memberof IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification
     */
    profileIntegrationID: string;
    /**
     * 
     * @type {number}
     * @memberof IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification
     */
    loyaltyProgramID: number;
    /**
     * The name of the loyalty program.
     * @type {string}
     * @memberof IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification
     */
    loyaltyProgramName: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification
     */
    subledgerID: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification
     */
    sourceOfEvent: string;
    /**
     * The name of the customer's current tier, or null if the customer was downgraded below all tiers.
     * @type {string}
     * @memberof IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification
     */
    currentTier?: string;
    /**
     * 
     * @type {number}
     * @memberof IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification
     */
    currentPoints: number;
    /**
     * 
     * @type {string}
     * @memberof IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification
     */
    oldTier?: string;
    /**
     * 
     * @type {Date}
     * @memberof IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification
     */
    tierExpirationDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification
     */
    timestampOfTierChange?: Date;
    /**
     * Timestamp when the event was published.
     * @type {Date}
     * @memberof IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification
     */
    publishedAt: Date;
}

/**
 * Check if a given object implements the IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification interface.
 */
export function instanceOfIntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification(value: object): value is IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification {
    if (!('profileIntegrationID' in value) || value['profileIntegrationID'] === undefined) return false;
    if (!('loyaltyProgramID' in value) || value['loyaltyProgramID'] === undefined) return false;
    if (!('loyaltyProgramName' in value) || value['loyaltyProgramName'] === undefined) return false;
    if (!('subledgerID' in value) || value['subledgerID'] === undefined) return false;
    if (!('sourceOfEvent' in value) || value['sourceOfEvent'] === undefined) return false;
    if (!('currentPoints' in value) || value['currentPoints'] === undefined) return false;
    if (!('publishedAt' in value) || value['publishedAt'] === undefined) return false;
    return true;
}

export function IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotificationFromJSON(json: any): IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification {
    return IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotificationFromJSONTyped(json, false);
}

export function IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'profileIntegrationID': json['ProfileIntegrationID'],
        'loyaltyProgramID': json['LoyaltyProgramID'],
        'loyaltyProgramName': json['LoyaltyProgramName'],
        'subledgerID': json['SubledgerID'],
        'sourceOfEvent': json['SourceOfEvent'],
        'currentTier': json['CurrentTier'] == null ? undefined : json['CurrentTier'],
        'currentPoints': json['CurrentPoints'],
        'oldTier': json['OldTier'] == null ? undefined : json['OldTier'],
        'tierExpirationDate': json['TierExpirationDate'] == null ? undefined : (new Date(json['TierExpirationDate'])),
        'timestampOfTierChange': json['TimestampOfTierChange'] == null ? undefined : (new Date(json['TimestampOfTierChange'])),
        'publishedAt': (new Date(json['PublishedAt'])),
    };
}

export function IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotificationToJSON(json: any): IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification {
    return IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotificationToJSONTyped(json, false);
}

export function IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotificationToJSONTyped(value?: IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ProfileIntegrationID': value['profileIntegrationID'],
        'LoyaltyProgramID': value['loyaltyProgramID'],
        'LoyaltyProgramName': value['loyaltyProgramName'],
        'SubledgerID': value['subledgerID'],
        'SourceOfEvent': value['sourceOfEvent'],
        'CurrentTier': value['currentTier'],
        'CurrentPoints': value['currentPoints'],
        'OldTier': value['oldTier'],
        'TierExpirationDate': value['tierExpirationDate'] == null ? value['tierExpirationDate'] : value['tierExpirationDate'].toISOString(),
        'TimestampOfTierChange': value['timestampOfTierChange'] == null ? value['timestampOfTierChange'] : value['timestampOfTierChange'].toISOString(),
        'PublishedAt': value['publishedAt'].toISOString(),
    };
}

