/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoyaltyCardBatchResponse
 */
export interface LoyaltyCardBatchResponse {
    /**
     * Number of loyalty cards in the batch.
     * @type {number}
     * @memberof LoyaltyCardBatchResponse
     */
    numberOfCardsGenerated: number;
    /**
     * ID of the loyalty card batch.
     * @type {string}
     * @memberof LoyaltyCardBatchResponse
     */
    batchId: string;
}

/**
 * Check if a given object implements the LoyaltyCardBatchResponse interface.
 */
export function instanceOfLoyaltyCardBatchResponse(value: object): value is LoyaltyCardBatchResponse {
    if (!('numberOfCardsGenerated' in value) || value['numberOfCardsGenerated'] === undefined) return false;
    if (!('batchId' in value) || value['batchId'] === undefined) return false;
    return true;
}

export function LoyaltyCardBatchResponseFromJSON(json: any): LoyaltyCardBatchResponse {
    return LoyaltyCardBatchResponseFromJSONTyped(json, false);
}

export function LoyaltyCardBatchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoyaltyCardBatchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'numberOfCardsGenerated': json['numberOfCardsGenerated'],
        'batchId': json['batchId'],
    };
}

export function LoyaltyCardBatchResponseToJSON(json: any): LoyaltyCardBatchResponse {
    return LoyaltyCardBatchResponseToJSONTyped(json, false);
}

export function LoyaltyCardBatchResponseToJSONTyped(value?: LoyaltyCardBatchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'numberOfCardsGenerated': value['numberOfCardsGenerated'],
        'batchId': value['batchId'],
    };
}

