/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoyaltyDashboardPointsBreakdown } from './LoyaltyDashboardPointsBreakdown';
import {
    LoyaltyDashboardPointsBreakdownFromJSON,
    LoyaltyDashboardPointsBreakdownFromJSONTyped,
    LoyaltyDashboardPointsBreakdownToJSON,
    LoyaltyDashboardPointsBreakdownToJSONTyped,
} from './LoyaltyDashboardPointsBreakdown';

/**
 * Datapoint for the graphs and cards on a loyalty program dashboard.
 * @export
 * @interface LoyaltyDashboardData
 */
export interface LoyaltyDashboardData {
    /**
     * Date at which data point was collected.
     * @type {Date}
     * @memberof LoyaltyDashboardData
     */
    date: Date;
    /**
     * Total of active points for this loyalty program.
     * @type {number}
     * @memberof LoyaltyDashboardData
     */
    totalActivePoints: number;
    /**
     * Total of pending points for this loyalty program.
     * @type {number}
     * @memberof LoyaltyDashboardData
     */
    totalPendingPoints: number;
    /**
     * Total of spent points for this loyalty program.
     * @type {number}
     * @memberof LoyaltyDashboardData
     */
    totalSpentPoints: number;
    /**
     * Total of expired points for this loyalty program.
     * @type {number}
     * @memberof LoyaltyDashboardData
     */
    totalExpiredPoints: number;
    /**
     * Total of negative points for this loyalty program.
     * @type {number}
     * @memberof LoyaltyDashboardData
     */
    totalNegativePoints: number;
    /**
     * Number of loyalty program members.
     * @type {number}
     * @memberof LoyaltyDashboardData
     */
    totalMembers: number;
    /**
     * Number of members who joined on this day.
     * @type {number}
     * @memberof LoyaltyDashboardData
     */
    newMembers: number;
    /**
     * Points spent on this day.
     * @type {LoyaltyDashboardPointsBreakdown}
     * @memberof LoyaltyDashboardData
     */
    spentPoints: LoyaltyDashboardPointsBreakdown;
    /**
     * Points that were earned on this day.
     * @type {LoyaltyDashboardPointsBreakdown}
     * @memberof LoyaltyDashboardData
     */
    earnedPoints: LoyaltyDashboardPointsBreakdown;
}

/**
 * Check if a given object implements the LoyaltyDashboardData interface.
 */
export function instanceOfLoyaltyDashboardData(value: object): value is LoyaltyDashboardData {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('totalActivePoints' in value) || value['totalActivePoints'] === undefined) return false;
    if (!('totalPendingPoints' in value) || value['totalPendingPoints'] === undefined) return false;
    if (!('totalSpentPoints' in value) || value['totalSpentPoints'] === undefined) return false;
    if (!('totalExpiredPoints' in value) || value['totalExpiredPoints'] === undefined) return false;
    if (!('totalNegativePoints' in value) || value['totalNegativePoints'] === undefined) return false;
    if (!('totalMembers' in value) || value['totalMembers'] === undefined) return false;
    if (!('newMembers' in value) || value['newMembers'] === undefined) return false;
    if (!('spentPoints' in value) || value['spentPoints'] === undefined) return false;
    if (!('earnedPoints' in value) || value['earnedPoints'] === undefined) return false;
    return true;
}

export function LoyaltyDashboardDataFromJSON(json: any): LoyaltyDashboardData {
    return LoyaltyDashboardDataFromJSONTyped(json, false);
}

export function LoyaltyDashboardDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoyaltyDashboardData {
    if (json == null) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'totalActivePoints': json['totalActivePoints'],
        'totalPendingPoints': json['totalPendingPoints'],
        'totalSpentPoints': json['totalSpentPoints'],
        'totalExpiredPoints': json['totalExpiredPoints'],
        'totalNegativePoints': json['totalNegativePoints'],
        'totalMembers': json['totalMembers'],
        'newMembers': json['newMembers'],
        'spentPoints': LoyaltyDashboardPointsBreakdownFromJSON(json['spentPoints']),
        'earnedPoints': LoyaltyDashboardPointsBreakdownFromJSON(json['earnedPoints']),
    };
}

export function LoyaltyDashboardDataToJSON(json: any): LoyaltyDashboardData {
    return LoyaltyDashboardDataToJSONTyped(json, false);
}

export function LoyaltyDashboardDataToJSONTyped(value?: LoyaltyDashboardData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'].toISOString(),
        'totalActivePoints': value['totalActivePoints'],
        'totalPendingPoints': value['totalPendingPoints'],
        'totalSpentPoints': value['totalSpentPoints'],
        'totalExpiredPoints': value['totalExpiredPoints'],
        'totalNegativePoints': value['totalNegativePoints'],
        'totalMembers': value['totalMembers'],
        'newMembers': value['newMembers'],
        'spentPoints': LoyaltyDashboardPointsBreakdownToJSON(value['spentPoints']),
        'earnedPoints': LoyaltyDashboardPointsBreakdownToJSON(value['earnedPoints']),
    };
}

