/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { LedgerInfo } from './LedgerInfo';
import {
    LedgerInfoFromJSON,
    LedgerInfoFromJSONTyped,
    LedgerInfoToJSON,
    LedgerInfoToJSONTyped,
} from './LedgerInfo';

/**
 * Customer-specific information about loyalty points.
 * @export
 * @interface LoyaltyProgramLedgers
 */
export interface LoyaltyProgramLedgers {
    /**
     * The internal ID of loyalty program.
     */
    id: number;
    /**
     * Visible name of loyalty program.
     */
    title: string;
    /**
     * Internal name of loyalty program.
     */
    name: string;
    /**
     * The date on which the customer joined the loyalty program in RFC3339.
     * 
     * **Note**: This is in the loyalty program's time zone.
     * 
     */
    joinDate?: Date;
    /**
     * Information about the main ledger in the loyalty program.
     */
    ledger: LedgerInfo;
    /**
     * A map containing information about each loyalty subledger. Subledgers for which all balances are zero are excluded from the response.
     */
    subLedgers?: { [key: string]: LedgerInfo; };
}

/**
 * Check if a given object implements the LoyaltyProgramLedgers interface.
 */
export function instanceOfLoyaltyProgramLedgers(value: object): value is LoyaltyProgramLedgers {
    const _v = value as Record<PropertyKey, unknown>;
    if (!('id' in _v) || _v['id'] === undefined) return false;
    if (!('title' in _v) || _v['title'] === undefined) return false;
    if (!('name' in _v) || _v['name'] === undefined) return false;
    if (!('ledger' in _v) || _v['ledger'] === undefined) return false;
    return true;
}

export function LoyaltyProgramLedgersFromJSON(json: any): LoyaltyProgramLedgers {
    return LoyaltyProgramLedgersFromJSONTyped(json, false);
}

export function LoyaltyProgramLedgersFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoyaltyProgramLedgers {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'name': json['name'],
        'joinDate': json['joinDate'] == null ? undefined : (parseDateTime(json['joinDate'])),
        'ledger': LedgerInfoFromJSON(json['ledger']),
        'subLedgers': json['subLedgers'] == null ? undefined : (mapValues(json['subLedgers'], LedgerInfoFromJSON)),
    };
}

export function LoyaltyProgramLedgersToJSON(json: any): LoyaltyProgramLedgers {
    return LoyaltyProgramLedgersToJSONTyped(json, false);
}

export function LoyaltyProgramLedgersToJSONTyped(value?: LoyaltyProgramLedgers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'name': value['name'],
        'joinDate': value['joinDate'] == null ? value['joinDate'] : serializeDateTime(value['joinDate']),
        'ledger': LedgerInfoToJSON(value['ledger']),
        'subLedgers': value['subLedgers'] == null ? undefined : (mapValues(value['subLedgers'], LedgerInfoToJSON)),
    };
}

