/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CatalogRule } from './CatalogRule';
import {
    CatalogRuleFromJSON,
    CatalogRuleFromJSONTyped,
    CatalogRuleToJSON,
    CatalogRuleToJSONTyped,
} from './CatalogRule';
import type { CartItemFilterTemplate } from './CartItemFilterTemplate';
import {
    CartItemFilterTemplateFromJSON,
    CartItemFilterTemplateFromJSONTyped,
    CartItemFilterTemplateToJSON,
    CartItemFilterTemplateToJSONTyped,
} from './CartItemFilterTemplate';

/**
 * 
 * @export
 * @interface NewCollectionsCatalog
 */
export interface NewCollectionsCatalog {
    /**
     * The display name for the collection catalog.
     * @type {string}
     * @memberof NewCollectionsCatalog
     */
    title: string;
    /**
     * A longer, more detailed description of the collection catalog.
     * @type {string}
     * @memberof NewCollectionsCatalog
     */
    description?: string;
    /**
     * Category used to group collection catalogs.
     * @type {string}
     * @memberof NewCollectionsCatalog
     */
    category?: NewCollectionsCatalogCategoryEnum;
    /**
     * Array of rules to store in this collection catalog. Rules should only contain title (no description, as description is at the collection catalog level). At least one rule or cart item filter is required.
     * @type {Array<CatalogRule>}
     * @memberof NewCollectionsCatalog
     */
    rules?: Array<CatalogRule>;
    /**
     * Array of cart item filters to store in this collection catalog. If not provided, will be extracted from the rules. Cart item filters should only contain name (no description, as description is at the collection catalog level).
     * @type {Array<CartItemFilterTemplate>}
     * @memberof NewCollectionsCatalog
     */
    cartItemFilters?: Array<CartItemFilterTemplate>;
}


/**
 * @export
 */
export const NewCollectionsCatalogCategoryEnum = {
    Promotions: 'promotions',
    Pricing: 'pricing',
    Loyalty: 'loyalty',
    Custom: 'custom'
} as const;
export type NewCollectionsCatalogCategoryEnum = typeof NewCollectionsCatalogCategoryEnum[keyof typeof NewCollectionsCatalogCategoryEnum];


/**
 * Check if a given object implements the NewCollectionsCatalog interface.
 */
export function instanceOfNewCollectionsCatalog(value: object): value is NewCollectionsCatalog {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function NewCollectionsCatalogFromJSON(json: any): NewCollectionsCatalog {
    return NewCollectionsCatalogFromJSONTyped(json, false);
}

export function NewCollectionsCatalogFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewCollectionsCatalog {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'category': json['category'] == null ? undefined : json['category'],
        'rules': json['rules'] == null ? undefined : ((json['rules'] as Array<any>).map(CatalogRuleFromJSON)),
        'cartItemFilters': json['cartItemFilters'] == null ? undefined : ((json['cartItemFilters'] as Array<any>).map(CartItemFilterTemplateFromJSON)),
    };
}

export function NewCollectionsCatalogToJSON(json: any): NewCollectionsCatalog {
    return NewCollectionsCatalogToJSONTyped(json, false);
}

export function NewCollectionsCatalogToJSONTyped(value?: NewCollectionsCatalog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'category': value['category'],
        'rules': value['rules'] == null ? undefined : ((value['rules'] as Array<any>).map(CatalogRuleToJSON)),
        'cartItemFilters': value['cartItemFilters'] == null ? undefined : ((value['cartItemFilters'] as Array<any>).map(CartItemFilterTemplateToJSON)),
    };
}

