/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Endpoint } from './Endpoint';
import {
    EndpointFromJSON,
    EndpointFromJSONTyped,
    EndpointToJSON,
    EndpointToJSONTyped,
} from './Endpoint';

/**
 * 
 * @export
 * @interface NewManagementKey
 */
export interface NewManagementKey {
    /**
     * Name for management key.
     * @type {string}
     * @memberof NewManagementKey
     */
    name: string;
    /**
     * The date the management key expires.
     * @type {Date}
     * @memberof NewManagementKey
     */
    expiryDate: Date;
    /**
     * The list of endpoints that can be accessed with the key
     * @type {Array<Endpoint>}
     * @memberof NewManagementKey
     */
    endpoints: Array<Endpoint>;
    /**
     * A list of Application IDs that you can access with the management key.
     * An empty or missing list means the management key can be used for all Applications in the account.
     * 
     * @type {Array<number>}
     * @memberof NewManagementKey
     */
    allowedApplicationIds?: Array<number>;
    /**
     * ID of the management key.
     * @type {number}
     * @memberof NewManagementKey
     */
    id: number;
    /**
     * ID of the user who created it.
     * @type {number}
     * @memberof NewManagementKey
     */
    createdBy: number;
    /**
     * ID of account the key is used for.
     * @type {number}
     * @memberof NewManagementKey
     */
    accountID: number;
    /**
     * The date the management key was created.
     * @type {Date}
     * @memberof NewManagementKey
     */
    created: Date;
    /**
     * The management key is disabled (this property is set to `true`) when the user who created the key is disabled or deleted.
     * @type {boolean}
     * @memberof NewManagementKey
     */
    disabled?: boolean;
    /**
     * The last time the management key was used.
     * @type {Date}
     * @memberof NewManagementKey
     */
    lastUsed?: Date;
    /**
     * The management key.
     * @type {string}
     * @memberof NewManagementKey
     */
    key: string;
}

/**
 * Check if a given object implements the NewManagementKey interface.
 */
export function instanceOfNewManagementKey(value: object): value is NewManagementKey {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('expiryDate' in value) || value['expiryDate'] === undefined) return false;
    if (!('endpoints' in value) || value['endpoints'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('accountID' in value) || value['accountID'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    return true;
}

export function NewManagementKeyFromJSON(json: any): NewManagementKey {
    return NewManagementKeyFromJSONTyped(json, false);
}

export function NewManagementKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewManagementKey {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'expiryDate': (new Date(json['expiryDate'])),
        'endpoints': ((json['endpoints'] as Array<any>).map(EndpointFromJSON)),
        'allowedApplicationIds': json['allowedApplicationIds'] == null ? undefined : json['allowedApplicationIds'],
        'id': json['id'],
        'createdBy': json['createdBy'],
        'accountID': json['accountID'],
        'created': (new Date(json['created'])),
        'disabled': json['disabled'] == null ? undefined : json['disabled'],
        'lastUsed': json['lastUsed'] == null ? undefined : (new Date(json['lastUsed'])),
        'key': json['key'],
    };
}

export function NewManagementKeyToJSON(json: any): NewManagementKey {
    return NewManagementKeyToJSONTyped(json, false);
}

export function NewManagementKeyToJSONTyped(value?: NewManagementKey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'expiryDate': value['expiryDate'].toISOString(),
        'endpoints': ((value['endpoints'] as Array<any>).map(EndpointToJSON)),
        'allowedApplicationIds': value['allowedApplicationIds'],
        'id': value['id'],
        'createdBy': value['createdBy'],
        'accountID': value['accountID'],
        'created': value['created'].toISOString(),
        'disabled': value['disabled'],
        'lastUsed': value['lastUsed'] == null ? value['lastUsed'] : value['lastUsed'].toISOString(),
        'key': value['key'],
    };
}

