/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewRole
 */
export interface NewRole {
    /**
     * Name of the role.
     */
    name: string;
    /**
     * Description of the role.
     */
    description?: string;
    /**
     * The `Access Control List` json defining the role of the user. This represents the access control on the user level.
     */
    acl: string;
    /**
     * An array of user identifiers.
     */
    members: Array<number>;
}

/**
 * Check if a given object implements the NewRole interface.
 */
export function instanceOfNewRole(value: object): value is NewRole {
    const _v = value as Record<PropertyKey, unknown>;
    if (!('name' in _v) || _v['name'] === undefined) return false;
    if (!('acl' in _v) || _v['acl'] === undefined) return false;
    if (!('members' in _v) || _v['members'] === undefined) return false;
    return true;
}

export function NewRoleFromJSON(json: any): NewRole {
    return NewRoleFromJSONTyped(json, false);
}

export function NewRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewRole {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'acl': json['acl'],
        'members': json['members'],
    };
}

export function NewRoleToJSON(json: any): NewRole {
    return NewRoleToJSONTyped(json, false);
}

export function NewRoleToJSONTyped(value?: NewRole | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'acl': value['acl'],
        'members': value['members'],
    };
}

