/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewSamlConnection
 */
export interface NewSamlConnection {
    /**
     * The ID of the account that owns this entity.
     * @type {number}
     * @memberof NewSamlConnection
     */
    accountId: number;
    /**
     * ID of the SAML service.
     * @type {string}
     * @memberof NewSamlConnection
     */
    name: string;
    /**
     * Determines if this SAML connection active.
     * @type {boolean}
     * @memberof NewSamlConnection
     */
    enabled: boolean;
    /**
     * Identity Provider Entity ID.
     * @type {string}
     * @memberof NewSamlConnection
     */
    issuer: string;
    /**
     * Single Sign-On URL.
     * @type {string}
     * @memberof NewSamlConnection
     */
    signOnURL: string;
    /**
     * Single Sign-Out URL.
     * @type {string}
     * @memberof NewSamlConnection
     */
    signOutURL?: string;
    /**
     * Metadata URL.
     * @type {string}
     * @memberof NewSamlConnection
     */
    metadataURL?: string;
    /**
     * The application-defined unique identifier that is the intended audience of the SAML assertion.
     * This is most often the SP Entity ID of your application. When not specified, the ACS URL will be used.
     * 
     * @type {string}
     * @memberof NewSamlConnection
     */
    audienceURI?: string;
    /**
     * X.509 Certificate.
     * @type {string}
     * @memberof NewSamlConnection
     */
    x509certificate: string;
}

/**
 * Check if a given object implements the NewSamlConnection interface.
 */
export function instanceOfNewSamlConnection(value: object): value is NewSamlConnection {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('issuer' in value) || value['issuer'] === undefined) return false;
    if (!('signOnURL' in value) || value['signOnURL'] === undefined) return false;
    if (!('x509certificate' in value) || value['x509certificate'] === undefined) return false;
    return true;
}

export function NewSamlConnectionFromJSON(json: any): NewSamlConnection {
    return NewSamlConnectionFromJSONTyped(json, false);
}

export function NewSamlConnectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewSamlConnection {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'name': json['name'],
        'enabled': json['enabled'],
        'issuer': json['issuer'],
        'signOnURL': json['signOnURL'],
        'signOutURL': json['signOutURL'] == null ? undefined : json['signOutURL'],
        'metadataURL': json['metadataURL'] == null ? undefined : json['metadataURL'],
        'audienceURI': json['audienceURI'] == null ? undefined : json['audienceURI'],
        'x509certificate': json['x509certificate'],
    };
}

export function NewSamlConnectionToJSON(json: any): NewSamlConnection {
    return NewSamlConnectionToJSONTyped(json, false);
}

export function NewSamlConnectionToJSONTyped(value?: NewSamlConnection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'name': value['name'],
        'enabled': value['enabled'],
        'issuer': value['issuer'],
        'signOnURL': value['signOnURL'],
        'signOutURL': value['signOutURL'],
        'metadataURL': value['metadataURL'],
        'audienceURI': value['audienceURI'],
        'x509certificate': value['x509certificate'],
    };
}

