/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TemplateArgDef } from './TemplateArgDef';
import {
    TemplateArgDefFromJSON,
    TemplateArgDefFromJSONTyped,
    TemplateArgDefToJSON,
    TemplateArgDefToJSONTyped,
} from './TemplateArgDef';

/**
 * 
 * @export
 * @interface NewTemplateDef
 */
export interface NewTemplateDef {
    /**
     * Campaigner-friendly name for the template that will be shown in the rule editor.
     * @type {string}
     * @memberof NewTemplateDef
     */
    title: string;
    /**
     * A short description of the template that will be shown in the rule editor.
     * @type {string}
     * @memberof NewTemplateDef
     */
    description?: string;
    /**
     * Extended help text for the template.
     * @type {string}
     * @memberof NewTemplateDef
     */
    help?: string;
    /**
     * Used for grouping templates in the rule editor sidebar.
     * @type {string}
     * @memberof NewTemplateDef
     */
    category: string;
    /**
     * A Talang expression that contains variable bindings referring to args.
     * @type {Array<any>}
     * @memberof NewTemplateDef
     */
    expr: Array<any>;
    /**
     * An array of argument definitions.
     * @type {Array<TemplateArgDef>}
     * @memberof NewTemplateDef
     */
    args: Array<TemplateArgDef>;
    /**
     * A flag to control exposure in Rule Builder.
     * @type {boolean}
     * @memberof NewTemplateDef
     */
    expose?: boolean;
}

/**
 * Check if a given object implements the NewTemplateDef interface.
 */
export function instanceOfNewTemplateDef(value: object): value is NewTemplateDef {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('expr' in value) || value['expr'] === undefined) return false;
    if (!('args' in value) || value['args'] === undefined) return false;
    return true;
}

export function NewTemplateDefFromJSON(json: any): NewTemplateDef {
    return NewTemplateDefFromJSONTyped(json, false);
}

export function NewTemplateDefFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewTemplateDef {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'help': json['help'] == null ? undefined : json['help'],
        'category': json['category'],
        'expr': json['expr'],
        'args': ((json['args'] as Array<any>).map(TemplateArgDefFromJSON)),
        'expose': json['expose'] == null ? undefined : json['expose'],
    };
}

export function NewTemplateDefToJSON(json: any): NewTemplateDef {
    return NewTemplateDefToJSONTyped(json, false);
}

export function NewTemplateDefToJSONTyped(value?: NewTemplateDef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'help': value['help'],
        'category': value['category'],
        'expr': value['expr'],
        'args': ((value['args'] as Array<any>).map(TemplateArgDefToJSON)),
        'expose': value['expose'],
    };
}

