/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OutgoingIntegrationType } from './OutgoingIntegrationType';
import {
    OutgoingIntegrationTypeFromJSON,
    OutgoingIntegrationTypeFromJSONTyped,
    OutgoingIntegrationTypeToJSON,
    OutgoingIntegrationTypeToJSONTyped,
} from './OutgoingIntegrationType';

/**
 * 
 * @export
 * @interface OutgoingIntegrationTypes
 */
export interface OutgoingIntegrationTypes {
    /**
     * List of outgoing integrations.
     * @type {Array<OutgoingIntegrationType>}
     * @memberof OutgoingIntegrationTypes
     */
    data?: Array<OutgoingIntegrationType>;
}

/**
 * Check if a given object implements the OutgoingIntegrationTypes interface.
 */
export function instanceOfOutgoingIntegrationTypes(value: object): value is OutgoingIntegrationTypes {
    return true;
}

export function OutgoingIntegrationTypesFromJSON(json: any): OutgoingIntegrationTypes {
    return OutgoingIntegrationTypesFromJSONTyped(json, false);
}

export function OutgoingIntegrationTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutgoingIntegrationTypes {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(OutgoingIntegrationTypeFromJSON)),
    };
}

export function OutgoingIntegrationTypesToJSON(json: any): OutgoingIntegrationTypes {
    return OutgoingIntegrationTypesToJSONTyped(json, false);
}

export function OutgoingIntegrationTypesToJSONTyped(value?: OutgoingIntegrationTypes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(OutgoingIntegrationTypeToJSON)),
    };
}

