/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OutgoingIntegrationTemplateWithConfigurationDetails
 */
export interface OutgoingIntegrationTemplateWithConfigurationDetails {
    /**
     * Unique ID for this entity.
     * @type {number}
     * @memberof OutgoingIntegrationTemplateWithConfigurationDetails
     */
    id: number;
    /**
     * Unique ID of outgoing integration type.
     * @type {number}
     * @memberof OutgoingIntegrationTemplateWithConfigurationDetails
     */
    integrationType: number;
    /**
     * The title of the integration template.
     * @type {string}
     * @memberof OutgoingIntegrationTemplateWithConfigurationDetails
     */
    title: string;
    /**
     * The description of the specific outgoing integration template.
     * @type {string}
     * @memberof OutgoingIntegrationTemplateWithConfigurationDetails
     */
    description: string;
    /**
     * The API payload (supports templating using parameters) for this integration template.
     * @type {string}
     * @memberof OutgoingIntegrationTemplateWithConfigurationDetails
     */
    payload: string;
    /**
     * API method for this webhook.
     * @type {string}
     * @memberof OutgoingIntegrationTemplateWithConfigurationDetails
     */
    method: OutgoingIntegrationTemplateWithConfigurationDetailsMethodEnum;
    /**
     * The relative URL corresponding to each integration template.
     * @type {string}
     * @memberof OutgoingIntegrationTemplateWithConfigurationDetails
     */
    relativeUrl: string;
    /**
     * The list of HTTP headers for this integration template.
     * @type {Array<string>}
     * @memberof OutgoingIntegrationTemplateWithConfigurationDetails
     */
    headers: Array<string>;
    /**
     * The outgoing integration policy specific to each integration type.
     * @type {object}
     * @memberof OutgoingIntegrationTemplateWithConfigurationDetails
     */
    policy: object;
}


/**
 * @export
 */
export const OutgoingIntegrationTemplateWithConfigurationDetailsMethodEnum = {
    Post: 'POST',
    Put: 'PUT',
    Get: 'GET',
    Delete: 'DELETE',
    Patch: 'PATCH'
} as const;
export type OutgoingIntegrationTemplateWithConfigurationDetailsMethodEnum = typeof OutgoingIntegrationTemplateWithConfigurationDetailsMethodEnum[keyof typeof OutgoingIntegrationTemplateWithConfigurationDetailsMethodEnum];


/**
 * Check if a given object implements the OutgoingIntegrationTemplateWithConfigurationDetails interface.
 */
export function instanceOfOutgoingIntegrationTemplateWithConfigurationDetails(value: object): value is OutgoingIntegrationTemplateWithConfigurationDetails {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('integrationType' in value) || value['integrationType'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('method' in value) || value['method'] === undefined) return false;
    if (!('relativeUrl' in value) || value['relativeUrl'] === undefined) return false;
    if (!('headers' in value) || value['headers'] === undefined) return false;
    if (!('policy' in value) || value['policy'] === undefined) return false;
    return true;
}

export function OutgoingIntegrationTemplateWithConfigurationDetailsFromJSON(json: any): OutgoingIntegrationTemplateWithConfigurationDetails {
    return OutgoingIntegrationTemplateWithConfigurationDetailsFromJSONTyped(json, false);
}

export function OutgoingIntegrationTemplateWithConfigurationDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutgoingIntegrationTemplateWithConfigurationDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'integrationType': json['integrationType'],
        'title': json['title'],
        'description': json['description'],
        'payload': json['payload'],
        'method': json['method'],
        'relativeUrl': json['relativeUrl'],
        'headers': json['headers'],
        'policy': json['policy'],
    };
}

export function OutgoingIntegrationTemplateWithConfigurationDetailsToJSON(json: any): OutgoingIntegrationTemplateWithConfigurationDetails {
    return OutgoingIntegrationTemplateWithConfigurationDetailsToJSONTyped(json, false);
}

export function OutgoingIntegrationTemplateWithConfigurationDetailsToJSONTyped(value?: OutgoingIntegrationTemplateWithConfigurationDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'integrationType': value['integrationType'],
        'title': value['title'],
        'description': value['description'],
        'payload': value['payload'],
        'method': value['method'],
        'relativeUrl': value['relativeUrl'],
        'headers': value['headers'],
        'policy': value['policy'],
    };
}

