/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectedTier
 */
export interface ProjectedTier {
    /**
     * The active points of the customer when their current tier expires.
     * @type {number}
     * @memberof ProjectedTier
     */
    projectedActivePoints: number;
    /**
     * The number of points the customer needs to stay in the current tier.
     * 
     * **Note**: This is included in the response when the customer is projected to be downgraded.
     * 
     * @type {number}
     * @memberof ProjectedTier
     */
    stayInTierPoints?: number;
    /**
     * The name of the tier the user will enter once their current tier expires.
     * @type {string}
     * @memberof ProjectedTier
     */
    projectedTierName?: string;
}

/**
 * Check if a given object implements the ProjectedTier interface.
 */
export function instanceOfProjectedTier(value: object): value is ProjectedTier {
    if (!('projectedActivePoints' in value) || value['projectedActivePoints'] === undefined) return false;
    return true;
}

export function ProjectedTierFromJSON(json: any): ProjectedTier {
    return ProjectedTierFromJSONTyped(json, false);
}

export function ProjectedTierFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectedTier {
    if (json == null) {
        return json;
    }
    return {
        
        'projectedActivePoints': json['projectedActivePoints'],
        'stayInTierPoints': json['stayInTierPoints'] == null ? undefined : json['stayInTierPoints'],
        'projectedTierName': json['projectedTierName'] == null ? undefined : json['projectedTierName'],
    };
}

export function ProjectedTierToJSON(json: any): ProjectedTier {
    return ProjectedTierToJSONTyped(json, false);
}

export function ProjectedTierToJSONTyped(value?: ProjectedTier | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'projectedActivePoints': value['projectedActivePoints'],
        'stayInTierPoints': value['stayInTierPoints'],
        'projectedTierName': value['projectedTierName'],
    };
}

