/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AwardGiveawayBlock } from './AwardGiveawayBlock';
import {
    instanceOfAwardGiveawayBlock,
    AwardGiveawayBlockFromJSON,
    AwardGiveawayBlockFromJSONTyped,
    AwardGiveawayBlockToJSON,
} from './AwardGiveawayBlock';
import type { AwardItemBlock } from './AwardItemBlock';
import {
    instanceOfAwardItemBlock,
    AwardItemBlockFromJSON,
    AwardItemBlockFromJSONTyped,
    AwardItemBlockToJSON,
} from './AwardItemBlock';
import type { CheckAudienceBlock } from './CheckAudienceBlock';
import {
    instanceOfCheckAudienceBlock,
    CheckAudienceBlockFromJSON,
    CheckAudienceBlockFromJSONTyped,
    CheckAudienceBlockToJSON,
} from './CheckAudienceBlock';
import type { CheckCouponBlock } from './CheckCouponBlock';
import {
    instanceOfCheckCouponBlock,
    CheckCouponBlockFromJSON,
    CheckCouponBlockFromJSONTyped,
    CheckCouponBlockToJSON,
} from './CheckCouponBlock';
import type { CheckReferralBlock } from './CheckReferralBlock';
import {
    instanceOfCheckReferralBlock,
    CheckReferralBlockFromJSON,
    CheckReferralBlockFromJSONTyped,
    CheckReferralBlockToJSON,
} from './CheckReferralBlock';
import type { PassthroughBlock } from './PassthroughBlock';
import {
    instanceOfPassthroughBlock,
    PassthroughBlockFromJSON,
    PassthroughBlockFromJSONTyped,
    PassthroughBlockToJSON,
} from './PassthroughBlock';
import type { PromotionCheckAttributeBlock } from './PromotionCheckAttributeBlock';
import {
    instanceOfPromotionCheckAttributeBlock,
    PromotionCheckAttributeBlockFromJSON,
    PromotionCheckAttributeBlockFromJSONTyped,
    PromotionCheckAttributeBlockToJSON,
} from './PromotionCheckAttributeBlock';
import type { PromotionGroupBlock } from './PromotionGroupBlock';
import {
    instanceOfPromotionGroupBlock,
    PromotionGroupBlockFromJSON,
    PromotionGroupBlockFromJSONTyped,
    PromotionGroupBlockToJSON,
} from './PromotionGroupBlock';
import type { ShowNotificationBlock } from './ShowNotificationBlock';
import {
    instanceOfShowNotificationBlock,
    ShowNotificationBlockFromJSON,
    ShowNotificationBlockFromJSONTyped,
    ShowNotificationBlockToJSON,
} from './ShowNotificationBlock';
import type { UpdateAchievementProgressBlock } from './UpdateAchievementProgressBlock';
import {
    instanceOfUpdateAchievementProgressBlock,
    UpdateAchievementProgressBlockFromJSON,
    UpdateAchievementProgressBlockFromJSONTyped,
    UpdateAchievementProgressBlockToJSON,
} from './UpdateAchievementProgressBlock';
import type { UpdateAttributeValueBlock } from './UpdateAttributeValueBlock';
import {
    instanceOfUpdateAttributeValueBlock,
    UpdateAttributeValueBlockFromJSON,
    UpdateAttributeValueBlockFromJSONTyped,
    UpdateAttributeValueBlockToJSON,
} from './UpdateAttributeValueBlock';
import type { UpdateAudienceMembershipBlock } from './UpdateAudienceMembershipBlock';
import {
    instanceOfUpdateAudienceMembershipBlock,
    UpdateAudienceMembershipBlockFromJSON,
    UpdateAudienceMembershipBlockFromJSONTyped,
    UpdateAudienceMembershipBlockToJSON,
} from './UpdateAudienceMembershipBlock';

/**
 * @type PromotionBlock
 * Describes a part of the logic of the rule.
 * @export
 */
export type PromotionBlock = { type: 'awardGiveaway' } & AwardGiveawayBlock | { type: 'awardItem' } & AwardItemBlock | { type: 'checkAttribute' } & PromotionCheckAttributeBlock | { type: 'checkAudience' } & CheckAudienceBlock | { type: 'checkCoupon' } & CheckCouponBlock | { type: 'checkReferral' } & CheckReferralBlock | { type: 'group' } & PromotionGroupBlock | { type: 'passthrough' } & PassthroughBlock | { type: 'showNotification' } & ShowNotificationBlock | { type: 'updateAchievementProgress' } & UpdateAchievementProgressBlock | { type: 'updateAttributeValue' } & UpdateAttributeValueBlock | { type: 'updateAudienceMembership' } & UpdateAudienceMembershipBlock;

export function PromotionBlockFromJSON(json: any): PromotionBlock {
    return PromotionBlockFromJSONTyped(json, false);
}

export function PromotionBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromotionBlock {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'awardGiveaway':
            return Object.assign({}, AwardGiveawayBlockFromJSONTyped(json, true), { type: 'awardGiveaway' } as const);
        case 'awardItem':
            return Object.assign({}, AwardItemBlockFromJSONTyped(json, true), { type: 'awardItem' } as const);
        case 'checkAttribute':
            return Object.assign({}, PromotionCheckAttributeBlockFromJSONTyped(json, true), { type: 'checkAttribute' } as const);
        case 'checkAudience':
            return Object.assign({}, CheckAudienceBlockFromJSONTyped(json, true), { type: 'checkAudience' } as const);
        case 'checkCoupon':
            return Object.assign({}, CheckCouponBlockFromJSONTyped(json, true), { type: 'checkCoupon' } as const);
        case 'checkReferral':
            return Object.assign({}, CheckReferralBlockFromJSONTyped(json, true), { type: 'checkReferral' } as const);
        case 'group':
            return Object.assign({}, PromotionGroupBlockFromJSONTyped(json, true), { type: 'group' } as const);
        case 'passthrough':
            return Object.assign({}, PassthroughBlockFromJSONTyped(json, true), { type: 'passthrough' } as const);
        case 'showNotification':
            return Object.assign({}, ShowNotificationBlockFromJSONTyped(json, true), { type: 'showNotification' } as const);
        case 'updateAchievementProgress':
            return Object.assign({}, UpdateAchievementProgressBlockFromJSONTyped(json, true), { type: 'updateAchievementProgress' } as const);
        case 'updateAttributeValue':
            return Object.assign({}, UpdateAttributeValueBlockFromJSONTyped(json, true), { type: 'updateAttributeValue' } as const);
        case 'updateAudienceMembership':
            return Object.assign({}, UpdateAudienceMembershipBlockFromJSONTyped(json, true), { type: 'updateAudienceMembership' } as const);
        default:
            return json;
    }
}

export function PromotionBlockToJSON(json: any): any {
    return PromotionBlockToJSONTyped(json, false);
}

export function PromotionBlockToJSONTyped(value?: PromotionBlock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'awardGiveaway':
            return Object.assign({}, AwardGiveawayBlockToJSON(value), { 'type': 'awardGiveaway' } as const);
        case 'awardItem':
            return Object.assign({}, AwardItemBlockToJSON(value), { 'type': 'awardItem' } as const);
        case 'checkAttribute':
            return Object.assign({}, PromotionCheckAttributeBlockToJSON(value), { 'type': 'checkAttribute' } as const);
        case 'checkAudience':
            return Object.assign({}, CheckAudienceBlockToJSON(value), { 'type': 'checkAudience' } as const);
        case 'checkCoupon':
            return Object.assign({}, CheckCouponBlockToJSON(value), { 'type': 'checkCoupon' } as const);
        case 'checkReferral':
            return Object.assign({}, CheckReferralBlockToJSON(value), { 'type': 'checkReferral' } as const);
        case 'group':
            return Object.assign({}, PromotionGroupBlockToJSON(value), { 'type': 'group' } as const);
        case 'passthrough':
            return Object.assign({}, PassthroughBlockToJSON(value), { 'type': 'passthrough' } as const);
        case 'showNotification':
            return Object.assign({}, ShowNotificationBlockToJSON(value), { 'type': 'showNotification' } as const);
        case 'updateAchievementProgress':
            return Object.assign({}, UpdateAchievementProgressBlockToJSON(value), { 'type': 'updateAchievementProgress' } as const);
        case 'updateAttributeValue':
            return Object.assign({}, UpdateAttributeValueBlockToJSON(value), { 'type': 'updateAttributeValue' } as const);
        case 'updateAudienceMembership':
            return Object.assign({}, UpdateAudienceMembershipBlockToJSON(value), { 'type': 'updateAudienceMembership' } as const);
        default:
            return value;
    }
}

