/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { type AwardDiscountBlock, AwardDiscountBlockFromJSONTyped, AwardDiscountBlockToJSON } from './AwardDiscountBlock';
import { type AwardGiveawayBlock, AwardGiveawayBlockFromJSONTyped, AwardGiveawayBlockToJSON } from './AwardGiveawayBlock';
import { type AwardItemBlock, AwardItemBlockFromJSONTyped, AwardItemBlockToJSON } from './AwardItemBlock';
import { type CheckAchievementBlock, CheckAchievementBlockFromJSONTyped, CheckAchievementBlockToJSON } from './CheckAchievementBlock';
import { type PromotionCheckAttributeBlock, PromotionCheckAttributeBlockFromJSONTyped, PromotionCheckAttributeBlockToJSON } from './PromotionCheckAttributeBlock';
import { type CheckAudienceBlock, CheckAudienceBlockFromJSONTyped, CheckAudienceBlockToJSON } from './CheckAudienceBlock';
import { type CheckBudgetBlock, CheckBudgetBlockFromJSONTyped, CheckBudgetBlockToJSON } from './CheckBudgetBlock';
import { type CheckCouponBlock, CheckCouponBlockFromJSONTyped, CheckCouponBlockToJSON } from './CheckCouponBlock';
import { type CheckEventBlock, CheckEventBlockFromJSONTyped, CheckEventBlockToJSON } from './CheckEventBlock';
import { type CheckReferralBlock, CheckReferralBlockFromJSONTyped, CheckReferralBlockToJSON } from './CheckReferralBlock';
import { type CreateCouponBlock, CreateCouponBlockFromJSONTyped, CreateCouponBlockToJSON } from './CreateCouponBlock';
import { type CreateReferralBlock, CreateReferralBlockFromJSONTyped, CreateReferralBlockToJSON } from './CreateReferralBlock';
import { type PromotionGroupBlock, PromotionGroupBlockFromJSONTyped, PromotionGroupBlockToJSON } from './PromotionGroupBlock';
import { type PassthroughBlock, PassthroughBlockFromJSONTyped, PassthroughBlockToJSON } from './PassthroughBlock';
import { type ReserveCouponBlock, ReserveCouponBlockFromJSONTyped, ReserveCouponBlockToJSON } from './ReserveCouponBlock';
import { type ShowNotificationBlock, ShowNotificationBlockFromJSONTyped, ShowNotificationBlockToJSON } from './ShowNotificationBlock';
import { type TriggerCustomEffectBlock, TriggerCustomEffectBlockFromJSONTyped, TriggerCustomEffectBlockToJSON } from './TriggerCustomEffectBlock';
import { type TriggerWebhookBlock, TriggerWebhookBlockFromJSONTyped, TriggerWebhookBlockToJSON } from './TriggerWebhookBlock';
import { type UpdateAchievementProgressBlock, UpdateAchievementProgressBlockFromJSONTyped, UpdateAchievementProgressBlockToJSON } from './UpdateAchievementProgressBlock';
import { type UpdateAttributeValueBlock, UpdateAttributeValueBlockFromJSONTyped, UpdateAttributeValueBlockToJSON } from './UpdateAttributeValueBlock';
import { type UpdateAudienceMembershipBlock, UpdateAudienceMembershipBlockFromJSONTyped, UpdateAudienceMembershipBlockToJSON } from './UpdateAudienceMembershipBlock';

/**
 * @type PromotionBlock
 * Describes a part of the logic of the rule.
 * @export
 */
export type PromotionBlock = { type: 'awardDiscount' } & AwardDiscountBlock | { type: 'awardGiveaway' } & AwardGiveawayBlock | { type: 'awardItem' } & AwardItemBlock | { type: 'checkAchievement' } & CheckAchievementBlock | { type: 'checkAttribute' } & PromotionCheckAttributeBlock | { type: 'checkAudience' } & CheckAudienceBlock | { type: 'checkBudget' } & CheckBudgetBlock | { type: 'checkCoupon' } & CheckCouponBlock | { type: 'checkEvent' } & CheckEventBlock | { type: 'checkReferral' } & CheckReferralBlock | { type: 'createCoupon' } & CreateCouponBlock | { type: 'createReferral' } & CreateReferralBlock | { type: 'group' } & PromotionGroupBlock | { type: 'passthrough' } & PassthroughBlock | { type: 'reserveCoupon' } & ReserveCouponBlock | { type: 'showNotification' } & ShowNotificationBlock | { type: 'triggerCustomEffect' } & TriggerCustomEffectBlock | { type: 'triggerWebhook' } & TriggerWebhookBlock | { type: 'updateAchievementProgress' } & UpdateAchievementProgressBlock | { type: 'updateAttributeValue' } & UpdateAttributeValueBlock | { type: 'updateAudienceMembership' } & UpdateAudienceMembershipBlock;
/**
 * Check if a given object implements the PromotionBlock interface.
 */
export function instanceOfPromotionBlock(value: any): value is PromotionBlock {
    const _v = value as Record<PropertyKey, unknown>;
    switch (_v['type']) {
        case 'awardDiscount':
        case 'awardGiveaway':
        case 'awardItem':
        case 'checkAchievement':
        case 'checkAttribute':
        case 'checkAudience':
        case 'checkBudget':
        case 'checkCoupon':
        case 'checkEvent':
        case 'checkReferral':
        case 'createCoupon':
        case 'createReferral':
        case 'group':
        case 'passthrough':
        case 'reserveCoupon':
        case 'showNotification':
        case 'triggerCustomEffect':
        case 'triggerWebhook':
        case 'updateAchievementProgress':
        case 'updateAttributeValue':
        case 'updateAudienceMembership':
            return true;
        default:
            return false;
    }
}

export function PromotionBlockFromJSON(json: any): PromotionBlock {
    return PromotionBlockFromJSONTyped(json, false);
}

export function PromotionBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromotionBlock {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'awardDiscount':
            return Object.assign({}, AwardDiscountBlockFromJSONTyped(json, true), { type: 'awardDiscount' } as const);
        case 'awardGiveaway':
            return Object.assign({}, AwardGiveawayBlockFromJSONTyped(json, true), { type: 'awardGiveaway' } as const);
        case 'awardItem':
            return Object.assign({}, AwardItemBlockFromJSONTyped(json, true), { type: 'awardItem' } as const);
        case 'checkAchievement':
            return Object.assign({}, CheckAchievementBlockFromJSONTyped(json, true), { type: 'checkAchievement' } as const);
        case 'checkAttribute':
            return Object.assign({}, PromotionCheckAttributeBlockFromJSONTyped(json, true), { type: 'checkAttribute' } as const);
        case 'checkAudience':
            return Object.assign({}, CheckAudienceBlockFromJSONTyped(json, true), { type: 'checkAudience' } as const);
        case 'checkBudget':
            return Object.assign({}, CheckBudgetBlockFromJSONTyped(json, true), { type: 'checkBudget' } as const);
        case 'checkCoupon':
            return Object.assign({}, CheckCouponBlockFromJSONTyped(json, true), { type: 'checkCoupon' } as const);
        case 'checkEvent':
            return Object.assign({}, CheckEventBlockFromJSONTyped(json, true), { type: 'checkEvent' } as const);
        case 'checkReferral':
            return Object.assign({}, CheckReferralBlockFromJSONTyped(json, true), { type: 'checkReferral' } as const);
        case 'createCoupon':
            return Object.assign({}, CreateCouponBlockFromJSONTyped(json, true), { type: 'createCoupon' } as const);
        case 'createReferral':
            return Object.assign({}, CreateReferralBlockFromJSONTyped(json, true), { type: 'createReferral' } as const);
        case 'group':
            return Object.assign({}, PromotionGroupBlockFromJSONTyped(json, true), { type: 'group' } as const);
        case 'passthrough':
            return Object.assign({}, PassthroughBlockFromJSONTyped(json, true), { type: 'passthrough' } as const);
        case 'reserveCoupon':
            return Object.assign({}, ReserveCouponBlockFromJSONTyped(json, true), { type: 'reserveCoupon' } as const);
        case 'showNotification':
            return Object.assign({}, ShowNotificationBlockFromJSONTyped(json, true), { type: 'showNotification' } as const);
        case 'triggerCustomEffect':
            return Object.assign({}, TriggerCustomEffectBlockFromJSONTyped(json, true), { type: 'triggerCustomEffect' } as const);
        case 'triggerWebhook':
            return Object.assign({}, TriggerWebhookBlockFromJSONTyped(json, true), { type: 'triggerWebhook' } as const);
        case 'updateAchievementProgress':
            return Object.assign({}, UpdateAchievementProgressBlockFromJSONTyped(json, true), { type: 'updateAchievementProgress' } as const);
        case 'updateAttributeValue':
            return Object.assign({}, UpdateAttributeValueBlockFromJSONTyped(json, true), { type: 'updateAttributeValue' } as const);
        case 'updateAudienceMembership':
            return Object.assign({}, UpdateAudienceMembershipBlockFromJSONTyped(json, true), { type: 'updateAudienceMembership' } as const);
        default:
            return json;
    }
}

export function PromotionBlockToJSON(json: any): any {
    return PromotionBlockToJSONTyped(json, false);
}

export function PromotionBlockToJSONTyped(value?: PromotionBlock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'awardDiscount':
            return Object.assign({}, AwardDiscountBlockToJSON(value), { 'type': 'awardDiscount' } as const);
        case 'awardGiveaway':
            return Object.assign({}, AwardGiveawayBlockToJSON(value), { 'type': 'awardGiveaway' } as const);
        case 'awardItem':
            return Object.assign({}, AwardItemBlockToJSON(value), { 'type': 'awardItem' } as const);
        case 'checkAchievement':
            return Object.assign({}, CheckAchievementBlockToJSON(value), { 'type': 'checkAchievement' } as const);
        case 'checkAttribute':
            return Object.assign({}, PromotionCheckAttributeBlockToJSON(value), { 'type': 'checkAttribute' } as const);
        case 'checkAudience':
            return Object.assign({}, CheckAudienceBlockToJSON(value), { 'type': 'checkAudience' } as const);
        case 'checkBudget':
            return Object.assign({}, CheckBudgetBlockToJSON(value), { 'type': 'checkBudget' } as const);
        case 'checkCoupon':
            return Object.assign({}, CheckCouponBlockToJSON(value), { 'type': 'checkCoupon' } as const);
        case 'checkEvent':
            return Object.assign({}, CheckEventBlockToJSON(value), { 'type': 'checkEvent' } as const);
        case 'checkReferral':
            return Object.assign({}, CheckReferralBlockToJSON(value), { 'type': 'checkReferral' } as const);
        case 'createCoupon':
            return Object.assign({}, CreateCouponBlockToJSON(value), { 'type': 'createCoupon' } as const);
        case 'createReferral':
            return Object.assign({}, CreateReferralBlockToJSON(value), { 'type': 'createReferral' } as const);
        case 'group':
            return Object.assign({}, PromotionGroupBlockToJSON(value), { 'type': 'group' } as const);
        case 'passthrough':
            return Object.assign({}, PassthroughBlockToJSON(value), { 'type': 'passthrough' } as const);
        case 'reserveCoupon':
            return Object.assign({}, ReserveCouponBlockToJSON(value), { 'type': 'reserveCoupon' } as const);
        case 'showNotification':
            return Object.assign({}, ShowNotificationBlockToJSON(value), { 'type': 'showNotification' } as const);
        case 'triggerCustomEffect':
            return Object.assign({}, TriggerCustomEffectBlockToJSON(value), { 'type': 'triggerCustomEffect' } as const);
        case 'triggerWebhook':
            return Object.assign({}, TriggerWebhookBlockToJSON(value), { 'type': 'triggerWebhook' } as const);
        case 'updateAchievementProgress':
            return Object.assign({}, UpdateAchievementProgressBlockToJSON(value), { 'type': 'updateAchievementProgress' } as const);
        case 'updateAttributeValue':
            return Object.assign({}, UpdateAttributeValueBlockToJSON(value), { 'type': 'updateAttributeValue' } as const);
        case 'updateAudienceMembership':
            return Object.assign({}, UpdateAudienceMembershipBlockToJSON(value), { 'type': 'updateAudienceMembership' } as const);
        default:
            return value;
    }
}

