/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RedeemableCoupon
 */
export interface RedeemableCoupon {
    /**
     * The internal ID of the coupon.
     */
    couponId: number;
    /**
     * The coupon code.
     */
    couponCode: string;
    /**
     * The number of times the coupon has been successfully redeemed.
     */
    usageCounter: number;
    /**
     * The number of times the coupon code can be redeemed. `0` means unlimited redemptions but any campaign usage limits still apply.
     */
    usageLimit: number;
    /**
     * The name of the campaign that owns the coupon.
     */
    campaignName: string;
}

/**
 * Check if a given object implements the RedeemableCoupon interface.
 */
export function instanceOfRedeemableCoupon(value: object): value is RedeemableCoupon {
    const _v = value as Record<PropertyKey, unknown>;
    if (!('couponId' in _v) || _v['couponId'] === undefined) return false;
    if (!('couponCode' in _v) || _v['couponCode'] === undefined) return false;
    if (!('usageCounter' in _v) || _v['usageCounter'] === undefined) return false;
    if (!('usageLimit' in _v) || _v['usageLimit'] === undefined) return false;
    if (!('campaignName' in _v) || _v['campaignName'] === undefined) return false;
    return true;
}

export function RedeemableCouponFromJSON(json: any): RedeemableCoupon {
    return RedeemableCouponFromJSONTyped(json, false);
}

export function RedeemableCouponFromJSONTyped(json: any, ignoreDiscriminator: boolean): RedeemableCoupon {
    if (json == null) {
        return json;
    }
    return {
        
        'couponId': json['couponId'],
        'couponCode': json['couponCode'],
        'usageCounter': json['usageCounter'],
        'usageLimit': json['usageLimit'],
        'campaignName': json['campaignName'],
    };
}

export function RedeemableCouponToJSON(json: any): RedeemableCoupon {
    return RedeemableCouponToJSONTyped(json, false);
}

export function RedeemableCouponToJSONTyped(value?: RedeemableCoupon | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'couponId': value['couponId'],
        'couponCode': value['couponCode'],
        'usageCounter': value['usageCounter'],
        'usageLimit': value['usageLimit'],
        'campaignName': value['campaignName'],
    };
}

