/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RedeemLoyaltyPointsBlock1Program } from './RedeemLoyaltyPointsBlock1Program';
import {
    RedeemLoyaltyPointsBlock1ProgramFromJSON,
    RedeemLoyaltyPointsBlock1ProgramFromJSONTyped,
    RedeemLoyaltyPointsBlock1ProgramToJSON,
    RedeemLoyaltyPointsBlock1ProgramToJSONTyped,
} from './RedeemLoyaltyPointsBlock1Program';
import type { RedeemLoyaltyPointsBlock1Value } from './RedeemLoyaltyPointsBlock1Value';
import {
    RedeemLoyaltyPointsBlock1ValueFromJSON,
    RedeemLoyaltyPointsBlock1ValueFromJSONTyped,
    RedeemLoyaltyPointsBlock1ValueToJSON,
    RedeemLoyaltyPointsBlock1ValueToJSONTyped,
} from './RedeemLoyaltyPointsBlock1Value';
import type { PromotionBlock } from './PromotionBlock';
import {
    PromotionBlockFromJSON,
    PromotionBlockFromJSONTyped,
    PromotionBlockToJSON,
    PromotionBlockToJSONTyped,
} from './PromotionBlock';

/**
 * 
 * @export
 * @interface RedeemLoyaltyPointsBlock
 */
export interface RedeemLoyaltyPointsBlock {
    /**
     * Unique identifier for this block.
     * @type {string}
     * @memberof RedeemLoyaltyPointsBlock
     */
    id: string;
    /**
     * Identifies the block variant and determines which additional properties are present in it.
     * @type {string}
     * @memberof RedeemLoyaltyPointsBlock
     */
    type: string;
    /**
     * Semantic labels attached to this block.
     * @type {Array<string>}
     * @memberof RedeemLoyaltyPointsBlock
     */
    tags?: Array<string>;
    /**
     * 
     * @type {RedeemLoyaltyPointsBlock1Program}
     * @memberof RedeemLoyaltyPointsBlock
     */
    program: RedeemLoyaltyPointsBlock1Program;
    /**
     * The name of the subledger to deduct points from. Can be empty if this block deducts from the loyalty program's main ledger instead of a subledger.
     * @type {string}
     * @memberof RedeemLoyaltyPointsBlock
     */
    subledger: string;
    /**
     * 
     * @type {RedeemLoyaltyPointsBlock1Value}
     * @memberof RedeemLoyaltyPointsBlock
     */
    value: RedeemLoyaltyPointsBlock1Value;
    /**
     * A custom description recorded as the reason for the point deduction.
     * @type {string}
     * @memberof RedeemLoyaltyPointsBlock
     */
    name?: string;
    /**
     * Promotion blocks evaluated when this block fails or returns false.
     * @type {Array<PromotionBlock>}
     * @memberof RedeemLoyaltyPointsBlock
     */
    onFailure?: Array<PromotionBlock>;
}

/**
 * Check if a given object implements the RedeemLoyaltyPointsBlock interface.
 */
export function instanceOfRedeemLoyaltyPointsBlock(value: object): value is RedeemLoyaltyPointsBlock {
    const _v = value as Record<PropertyKey, unknown>;
    if (!('id' in _v) || _v['id'] === undefined) return false;
    if (!('type' in _v) || _v['type'] === undefined) return false;
    if (!('program' in _v) || _v['program'] === undefined) return false;
    if (!('subledger' in _v) || _v['subledger'] === undefined) return false;
    if (!('value' in _v) || _v['value'] === undefined) return false;
    return true;
}

export function RedeemLoyaltyPointsBlockFromJSON(json: any): RedeemLoyaltyPointsBlock {
    return RedeemLoyaltyPointsBlockFromJSONTyped(json, false);
}

export function RedeemLoyaltyPointsBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): RedeemLoyaltyPointsBlock {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'program': RedeemLoyaltyPointsBlock1ProgramFromJSON(json['program']),
        'subledger': json['subledger'],
        'value': RedeemLoyaltyPointsBlock1ValueFromJSON(json['value']),
        'name': json['name'] == null ? undefined : json['name'],
        'onFailure': json['onFailure'] == null ? undefined : ((json['onFailure'] as Array<any>).map(PromotionBlockFromJSON)),
    };
}

export function RedeemLoyaltyPointsBlockToJSON(json: any): RedeemLoyaltyPointsBlock {
    return RedeemLoyaltyPointsBlockToJSONTyped(json, false);
}

export function RedeemLoyaltyPointsBlockToJSONTyped(value?: RedeemLoyaltyPointsBlock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'tags': value['tags'],
        'program': RedeemLoyaltyPointsBlock1ProgramToJSON(value['program']),
        'subledger': value['subledger'],
        'value': RedeemLoyaltyPointsBlock1ValueToJSON(value['value']),
        'name': value['name'],
        'onFailure': value['onFailure'] == null ? undefined : ((value['onFailure'] as Array<any>).map(PromotionBlockToJSON)),
    };
}

