/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Aggregates items into a single value.
 * @export
 * @interface ReduceSelectorStep
 */
export interface ReduceSelectorStep {
    /**
     * A step discriminator of type `reduce`.
     */
    type: ReduceSelectorStepTypeEnum;
    /**
     * The aggregation operator applied to the items produced by the preceding step:
     * - `max`, `min`, and `sum` operate on numeric values.
     * - `count` returns the number of items.
     * - `empty` reports whether the list is empty.
     * 
     */
    operator: ReduceSelectorStepOperatorEnum;
}


/**
 * @export
 */
export const ReduceSelectorStepTypeEnum = {
    Reduce: 'reduce',
} as const;
export type ReduceSelectorStepTypeEnum = typeof ReduceSelectorStepTypeEnum[keyof typeof ReduceSelectorStepTypeEnum];

/**
 * @export
 */
export const ReduceSelectorStepOperatorEnum = {
    Max: 'max',
    Min: 'min',
    Sum: 'sum',
    Count: 'count',
    Empty: 'empty',
} as const;
export type ReduceSelectorStepOperatorEnum = typeof ReduceSelectorStepOperatorEnum[keyof typeof ReduceSelectorStepOperatorEnum];


/**
 * Check if a given object implements the ReduceSelectorStep interface.
 */
export function instanceOfReduceSelectorStep(value: object): value is ReduceSelectorStep {
    const _v = value as Record<PropertyKey, unknown>;
    if (!('type' in _v) || _v['type'] === undefined) return false;
    if (_v['type'] !== 'reduce') return false;
    
    if (!('operator' in _v) || _v['operator'] === undefined) return false;
    return true;
}

export function ReduceSelectorStepFromJSON(json: any): ReduceSelectorStep {
    return ReduceSelectorStepFromJSONTyped(json, false);
}

export function ReduceSelectorStepFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReduceSelectorStep {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'operator': json['operator'],
    };
}

export function ReduceSelectorStepToJSON(json: any): ReduceSelectorStep {
    return ReduceSelectorStepToJSONTyped(json, false);
}

export function ReduceSelectorStepToJSONTyped(value?: ReduceSelectorStep | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'operator': value['operator'],
    };
}

