/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReferralConstraints
 */
export interface ReferralConstraints {
    /**
     * Timestamp at which point the referral code becomes valid.
     * @type {Date}
     * @memberof ReferralConstraints
     */
    startDate?: Date;
    /**
     * Expiration date of the referral code. Referral never expires if this is omitted.
     * @type {Date}
     * @memberof ReferralConstraints
     */
    expiryDate?: Date;
    /**
     * The number of times a referral code can be used. `0` means no limit but any campaign usage limits will still apply.
     * 
     * @type {number}
     * @memberof ReferralConstraints
     */
    usageLimit?: number;
}

/**
 * Check if a given object implements the ReferralConstraints interface.
 */
export function instanceOfReferralConstraints(value: object): value is ReferralConstraints {
    return true;
}

export function ReferralConstraintsFromJSON(json: any): ReferralConstraints {
    return ReferralConstraintsFromJSONTyped(json, false);
}

export function ReferralConstraintsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferralConstraints {
    if (json == null) {
        return json;
    }
    return {
        
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'expiryDate': json['expiryDate'] == null ? undefined : (new Date(json['expiryDate'])),
        'usageLimit': json['usageLimit'] == null ? undefined : json['usageLimit'],
    };
}

export function ReferralConstraintsToJSON(json: any): ReferralConstraints {
    return ReferralConstraintsToJSONTyped(json, false);
}

export function ReferralConstraintsToJSONTyped(value?: ReferralConstraints | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'startDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
        'expiryDate': value['expiryDate'] == null ? value['expiryDate'] : value['expiryDate'].toISOString(),
        'usageLimit': value['usageLimit'],
    };
}

