/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The properties specific to the "reserveCoupon" effect. This gets triggered whenever a validated rule contained a "reserve coupon" effect. This reserves the coupon currently on scope to the profile on scope.
 * @export
 * @interface ReserveCouponEffectProps
 */
export interface ReserveCouponEffectProps {
    /**
     * The value of the coupon currently on scope.
     * @type {string}
     * @memberof ReserveCouponEffectProps
     */
    couponValue: string;
    /**
     * The ID of this customer profile in the third-party integration.
     * @type {string}
     * @memberof ReserveCouponEffectProps
     */
    profileIntegrationId: string;
    /**
     * Indicates whether this is a new coupon reservation or not.
     * @type {boolean}
     * @memberof ReserveCouponEffectProps
     */
    isNewReservation: boolean;
}

/**
 * Check if a given object implements the ReserveCouponEffectProps interface.
 */
export function instanceOfReserveCouponEffectProps(value: object): value is ReserveCouponEffectProps {
    if (!('couponValue' in value) || value['couponValue'] === undefined) return false;
    if (!('profileIntegrationId' in value) || value['profileIntegrationId'] === undefined) return false;
    if (!('isNewReservation' in value) || value['isNewReservation'] === undefined) return false;
    return true;
}

export function ReserveCouponEffectPropsFromJSON(json: any): ReserveCouponEffectProps {
    return ReserveCouponEffectPropsFromJSONTyped(json, false);
}

export function ReserveCouponEffectPropsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReserveCouponEffectProps {
    if (json == null) {
        return json;
    }
    return {
        
        'couponValue': json['couponValue'],
        'profileIntegrationId': json['profileIntegrationId'],
        'isNewReservation': json['isNewReservation'],
    };
}

export function ReserveCouponEffectPropsToJSON(json: any): ReserveCouponEffectProps {
    return ReserveCouponEffectPropsToJSONTyped(json, false);
}

export function ReserveCouponEffectPropsToJSONTyped(value?: ReserveCouponEffectProps | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'couponValue': value['couponValue'],
        'profileIntegrationId': value['profileIntegrationId'],
        'isNewReservation': value['isNewReservation'],
    };
}

