/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RuleFailureReason } from './RuleFailureReason';
import {
    RuleFailureReasonFromJSON,
    RuleFailureReasonFromJSONTyped,
    RuleFailureReasonToJSON,
    RuleFailureReasonToJSONTyped,
} from './RuleFailureReason';

/**
 * Returned when a reward unlock is rejected by the Rule Engine, for example because the customer already unlocked this reward, the customer has insufficient points, or the reward's eligibility conditions are not met.
 * 
 * @export
 * @interface RewardUnlockRejection
 */
export interface RewardUnlockRejection {
    /**
     * A human-readable summary of why the reward unlock was rejected.
     */
    message: string;
    /**
     * The reasons why the reward could not be unlocked.
     */
    ruleFailureReasons: Array<RuleFailureReason>;
}

/**
 * Check if a given object implements the RewardUnlockRejection interface.
 */
export function instanceOfRewardUnlockRejection(value: object): value is RewardUnlockRejection {
    const _v = value as Record<PropertyKey, unknown>;
    if (!('message' in _v) || _v['message'] === undefined) return false;
    if (!('ruleFailureReasons' in _v) || _v['ruleFailureReasons'] === undefined) return false;
    return true;
}

export function RewardUnlockRejectionFromJSON(json: any): RewardUnlockRejection {
    return RewardUnlockRejectionFromJSONTyped(json, false);
}

export function RewardUnlockRejectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RewardUnlockRejection {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'ruleFailureReasons': (json['ruleFailureReasons'] == null ? undefined as any : (json['ruleFailureReasons'] as Array<any>).map(RuleFailureReasonFromJSON)),
    };
}

export function RewardUnlockRejectionToJSON(json: any): RewardUnlockRejection {
    return RewardUnlockRejectionToJSONTyped(json, false);
}

export function RewardUnlockRejectionToJSONTyped(value?: RewardUnlockRejection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'ruleFailureReasons': (value['ruleFailureReasons'] == null ? undefined : (value['ruleFailureReasons'] as Array<any>).map(RuleFailureReasonToJSON)),
    };
}

