/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RewardEligibility } from './RewardEligibility';
import {
    RewardEligibilityFromJSON,
    RewardEligibilityFromJSONTyped,
    RewardEligibilityToJSON,
    RewardEligibilityToJSONTyped,
} from './RewardEligibility';
import type { RewardPointsRequired } from './RewardPointsRequired';
import {
    RewardPointsRequiredFromJSON,
    RewardPointsRequiredFromJSONTyped,
    RewardPointsRequiredToJSON,
    RewardPointsRequiredToJSONTyped,
} from './RewardPointsRequired';
import type { RuleMetadata } from './RuleMetadata';
import {
    RuleMetadataFromJSON,
    RuleMetadataFromJSONTyped,
    RuleMetadataToJSON,
    RuleMetadataToJSONTyped,
} from './RuleMetadata';

/**
 * A reward returned by the rewards catalog Integration API endpoint.
 * @export
 * @interface RewardCatalogItem
 */
export interface RewardCatalogItem {
    /**
     * The unique ID of the reward.
     */
    id: number;
    /**
     * The customer-facing name of the reward.
     */
    name: string;
    /**
     * The customer-facing description of the reward.
     */
    description?: string;
    /**
     * The loyalty points required to activate the reward.
     */
    pointsRequired?: Array<RewardPointsRequired>;
    /**
     * Customer-facing rule metadata for the reward.
     */
    rule: RuleMetadata;
    /**
     * The customer's eligibility for the reward. Returned only when the request
     * includes a `profileIntegrationId` or `loyaltyCardId`.
     * 
     */
    eligibility?: RewardEligibility;
}

/**
 * Check if a given object implements the RewardCatalogItem interface.
 */
export function instanceOfRewardCatalogItem(value: object): value is RewardCatalogItem {
    const _v = value as Record<PropertyKey, unknown>;
    if (!('id' in _v) || _v['id'] === undefined) return false;
    if (!('name' in _v) || _v['name'] === undefined) return false;
    if (!('rule' in _v) || _v['rule'] === undefined) return false;
    return true;
}

export function RewardCatalogItemFromJSON(json: any): RewardCatalogItem {
    return RewardCatalogItemFromJSONTyped(json, false);
}

export function RewardCatalogItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): RewardCatalogItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'pointsRequired': json['pointsRequired'] == null ? undefined : ((json['pointsRequired'] as Array<any>).map(RewardPointsRequiredFromJSON)),
        'rule': RuleMetadataFromJSON(json['rule']),
        'eligibility': json['eligibility'] == null ? undefined : RewardEligibilityFromJSON(json['eligibility']),
    };
}

export function RewardCatalogItemToJSON(json: any): RewardCatalogItem {
    return RewardCatalogItemToJSONTyped(json, false);
}

export function RewardCatalogItemToJSONTyped(value?: RewardCatalogItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'pointsRequired': value['pointsRequired'] == null ? undefined : ((value['pointsRequired'] as Array<any>).map(RewardPointsRequiredToJSON)),
        'rule': RuleMetadataToJSON(value['rule']),
        'eligibility': RewardEligibilityToJSON(value['eligibility']),
    };
}

