/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoleV2PermissionSet } from './RoleV2PermissionSet';
import {
    RoleV2PermissionSetFromJSON,
    RoleV2PermissionSetFromJSONTyped,
    RoleV2PermissionSetToJSON,
    RoleV2PermissionSetToJSONTyped,
} from './RoleV2PermissionSet';
import type { RolesV2Thresholds } from './RolesV2Thresholds';
import {
    RolesV2ThresholdsFromJSON,
    RolesV2ThresholdsFromJSONTyped,
    RolesV2ThresholdsToJSON,
    RolesV2ThresholdsToJSONTyped,
} from './RolesV2Thresholds';
import type { RoleV2RolesGroup } from './RoleV2RolesGroup';
import {
    RoleV2RolesGroupFromJSON,
    RoleV2RolesGroupFromJSONTyped,
    RoleV2RolesGroupToJSON,
    RoleV2RolesGroupToJSONTyped,
} from './RoleV2RolesGroup';

/**
 * 
 * @export
 * @interface RoleV2Permissions
 */
export interface RoleV2Permissions {
    /**
     * List of grouped logical operations referenced by roles.
     * @type {Array<RoleV2PermissionSet>}
     * @memberof RoleV2Permissions
     */
    permissionSets?: Array<RoleV2PermissionSet>;
    /**
     * 
     * @type {RoleV2RolesGroup}
     * @memberof RoleV2Permissions
     */
    roles?: RoleV2RolesGroup;
    /**
     * Support user limits for actions that require admin approval within the given application.
     * @type {Array<RolesV2Thresholds>}
     * @memberof RoleV2Permissions
     */
    thresholds?: Array<RolesV2Thresholds>;
}

/**
 * Check if a given object implements the RoleV2Permissions interface.
 */
export function instanceOfRoleV2Permissions(value: object): value is RoleV2Permissions {
    const _v = value as Record<PropertyKey, unknown>;
    return true;
}

export function RoleV2PermissionsFromJSON(json: any): RoleV2Permissions {
    return RoleV2PermissionsFromJSONTyped(json, false);
}

export function RoleV2PermissionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleV2Permissions {
    if (json == null) {
        return json;
    }
    return {
        
        'permissionSets': json['permissionSets'] == null ? undefined : ((json['permissionSets'] as Array<any>).map(RoleV2PermissionSetFromJSON)),
        'roles': json['roles'] == null ? undefined : RoleV2RolesGroupFromJSON(json['roles']),
        'thresholds': json['thresholds'] == null ? undefined : ((json['thresholds'] as Array<any>).map(RolesV2ThresholdsFromJSON)),
    };
}

export function RoleV2PermissionsToJSON(json: any): RoleV2Permissions {
    return RoleV2PermissionsToJSONTyped(json, false);
}

export function RoleV2PermissionsToJSONTyped(value?: RoleV2Permissions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'permissionSets': value['permissionSets'] == null ? undefined : ((value['permissionSets'] as Array<any>).map(RoleV2PermissionSetToJSON)),
        'roles': RoleV2RolesGroupToJSON(value['roles']),
        'thresholds': value['thresholds'] == null ? undefined : ((value['thresholds'] as Array<any>).map(RolesV2ThresholdsToJSON)),
    };
}

