/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoleAssign
 */
export interface RoleAssign {
    /**
     * An array of user IDs.
     * @type {Array<number>}
     * @memberof RoleAssign
     */
    users: Array<number>;
    /**
     * An array of role IDs.
     * @type {Array<number>}
     * @memberof RoleAssign
     */
    roles: Array<number>;
}

/**
 * Check if a given object implements the RoleAssign interface.
 */
export function instanceOfRoleAssign(value: object): value is RoleAssign {
    if (!('users' in value) || value['users'] === undefined) return false;
    if (!('roles' in value) || value['roles'] === undefined) return false;
    return true;
}

export function RoleAssignFromJSON(json: any): RoleAssign {
    return RoleAssignFromJSONTyped(json, false);
}

export function RoleAssignFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleAssign {
    if (json == null) {
        return json;
    }
    return {
        
        'users': json['users'],
        'roles': json['roles'],
    };
}

export function RoleAssignToJSON(json: any): RoleAssign {
    return RoleAssignToJSONTyped(json, false);
}

export function RoleAssignToJSONTyped(value?: RoleAssign | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'users': value['users'],
        'roles': value['roles'],
    };
}

