/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * This effect indicates that the customer's progress in an achievement was rolled back.
 * 
 * The Rule Engine triggers this effect when you cancel or [reopen a customer session](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/reopenCustomerSession) that previously validated the [Update customer progress](https://docs.talon.one/docs/product/rules/effects/use-effects#update-customer-progress) effect and triggered the [increaseAchievementProgress](https://docs.talon.one/docs/dev/integration-api/api-effects#increaseachievementprogress) API effect.
 * 
 * The effect is also triggered for completed achievements if the **Allow progress rollback for completed achievements** setting is enabled. You can enable this through the [Campaign Manager](https://docs.talon.one/docs/product/campaigns/achievements/manage-achievements) or the [Management API](https://docs.talon.one/management-api#tag/Achievements/operation/createAchievement) by setting the `achievementAllowRollbackAfterCompletion` property to `true`. This setting only applies to one-time and recurring on expiration achievements.
 * @export
 * @interface RollbackIncreasedAchievementProgressEffectProps
 */
export interface RollbackIncreasedAchievementProgressEffectProps {
    /**
     * The internal ID of the achievement.
     * @type {number}
     * @memberof RollbackIncreasedAchievementProgressEffectProps
     */
    achievementId: number;
    /**
     * The name of the achievement.
     * @type {string}
     * @memberof RollbackIncreasedAchievementProgressEffectProps
     */
    achievementName: string;
    /**
     * The internal ID of the achievement progress tracker.
     * @type {number}
     * @memberof RollbackIncreasedAchievementProgressEffectProps
     */
    progressTrackerId: number;
    /**
     * The value by which the customer's current progress in the achievement has decreased.
     * @type {number}
     * @memberof RollbackIncreasedAchievementProgressEffectProps
     */
    decreaseProgressBy: number;
    /**
     * The current progress of the customer in the achievement.
     * @type {number}
     * @memberof RollbackIncreasedAchievementProgressEffectProps
     */
    currentProgress: number;
    /**
     * The target value to complete the achievement.
     * @type {number}
     * @memberof RollbackIncreasedAchievementProgressEffectProps
     */
    target: number;
}

/**
 * Check if a given object implements the RollbackIncreasedAchievementProgressEffectProps interface.
 */
export function instanceOfRollbackIncreasedAchievementProgressEffectProps(value: object): value is RollbackIncreasedAchievementProgressEffectProps {
    if (!('achievementId' in value) || value['achievementId'] === undefined) return false;
    if (!('achievementName' in value) || value['achievementName'] === undefined) return false;
    if (!('progressTrackerId' in value) || value['progressTrackerId'] === undefined) return false;
    if (!('decreaseProgressBy' in value) || value['decreaseProgressBy'] === undefined) return false;
    if (!('currentProgress' in value) || value['currentProgress'] === undefined) return false;
    if (!('target' in value) || value['target'] === undefined) return false;
    return true;
}

export function RollbackIncreasedAchievementProgressEffectPropsFromJSON(json: any): RollbackIncreasedAchievementProgressEffectProps {
    return RollbackIncreasedAchievementProgressEffectPropsFromJSONTyped(json, false);
}

export function RollbackIncreasedAchievementProgressEffectPropsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RollbackIncreasedAchievementProgressEffectProps {
    if (json == null) {
        return json;
    }
    return {
        
        'achievementId': json['achievementId'],
        'achievementName': json['achievementName'],
        'progressTrackerId': json['progressTrackerId'],
        'decreaseProgressBy': json['decreaseProgressBy'],
        'currentProgress': json['currentProgress'],
        'target': json['target'],
    };
}

export function RollbackIncreasedAchievementProgressEffectPropsToJSON(json: any): RollbackIncreasedAchievementProgressEffectProps {
    return RollbackIncreasedAchievementProgressEffectPropsToJSONTyped(json, false);
}

export function RollbackIncreasedAchievementProgressEffectPropsToJSONTyped(value?: RollbackIncreasedAchievementProgressEffectProps | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'achievementId': value['achievementId'],
        'achievementName': value['achievementName'],
        'progressTrackerId': value['progressTrackerId'],
        'decreaseProgressBy': value['decreaseProgressBy'],
        'currentProgress': value['currentProgress'],
        'target': value['target'],
    };
}

