/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Configuration settings related to patch operations, which allow partial updates to SCIM resources.
 * @export
 * @interface ScimServiceProviderConfigResponsePatch
 */
export interface ScimServiceProviderConfigResponsePatch {
    /**
     * Indicates whether the service provider supports patch operations for modifying resources.
     * @type {boolean}
     * @memberof ScimServiceProviderConfigResponsePatch
     */
    supported?: boolean;
}

/**
 * Check if a given object implements the ScimServiceProviderConfigResponsePatch interface.
 */
export function instanceOfScimServiceProviderConfigResponsePatch(value: object): value is ScimServiceProviderConfigResponsePatch {
    return true;
}

export function ScimServiceProviderConfigResponsePatchFromJSON(json: any): ScimServiceProviderConfigResponsePatch {
    return ScimServiceProviderConfigResponsePatchFromJSONTyped(json, false);
}

export function ScimServiceProviderConfigResponsePatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScimServiceProviderConfigResponsePatch {
    if (json == null) {
        return json;
    }
    return {
        
        'supported': json['supported'] == null ? undefined : json['supported'],
    };
}

export function ScimServiceProviderConfigResponsePatchToJSON(json: any): ScimServiceProviderConfigResponsePatch {
    return ScimServiceProviderConfigResponsePatchToJSONTyped(json, false);
}

export function ScimServiceProviderConfigResponsePatchToJSONTyped(value?: ScimServiceProviderConfigResponsePatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'supported': value['supported'],
    };
}

