/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScimGroup } from './ScimGroup';
import {
    ScimGroupFromJSON,
    ScimGroupFromJSONTyped,
    ScimGroupToJSON,
    ScimGroupToJSONTyped,
} from './ScimGroup';

/**
 * List of groups created using the SCIM provisioning protocol with an identity provider, for example, Microsoft Entra ID.
 * In Talon.One, a `Group` corresponds to a [role](https://docs.talon.one/docs/product/account/account-settings/managing-roles), and `members` are the [users](https://docs.talon.one/docs/product/account/account-settings/managing-users) assigned to that role.
 * @export
 * @interface ScimGroupsListResponse
 */
export interface ScimGroupsListResponse {
    /**
     * 
     * @type {Array<ScimGroup>}
     * @memberof ScimGroupsListResponse
     */
    resources: Array<ScimGroup>;
    /**
     * SCIM schema for the given resource.
     * @type {Array<string>}
     * @memberof ScimGroupsListResponse
     */
    schemas?: Array<string>;
    /**
     * Number of results in the response.
     * @type {number}
     * @memberof ScimGroupsListResponse
     */
    totalResults?: number;
}

/**
 * Check if a given object implements the ScimGroupsListResponse interface.
 */
export function instanceOfScimGroupsListResponse(value: object): value is ScimGroupsListResponse {
    if (!('resources' in value) || value['resources'] === undefined) return false;
    return true;
}

export function ScimGroupsListResponseFromJSON(json: any): ScimGroupsListResponse {
    return ScimGroupsListResponseFromJSONTyped(json, false);
}

export function ScimGroupsListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScimGroupsListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'resources': ((json['Resources'] as Array<any>).map(ScimGroupFromJSON)),
        'schemas': json['schemas'] == null ? undefined : json['schemas'],
        'totalResults': json['totalResults'] == null ? undefined : json['totalResults'],
    };
}

export function ScimGroupsListResponseToJSON(json: any): ScimGroupsListResponse {
    return ScimGroupsListResponseToJSONTyped(json, false);
}

export function ScimGroupsListResponseToJSONTyped(value?: ScimGroupsListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Resources': ((value['resources'] as Array<any>).map(ScimGroupToJSON)),
        'schemas': value['schemas'],
        'totalResults': value['totalResults'],
    };
}

