/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The properties specific to the "setDiscount" effect. This gets triggered whenever a validated rule contained a "set discount" effect. This is a discount that should be applied on the scope of defined with it.
 * @export
 * @interface SetDiscountEffectProps
 */
export interface SetDiscountEffectProps {
    /**
     * The name / description of this discount
     * @type {string}
     * @memberof SetDiscountEffectProps
     */
    name: string;
    /**
     * The total monetary value of the discount.
     * @type {number}
     * @memberof SetDiscountEffectProps
     */
    value: number;
    /**
     * The scope which the discount was applied on, can be one of (cartItems,additionalCosts,sessionTotal).
     * @type {string}
     * @memberof SetDiscountEffectProps
     */
    scope?: string;
    /**
     * The original value of the discount.
     * @type {number}
     * @memberof SetDiscountEffectProps
     */
    desiredValue?: number;
}

/**
 * Check if a given object implements the SetDiscountEffectProps interface.
 */
export function instanceOfSetDiscountEffectProps(value: object): value is SetDiscountEffectProps {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function SetDiscountEffectPropsFromJSON(json: any): SetDiscountEffectProps {
    return SetDiscountEffectPropsFromJSONTyped(json, false);
}

export function SetDiscountEffectPropsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetDiscountEffectProps {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'desiredValue': json['desiredValue'] == null ? undefined : json['desiredValue'],
    };
}

export function SetDiscountEffectPropsToJSON(json: any): SetDiscountEffectProps {
    return SetDiscountEffectPropsToJSONTyped(json, false);
}

export function SetDiscountEffectPropsToJSONTyped(value?: SetDiscountEffectProps | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': value['value'],
        'scope': value['scope'],
        'desiredValue': value['desiredValue'],
    };
}

