/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * This effect indicates that the customer's progress in an achievement was started during 
 * the current session. The Rule Engine creates a progress tracker for the customer, 
 * identified by `progressTrackerId`. 
 * 
 * This effect only starts the customer's progress and does not increase the
 * progress. When this effect is returned, the customer progress status is
 * `inprogress` and the progress value is `0`.
 * 
 * You can retrieve the customer's current progress at any time, whether or not
 * this effect was returned, in the following ways:
 * - Include `achievements` in the `responseContent` property of your request,
 *   on any endpoint where this property is available, for example
 *   [Update customer session](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2).
 * - Use the [List customer's available achievements](https://docs.talon.one/integration-api#tag/Achievements/operation/getCustomerAchievements) endpoint.
 * - Use the [List customer's achievement history](https://docs.talon.one/integration-api#tag/Achievements/operation/getCustomerAchievementHistory) endpoint.
 * 
 * For recurring achievements, this effect is only returned for the first iteration
 * and has no effect on the iterations that follow. For 
 * [recurring user-action achievements](https://docs.talon.one/docs/product/achievements/overview#recurring-user-action-achievements)
 * specifically, this effect also begins the customer's progress period, specified 
 * by the `startDate` and `endDate` properties.
 * 
 * This effect is triggered in the following cases:
 * 
 * - A rule containing a [Start customer
 *   progress](https://docs.talon.one/docs/product/rules/effects/use-effects#start-customer-progress)
 *   effect is validated.
 * - A rule containing an [Update customer
 *   progress](https://docs.talon.one/docs/product/rules/effects/use-effects#update-customer-progress)
 *   effect is validated for an achievement that the customer has not started
 *   yet. In this case, the Rule Engine returns the `startAchievementProgress`
 *   effect first, followed by
 *   [increaseAchievementProgress](https://docs.talon.one/docs/dev/integration-api/api-effects#increaseachievementprogress),
 *   which carries the increased customer progress. Use `progressTrackerId` to
 *   connect the results produced by the two effects.
 * 
 * **Note:**
 * - This effect is not returned if the customer's progress in the achievement has 
 *   already started, or if the achievement's end date has passed. In these cases, 
 *   the **Start customer progress** effect fails, an 
 *   [error](https://docs.talon.one/docs/dev/integration-api/api-effects#error) effect
 *   is returned, and the customer's progress remains unchanged. Any other effects 
 *   in the same rule are also not applied.
 * - If a rule with this effect fails, include `ruleFailureReasons` in the 
 *   `responseContent` property of your request to see the reason for failure. 
 *   The customer's progress is unchanged, so no update is required. The failure 
 *   reason identifies the campaign, ruleset, and rule that failed, and `details` 
 *   explains why.
 * - There is no rollback effect for the `startAchievementProgress` effect.
 * 
 * @export
 * @interface StartAchievementProgressEffectProps
 */
export interface StartAchievementProgressEffectProps {
    /**
     * The ID of the achievement.
     */
    achievementId: number;
    /**
     * The name of the achievement.
     */
    achievementName: string;
    /**
     * The ID of the customer's progress tracker for this achievement.
     * 
     * For [on-completion achievements](https://docs.talon.one/docs/product/achievements/overview#recurring-on-completion-achievements), this effect generates a unique ID for each iteration.
     */
    progressTrackerId?: number;
    /**
     * The target value to complete the achievement.
     */
    target: number;
    /**
     * Timestamp at which the customer's progress started.
     */
    startDate: Date;
    /**
     * Timestamp at which this progress period ends.
     * 
     * Only returned for achievements that have a fixed end date. [On-completion achievements](https://docs.talon.one/docs/product/achievements/overview#recurring-on-completion-achievements) have no end date.
     */
    endDate?: Date;
}

/**
 * Check if a given object implements the StartAchievementProgressEffectProps interface.
 */
export function instanceOfStartAchievementProgressEffectProps(value: object): value is StartAchievementProgressEffectProps {
    const _v = value as Record<PropertyKey, unknown>;
    if (!('achievementId' in _v) || _v['achievementId'] === undefined) return false;
    if (!('achievementName' in _v) || _v['achievementName'] === undefined) return false;
    if (!('target' in _v) || _v['target'] === undefined) return false;
    if (!('startDate' in _v) || _v['startDate'] === undefined) return false;
    return true;
}

export function StartAchievementProgressEffectPropsFromJSON(json: any): StartAchievementProgressEffectProps {
    return StartAchievementProgressEffectPropsFromJSONTyped(json, false);
}

export function StartAchievementProgressEffectPropsFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartAchievementProgressEffectProps {
    if (json == null) {
        return json;
    }
    return {
        
        'achievementId': json['achievementId'],
        'achievementName': json['achievementName'],
        'progressTrackerId': json['progressTrackerId'] == null ? undefined : json['progressTrackerId'],
        'target': json['target'],
        'startDate': (json['startDate'] == null ? json['startDate'] : parseDateTime(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (parseDateTime(json['endDate'])),
    };
}

export function StartAchievementProgressEffectPropsToJSON(json: any): StartAchievementProgressEffectProps {
    return StartAchievementProgressEffectPropsToJSONTyped(json, false);
}

export function StartAchievementProgressEffectPropsToJSONTyped(value?: StartAchievementProgressEffectProps | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'achievementId': value['achievementId'],
        'achievementName': value['achievementName'],
        'progressTrackerId': value['progressTrackerId'],
        'target': value['target'],
        'startDate': value['startDate'] == null ? undefined : serializeDateTime(value['startDate']),
        'endDate': value['endDate'] == null ? value['endDate'] : serializeDateTime(value['endDate']),
    };
}

