/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Store
 */
export interface Store {
    /**
     * The internal ID of this entity.
     * @type {number}
     * @memberof Store
     */
    id: number;
    /**
     * The time this entity was created.
     * @type {Date}
     * @memberof Store
     */
    created: Date;
    /**
     * The name of the store.
     * @type {string}
     * @memberof Store
     */
    name: string;
    /**
     * The description of the store.
     * @type {string}
     * @memberof Store
     */
    description: string;
    /**
     * The attributes of the store.
     * @type {object}
     * @memberof Store
     */
    attributes?: object;
    /**
     * The integration ID of the store. You choose this ID when you create a store.
     * 
     * **Note**: You cannot edit the `integrationId` after the store has been created.
     * 
     * @type {string}
     * @memberof Store
     */
    integrationId: string;
    /**
     * The ID of the Application that owns this entity.
     * @type {number}
     * @memberof Store
     */
    applicationId: number;
    /**
     * Timestamp of the most recent update on this entity.
     * @type {Date}
     * @memberof Store
     */
    updated: Date;
    /**
     * A list of IDs of the campaigns that are linked with current store.
     * @type {Array<number>}
     * @memberof Store
     */
    linkedCampaignIds?: Array<number>;
}

/**
 * Check if a given object implements the Store interface.
 */
export function instanceOfStore(value: object): value is Store {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('integrationId' in value) || value['integrationId'] === undefined) return false;
    if (!('applicationId' in value) || value['applicationId'] === undefined) return false;
    if (!('updated' in value) || value['updated'] === undefined) return false;
    return true;
}

export function StoreFromJSON(json: any): Store {
    return StoreFromJSONTyped(json, false);
}

export function StoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): Store {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'created': (new Date(json['created'])),
        'name': json['name'],
        'description': json['description'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'integrationId': json['integrationId'],
        'applicationId': json['applicationId'],
        'updated': (new Date(json['updated'])),
        'linkedCampaignIds': json['linkedCampaignIds'] == null ? undefined : json['linkedCampaignIds'],
    };
}

export function StoreToJSON(json: any): Store {
    return StoreToJSONTyped(json, false);
}

export function StoreToJSONTyped(value?: Store | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created': value['created'].toISOString(),
        'name': value['name'],
        'description': value['description'],
        'attributes': value['attributes'],
        'integrationId': value['integrationId'],
        'applicationId': value['applicationId'],
        'updated': value['updated'].toISOString(),
        'linkedCampaignIds': value['linkedCampaignIds'],
    };
}

