/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { StrikethroughCustomEffectPerItemProps } from './StrikethroughCustomEffectPerItemProps';
import {
    instanceOfStrikethroughCustomEffectPerItemProps,
    StrikethroughCustomEffectPerItemPropsFromJSON,
    StrikethroughCustomEffectPerItemPropsFromJSONTyped,
    StrikethroughCustomEffectPerItemPropsToJSON,
} from './StrikethroughCustomEffectPerItemProps';
import type { StrikethroughSetDiscountPerItemEffectProps } from './StrikethroughSetDiscountPerItemEffectProps';
import {
    instanceOfStrikethroughSetDiscountPerItemEffectProps,
    StrikethroughSetDiscountPerItemEffectPropsFromJSON,
    StrikethroughSetDiscountPerItemEffectPropsFromJSONTyped,
    StrikethroughSetDiscountPerItemEffectPropsToJSON,
} from './StrikethroughSetDiscountPerItemEffectProps';
import type { StrikethroughSetDiscountPerItemMemberEffectProps } from './StrikethroughSetDiscountPerItemMemberEffectProps';
import {
    instanceOfStrikethroughSetDiscountPerItemMemberEffectProps,
    StrikethroughSetDiscountPerItemMemberEffectPropsFromJSON,
    StrikethroughSetDiscountPerItemMemberEffectPropsFromJSONTyped,
    StrikethroughSetDiscountPerItemMemberEffectPropsToJSON,
} from './StrikethroughSetDiscountPerItemMemberEffectProps';

/**
 * @type StrikethroughEffectProps
 * 
 * @export
 */
export type StrikethroughEffectProps = StrikethroughCustomEffectPerItemProps | StrikethroughSetDiscountPerItemEffectProps | StrikethroughSetDiscountPerItemMemberEffectProps;

export function StrikethroughEffectPropsFromJSON(json: any): StrikethroughEffectProps {
    return StrikethroughEffectPropsFromJSONTyped(json, false);
}

export function StrikethroughEffectPropsFromJSONTyped(json: any, ignoreDiscriminator: boolean): StrikethroughEffectProps {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfStrikethroughCustomEffectPerItemProps(json)) {
        return StrikethroughCustomEffectPerItemPropsFromJSONTyped(json, true);
    }
    if (instanceOfStrikethroughSetDiscountPerItemEffectProps(json)) {
        return StrikethroughSetDiscountPerItemEffectPropsFromJSONTyped(json, true);
    }
    if (instanceOfStrikethroughSetDiscountPerItemMemberEffectProps(json)) {
        return StrikethroughSetDiscountPerItemMemberEffectPropsFromJSONTyped(json, true);
    }
    return {} as any;
}

export function StrikethroughEffectPropsToJSON(json: any): any {
    return StrikethroughEffectPropsToJSONTyped(json, false);
}

export function StrikethroughEffectPropsToJSONTyped(value?: StrikethroughEffectProps | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfStrikethroughCustomEffectPerItemProps(value)) {
        return StrikethroughCustomEffectPerItemPropsToJSON(value as StrikethroughCustomEffectPerItemProps);
    }
    if (instanceOfStrikethroughSetDiscountPerItemEffectProps(value)) {
        return StrikethroughSetDiscountPerItemEffectPropsToJSON(value as StrikethroughSetDiscountPerItemEffectProps);
    }
    if (instanceOfStrikethroughSetDiscountPerItemMemberEffectProps(value)) {
        return StrikethroughSetDiscountPerItemMemberEffectPropsToJSON(value as StrikethroughSetDiscountPerItemMemberEffectProps);
    }
    return {};
}

