/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StrikethroughEffect } from './StrikethroughEffect';
import {
    StrikethroughEffectFromJSON,
    StrikethroughEffectFromJSONTyped,
    StrikethroughEffectToJSON,
    StrikethroughEffectToJSONTyped,
} from './StrikethroughEffect';

/**
 * 
 * @export
 * @interface StrikethroughDebugResponse
 */
export interface StrikethroughDebugResponse {
    /**
     * The campaign IDs that got fetched for the evaluation process.
     * @type {Array<number>}
     * @memberof StrikethroughDebugResponse
     */
    campaignsIDs?: Array<number>;
    /**
     * The strikethrough effects that are returned from the evaluation process.
     * @type {Array<StrikethroughEffect>}
     * @memberof StrikethroughDebugResponse
     */
    effects?: Array<StrikethroughEffect>;
}

/**
 * Check if a given object implements the StrikethroughDebugResponse interface.
 */
export function instanceOfStrikethroughDebugResponse(value: object): value is StrikethroughDebugResponse {
    return true;
}

export function StrikethroughDebugResponseFromJSON(json: any): StrikethroughDebugResponse {
    return StrikethroughDebugResponseFromJSONTyped(json, false);
}

export function StrikethroughDebugResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StrikethroughDebugResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'campaignsIDs': json['campaignsIDs'] == null ? undefined : json['campaignsIDs'],
        'effects': json['effects'] == null ? undefined : ((json['effects'] as Array<any>).map(StrikethroughEffectFromJSON)),
    };
}

export function StrikethroughDebugResponseToJSON(json: any): StrikethroughDebugResponse {
    return StrikethroughDebugResponseToJSONTyped(json, false);
}

export function StrikethroughDebugResponseToJSONTyped(value?: StrikethroughDebugResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'campaignsIDs': value['campaignsIDs'],
        'effects': value['effects'] == null ? undefined : ((value['effects'] as Array<any>).map(StrikethroughEffectToJSON)),
    };
}

