/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * setDiscountPerItem effect in strikethrough pricing payload.
 * @export
 * @interface StrikethroughSetDiscountPerItemEffectProps
 */
export interface StrikethroughSetDiscountPerItemEffectProps {
    /**
     * effect name.
     * @type {string}
     * @memberof StrikethroughSetDiscountPerItemEffectProps
     */
    name: string;
    /**
     * 
     * @type {any}
     * @memberof StrikethroughSetDiscountPerItemEffectProps
     */
    value: any | null;
}

/**
 * Check if a given object implements the StrikethroughSetDiscountPerItemEffectProps interface.
 */
export function instanceOfStrikethroughSetDiscountPerItemEffectProps(value: object): value is StrikethroughSetDiscountPerItemEffectProps {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function StrikethroughSetDiscountPerItemEffectPropsFromJSON(json: any): StrikethroughSetDiscountPerItemEffectProps {
    return StrikethroughSetDiscountPerItemEffectPropsFromJSONTyped(json, false);
}

export function StrikethroughSetDiscountPerItemEffectPropsFromJSONTyped(json: any, ignoreDiscriminator: boolean): StrikethroughSetDiscountPerItemEffectProps {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'],
    };
}

export function StrikethroughSetDiscountPerItemEffectPropsToJSON(json: any): StrikethroughSetDiscountPerItemEffectProps {
    return StrikethroughSetDiscountPerItemEffectPropsToJSONTyped(json, false);
}

export function StrikethroughSetDiscountPerItemEffectPropsToJSONTyped(value?: StrikethroughSetDiscountPerItemEffectProps | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': value['value'],
    };
}

