/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TierUpgradeData } from './TierUpgradeData';
import {
    TierUpgradeDataFromJSON,
    TierUpgradeDataFromJSONTyped,
    TierUpgradeDataToJSON,
    TierUpgradeDataToJSONTyped,
} from './TierUpgradeData';

/**
 * 
 * @export
 * @interface TierUpgradeNotification
 */
export interface TierUpgradeNotification {
    /**
     * 
     * @type {number}
     * @memberof TierUpgradeNotification
     */
    totalResultSize: number;
    /**
     * The array of tier upgrade notifications.
     * @type {Array<TierUpgradeData>}
     * @memberof TierUpgradeNotification
     */
    data: Array<TierUpgradeData>;
    /**
     * The type of notification.
     * @type {string}
     * @memberof TierUpgradeNotification
     */
    notificationType: TierUpgradeNotificationNotificationTypeEnum;
}


/**
 * @export
 */
export const TierUpgradeNotificationNotificationTypeEnum = {
    TierUpgrade: 'TierUpgrade'
} as const;
export type TierUpgradeNotificationNotificationTypeEnum = typeof TierUpgradeNotificationNotificationTypeEnum[keyof typeof TierUpgradeNotificationNotificationTypeEnum];


/**
 * Check if a given object implements the TierUpgradeNotification interface.
 */
export function instanceOfTierUpgradeNotification(value: object): value is TierUpgradeNotification {
    if (!('totalResultSize' in value) || value['totalResultSize'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('notificationType' in value) || value['notificationType'] === undefined) return false;
    return true;
}

export function TierUpgradeNotificationFromJSON(json: any): TierUpgradeNotification {
    return TierUpgradeNotificationFromJSONTyped(json, false);
}

export function TierUpgradeNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TierUpgradeNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'totalResultSize': json['TotalResultSize'],
        'data': ((json['Data'] as Array<any>).map(TierUpgradeDataFromJSON)),
        'notificationType': json['NotificationType'],
    };
}

export function TierUpgradeNotificationToJSON(json: any): TierUpgradeNotification {
    return TierUpgradeNotificationToJSONTyped(json, false);
}

export function TierUpgradeNotificationToJSONTyped(value?: TierUpgradeNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'TotalResultSize': value['totalResultSize'],
        'Data': ((value['data'] as Array<any>).map(TierUpgradeDataToJSON)),
        'NotificationType': value['notificationType'],
    };
}

