/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Block } from './Block';
import {
    BlockFromJSON,
    BlockFromJSONTyped,
    BlockToJSON,
    BlockToJSONTyped,
} from './Block';
import type { TriggerWebhookBlock1Webhook } from './TriggerWebhookBlock1Webhook';
import {
    TriggerWebhookBlock1WebhookFromJSON,
    TriggerWebhookBlock1WebhookFromJSONTyped,
    TriggerWebhookBlock1WebhookToJSON,
    TriggerWebhookBlock1WebhookToJSONTyped,
} from './TriggerWebhookBlock1Webhook';

/**
 * 
 * @export
 * @interface TriggerWebhookBlock
 */
export interface TriggerWebhookBlock {
    /**
     * Unique identifier for this block.
     */
    readonly id?: string;
    /**
     * Identifies the block variant and determines which additional properties are present in it.
     */
    type: string;
    /**
     * Semantic labels attached to this block.
     */
    readonly tags?: Array<string>;
    /**
     * 
     */
    webhook: TriggerWebhookBlock1Webhook;
    /**
     * The webhook's parameters, in configured order. Each property name is the parameter's title, lowercased with spaces replaced by underscores (for example, `Order ID` becomes `order_id`); falls back to `param_0`, `param_1`, and so on if a title is blank or collides with another.
     */
    params?: { [key: string]: any; };
    /**
     * Named error handlers evaluated when a specific error occurs.
     */
    onError?: { [key: string]: Array<Block>; };
}

/**
 * Check if a given object implements the TriggerWebhookBlock interface.
 */
export function instanceOfTriggerWebhookBlock(value: object): value is TriggerWebhookBlock {
    const _v = value as Record<PropertyKey, unknown>;
    if (!('type' in _v) || _v['type'] === undefined) return false;
    if (!('webhook' in _v) || _v['webhook'] === undefined) return false;
    return true;
}

export function TriggerWebhookBlockFromJSON(json: any): TriggerWebhookBlock {
    return TriggerWebhookBlockFromJSONTyped(json, false);
}

export function TriggerWebhookBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriggerWebhookBlock {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'webhook': TriggerWebhookBlock1WebhookFromJSON(json['webhook']),
        'params': json['params'] == null ? undefined : json['params'],
        'onError': json['onError'] == null ? undefined : json['onError'],
    };
}

export function TriggerWebhookBlockToJSON(json: any): TriggerWebhookBlock {
    return TriggerWebhookBlockToJSONTyped(json, false);
}

export function TriggerWebhookBlockToJSONTyped(value?: Omit<TriggerWebhookBlock, 'id'|'tags'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'webhook': TriggerWebhookBlock1WebhookToJSON(value['webhook']),
        'params': value['params'],
        'onError': value['onError'],
    };
}

