/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCampaignCollection
 */
export interface UpdateCampaignCollection {
    /**
     * A short description of the purpose of this collection.
     * @type {string}
     * @memberof UpdateCampaignCollection
     */
    description?: string;
}

/**
 * Check if a given object implements the UpdateCampaignCollection interface.
 */
export function instanceOfUpdateCampaignCollection(value: object): value is UpdateCampaignCollection {
    return true;
}

export function UpdateCampaignCollectionFromJSON(json: any): UpdateCampaignCollection {
    return UpdateCampaignCollectionFromJSONTyped(json, false);
}

export function UpdateCampaignCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCampaignCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function UpdateCampaignCollectionToJSON(json: any): UpdateCampaignCollection {
    return UpdateCampaignCollectionToJSONTyped(json, false);
}

export function UpdateCampaignCollectionToJSONTyped(value?: UpdateCampaignCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
    };
}

