/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The properties specific to the "updateAttribute" effect. This gets triggered whenever a validated rule contained an "update an attribute" effect.
 * @export
 * @interface UpdateAttributeEffectProps
 */
export interface UpdateAttributeEffectProps {
    /**
     * The exact path of the attribute that was updated.
     * @type {string}
     * @memberof UpdateAttributeEffectProps
     */
    path: string;
    /**
     * 
     * @type {any}
     * @memberof UpdateAttributeEffectProps
     */
    value: any | null;
}

/**
 * Check if a given object implements the UpdateAttributeEffectProps interface.
 */
export function instanceOfUpdateAttributeEffectProps(value: object): value is UpdateAttributeEffectProps {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function UpdateAttributeEffectPropsFromJSON(json: any): UpdateAttributeEffectProps {
    return UpdateAttributeEffectPropsFromJSONTyped(json, false);
}

export function UpdateAttributeEffectPropsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAttributeEffectProps {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'value': json['value'],
    };
}

export function UpdateAttributeEffectPropsToJSON(json: any): UpdateAttributeEffectProps {
    return UpdateAttributeEffectPropsToJSONTyped(json, false);
}

export function UpdateAttributeEffectPropsToJSONTyped(value?: UpdateAttributeEffectProps | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'value': value['value'],
    };
}

