/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUser
 */
export interface UpdateUser {
    /**
     * Name of the user.
     * @type {string}
     * @memberof UpdateUser
     */
    name?: string;
    /**
     * The state of the user.
     *   - `deactivated`: The user has been deactivated.
     *   - `active`: The user is active.
     * 
     * **Note**: Only `admin` users can update the state of another user.
     * 
     * @type {string}
     * @memberof UpdateUser
     */
    state?: UpdateUserStateEnum;
    /**
     * Indicates whether the user is an `admin`.
     * @type {boolean}
     * @memberof UpdateUser
     */
    isAdmin?: boolean;
    /**
     * Indicates the access level of the user.
     * @type {string}
     * @memberof UpdateUser
     */
    policy?: string;
    /**
     * A list of the IDs of the roles assigned to the user.
     * 
     * **Note**: To find the ID of a role, use the [List roles](/management-api#tag/Roles/operation/listAllRolesV2) endpoint.
     * 
     * @type {Array<number>}
     * @memberof UpdateUser
     */
    roles?: Array<number>;
    /**
     * Application notifications that the user is subscribed to.
     * @type {object}
     * @memberof UpdateUser
     */
    applicationNotificationSubscriptions?: object;
}


/**
 * @export
 */
export const UpdateUserStateEnum = {
    Deactivated: 'deactivated',
    Active: 'active'
} as const;
export type UpdateUserStateEnum = typeof UpdateUserStateEnum[keyof typeof UpdateUserStateEnum];


/**
 * Check if a given object implements the UpdateUser interface.
 */
export function instanceOfUpdateUser(value: object): value is UpdateUser {
    return true;
}

export function UpdateUserFromJSON(json: any): UpdateUser {
    return UpdateUserFromJSONTyped(json, false);
}

export function UpdateUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUser {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'state': json['state'] == null ? undefined : json['state'],
        'isAdmin': json['isAdmin'] == null ? undefined : json['isAdmin'],
        'policy': json['policy'] == null ? undefined : json['policy'],
        'roles': json['roles'] == null ? undefined : json['roles'],
        'applicationNotificationSubscriptions': json['applicationNotificationSubscriptions'] == null ? undefined : json['applicationNotificationSubscriptions'],
    };
}

export function UpdateUserToJSON(json: any): UpdateUser {
    return UpdateUserToJSONTyped(json, false);
}

export function UpdateUserToJSONTyped(value?: UpdateUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'state': value['state'],
        'isAdmin': value['isAdmin'],
        'policy': value['policy'],
        'roles': value['roles'],
        'applicationNotificationSubscriptions': value['applicationNotificationSubscriptions'],
    };
}

