/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The loyalty program whose points' expiry is changed.
 * @export
 * @interface UpdateLoyaltyPointsExpiryBlock1Program
 */
export interface UpdateLoyaltyPointsExpiryBlock1Program {
    /**
     * The ID of the loyalty program.
     */
    id: number;
    /**
     * The internal name of the loyalty program.
     */
    name: string;
    /**
     * The display name of the loyalty program.
     */
    title: string;
}

/**
 * Check if a given object implements the UpdateLoyaltyPointsExpiryBlock1Program interface.
 */
export function instanceOfUpdateLoyaltyPointsExpiryBlock1Program(value: object): value is UpdateLoyaltyPointsExpiryBlock1Program {
    const _v = value as Record<PropertyKey, unknown>;
    if (!('id' in _v) || _v['id'] === undefined) return false;
    if (!('name' in _v) || _v['name'] === undefined) return false;
    if (!('title' in _v) || _v['title'] === undefined) return false;
    return true;
}

export function UpdateLoyaltyPointsExpiryBlock1ProgramFromJSON(json: any): UpdateLoyaltyPointsExpiryBlock1Program {
    return UpdateLoyaltyPointsExpiryBlock1ProgramFromJSONTyped(json, false);
}

export function UpdateLoyaltyPointsExpiryBlock1ProgramFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateLoyaltyPointsExpiryBlock1Program {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'title': json['title'],
    };
}

export function UpdateLoyaltyPointsExpiryBlock1ProgramToJSON(json: any): UpdateLoyaltyPointsExpiryBlock1Program {
    return UpdateLoyaltyPointsExpiryBlock1ProgramToJSONTyped(json, false);
}

export function UpdateLoyaltyPointsExpiryBlock1ProgramToJSONTyped(value?: UpdateLoyaltyPointsExpiryBlock1Program | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'title': value['title'],
    };
}

