/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Update a tier in a specified loyalty program.
 * @export
 * @interface UpdateLoyaltyProgramTier
 */
export interface UpdateLoyaltyProgramTier {
    /**
     * The internal ID of the tier.
     * @type {number}
     * @memberof UpdateLoyaltyProgramTier
     */
    id: number;
    /**
     * The name of the tier.
     * @type {string}
     * @memberof UpdateLoyaltyProgramTier
     */
    name?: string;
    /**
     * The minimum amount of points required to enter the tier.
     * @type {number}
     * @memberof UpdateLoyaltyProgramTier
     */
    minPoints?: number;
}

/**
 * Check if a given object implements the UpdateLoyaltyProgramTier interface.
 */
export function instanceOfUpdateLoyaltyProgramTier(value: object): value is UpdateLoyaltyProgramTier {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function UpdateLoyaltyProgramTierFromJSON(json: any): UpdateLoyaltyProgramTier {
    return UpdateLoyaltyProgramTierFromJSONTyped(json, false);
}

export function UpdateLoyaltyProgramTierFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateLoyaltyProgramTier {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'minPoints': json['minPoints'] == null ? undefined : json['minPoints'],
    };
}

export function UpdateLoyaltyProgramTierToJSON(json: any): UpdateLoyaltyProgramTier {
    return UpdateLoyaltyProgramTierToJSONTyped(json, false);
}

export function UpdateLoyaltyProgramTierToJSONTyped(value?: UpdateLoyaltyProgramTier | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'minPoints': value['minPoints'],
    };
}

