/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * This effect is triggered when a rule that uses a customer's unlocked reward is validated during session evaluation.
 * @export
 * @interface UseRewardEffectProps
 */
export interface UseRewardEffectProps {
    /**
     * The integration ID of the customer reward that was used.
     */
    integrationId: string;
    /**
     * The ID of the reward that was used.
     */
    rewardId: number;
    /**
     * The ID of the Application the reward belongs to.
     */
    applicationId: number;
}

/**
 * Check if a given object implements the UseRewardEffectProps interface.
 */
export function instanceOfUseRewardEffectProps(value: object): value is UseRewardEffectProps {
    const _v = value as Record<PropertyKey, unknown>;
    if (!('integrationId' in _v) || _v['integrationId'] === undefined) return false;
    if (!('rewardId' in _v) || _v['rewardId'] === undefined) return false;
    if (!('applicationId' in _v) || _v['applicationId'] === undefined) return false;
    return true;
}

export function UseRewardEffectPropsFromJSON(json: any): UseRewardEffectProps {
    return UseRewardEffectPropsFromJSONTyped(json, false);
}

export function UseRewardEffectPropsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UseRewardEffectProps {
    if (json == null) {
        return json;
    }
    return {
        
        'integrationId': json['integrationId'],
        'rewardId': json['rewardId'],
        'applicationId': json['applicationId'],
    };
}

export function UseRewardEffectPropsToJSON(json: any): UseRewardEffectProps {
    return UseRewardEffectPropsToJSONTyped(json, false);
}

export function UseRewardEffectPropsToJSONTyped(value?: UseRewardEffectProps | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'integrationId': value['integrationId'],
        'rewardId': value['rewardId'],
        'applicationId': value['applicationId'],
    };
}

