/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TemplateArgDef } from './TemplateArgDef';
import {
    TemplateArgDefFromJSON,
    TemplateArgDefFromJSONTyped,
    TemplateArgDefToJSON,
    TemplateArgDefToJSONTyped,
} from './TemplateArgDef';

/**
 * 
 * @export
 * @interface Webhook
 */
export interface Webhook {
    /**
     * The internal ID of this entity.
     * @type {number}
     * @memberof Webhook
     */
    id: number;
    /**
     * The time this entity was created.
     * @type {Date}
     * @memberof Webhook
     */
    created: Date;
    /**
     * The time this entity was last modified.
     * @type {Date}
     * @memberof Webhook
     */
    modified: Date;
    /**
     * The IDs of the Applications in which this webhook is available.
     * An empty array means the webhook is available in `All Applications`.
     * 
     * @type {Array<number>}
     * @memberof Webhook
     */
    applicationIds: Array<number>;
    /**
     * Name or title for this webhook.
     * @type {string}
     * @memberof Webhook
     */
    title: string;
    /**
     * A description of the webhook.
     * @type {string}
     * @memberof Webhook
     */
    description?: string;
    /**
     * Indicates if the webhook is a draft.
     * @type {boolean}
     * @memberof Webhook
     */
    draft: boolean;
    /**
     * API method for this webhook.
     * @type {string}
     * @memberof Webhook
     */
    verb: WebhookVerbEnum;
    /**
     * API URL (supports templating using parameters) for this webhook.
     * @type {string}
     * @memberof Webhook
     */
    url: string;
    /**
     * List of API HTTP headers for this webhook.
     * @type {Array<string>}
     * @memberof Webhook
     */
    headers: Array<string>;
    /**
     * API payload (supports templating using parameters) for this webhook.
     * @type {string}
     * @memberof Webhook
     */
    payload?: string;
    /**
     * Array of template argument definitions.
     * @type {Array<TemplateArgDef>}
     * @memberof Webhook
     */
    params: Array<TemplateArgDef>;
    /**
     * Enables or disables webhook from showing in the Rule Builder.
     * @type {boolean}
     * @memberof Webhook
     */
    enabled: boolean;
    /**
     * The ID of the credential that this webhook is using.
     * @type {number}
     * @memberof Webhook
     */
    authenticationId?: number;
}


/**
 * @export
 */
export const WebhookVerbEnum = {
    Post: 'POST',
    Put: 'PUT',
    Get: 'GET',
    Delete: 'DELETE',
    Patch: 'PATCH'
} as const;
export type WebhookVerbEnum = typeof WebhookVerbEnum[keyof typeof WebhookVerbEnum];


/**
 * Check if a given object implements the Webhook interface.
 */
export function instanceOfWebhook(value: object): value is Webhook {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('modified' in value) || value['modified'] === undefined) return false;
    if (!('applicationIds' in value) || value['applicationIds'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('draft' in value) || value['draft'] === undefined) return false;
    if (!('verb' in value) || value['verb'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('headers' in value) || value['headers'] === undefined) return false;
    if (!('params' in value) || value['params'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    return true;
}

export function WebhookFromJSON(json: any): Webhook {
    return WebhookFromJSONTyped(json, false);
}

export function WebhookFromJSONTyped(json: any, ignoreDiscriminator: boolean): Webhook {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'created': (new Date(json['created'])),
        'modified': (new Date(json['modified'])),
        'applicationIds': json['applicationIds'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'draft': json['draft'],
        'verb': json['verb'],
        'url': json['url'],
        'headers': json['headers'],
        'payload': json['payload'] == null ? undefined : json['payload'],
        'params': ((json['params'] as Array<any>).map(TemplateArgDefFromJSON)),
        'enabled': json['enabled'],
        'authenticationId': json['authenticationId'] == null ? undefined : json['authenticationId'],
    };
}

export function WebhookToJSON(json: any): Webhook {
    return WebhookToJSONTyped(json, false);
}

export function WebhookToJSONTyped(value?: Webhook | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created': value['created'].toISOString(),
        'modified': value['modified'].toISOString(),
        'applicationIds': value['applicationIds'],
        'title': value['title'],
        'description': value['description'],
        'draft': value['draft'],
        'verb': value['verb'],
        'url': value['url'],
        'headers': value['headers'],
        'payload': value['payload'],
        'params': ((value['params'] as Array<any>).map(TemplateArgDefToJSON)),
        'enabled': value['enabled'],
        'authenticationId': value['authenticationId'],
    };
}

