/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookAuthenticationDataCustom
 */
export interface WebhookAuthenticationDataCustom {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof WebhookAuthenticationDataCustom
     */
    headers: { [key: string]: string; };
}

/**
 * Check if a given object implements the WebhookAuthenticationDataCustom interface.
 */
export function instanceOfWebhookAuthenticationDataCustom(value: object): value is WebhookAuthenticationDataCustom {
    if (!('headers' in value) || value['headers'] === undefined) return false;
    return true;
}

export function WebhookAuthenticationDataCustomFromJSON(json: any): WebhookAuthenticationDataCustom {
    return WebhookAuthenticationDataCustomFromJSONTyped(json, false);
}

export function WebhookAuthenticationDataCustomFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookAuthenticationDataCustom {
    if (json == null) {
        return json;
    }
    return {
        
        'headers': json['headers'],
    };
}

export function WebhookAuthenticationDataCustomToJSON(json: any): WebhookAuthenticationDataCustom {
    return WebhookAuthenticationDataCustomToJSONTyped(json, false);
}

export function WebhookAuthenticationDataCustomToJSONTyped(value?: WebhookAuthenticationDataCustom | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'headers': value['headers'],
    };
}

