/* tslint:disable */
/* eslint-disable */
/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Variant of `CheckAttributeBlock` for the `within` and `not(within)` operators, which require both a start and end value.
 * @export
 * @interface WithinCheckAttributeBlock
 */
export interface WithinCheckAttributeBlock {
    /**
     * The range comparison operator. Must be `within` or `not(within)`.
     */
    operator?: WithinCheckAttributeBlockOperatorEnum;
    /**
     * The start value for the `within` operator.
     */
    start: any | null;
    /**
     * The end value for the `within` operator.
     */
    end: any | null;
    /**
     * When `true`, the `start` value is included in the range for the `within` operator.
     */
    startInclusive?: boolean;
    /**
     * When `true`, the `end` value is included in the range for the `within` operator.
     */
    endInclusive?: boolean;
    /**
     * Indicates whether the `within` operator ignores time zones and compares the wall-clock time only. When `false`, time zones are taken into account.
     */
    timezoneInsensitive?: boolean;
}


/**
 * @export
 */
export const WithinCheckAttributeBlockOperatorEnum = {
    Within: 'within',
    NotWithin: 'not(within)',
} as const;
export type WithinCheckAttributeBlockOperatorEnum = typeof WithinCheckAttributeBlockOperatorEnum[keyof typeof WithinCheckAttributeBlockOperatorEnum];


/**
 * Check if a given object implements the WithinCheckAttributeBlock interface.
 */
export function instanceOfWithinCheckAttributeBlock(value: object): value is WithinCheckAttributeBlock {
    const _v = value as Record<PropertyKey, unknown>;
    if (!('start' in _v) || _v['start'] === undefined) return false;
    if (!('end' in _v) || _v['end'] === undefined) return false;
    return true;
}

export function WithinCheckAttributeBlockFromJSON(json: any): WithinCheckAttributeBlock {
    return WithinCheckAttributeBlockFromJSONTyped(json, false);
}

export function WithinCheckAttributeBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): WithinCheckAttributeBlock {
    if (json == null) {
        return json;
    }
    return {
        
        'operator': json['operator'] == null ? undefined : json['operator'],
        'start': json['start'],
        'end': json['end'],
        'startInclusive': json['startInclusive'] == null ? undefined : json['startInclusive'],
        'endInclusive': json['endInclusive'] == null ? undefined : json['endInclusive'],
        'timezoneInsensitive': json['timezoneInsensitive'] == null ? undefined : json['timezoneInsensitive'],
    };
}

export function WithinCheckAttributeBlockToJSON(json: any): WithinCheckAttributeBlock {
    return WithinCheckAttributeBlockToJSONTyped(json, false);
}

export function WithinCheckAttributeBlockToJSONTyped(value?: WithinCheckAttributeBlock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operator': value['operator'],
        'start': value['start'],
        'end': value['end'],
        'startInclusive': value['startInclusive'],
        'endInclusive': value['endInclusive'],
        'timezoneInsensitive': value['timezoneInsensitive'],
    };
}

